Repository FAForever/fa, pull requests merged in 2018-09, with the labels that each got.

#2581 Removal of friendly collisions
  lua/sim/Unit.lua
Labels: balance

#2583 added CQUEMOV for upgradable building
  units/UAB1103/UAB1103_unit.bp
  units/UAB1202/UAB1202_unit.bp
  units/UAB3101/UAB3101_unit.bp
  units/UAB3102/UAB3102_unit.bp
  units/UAB3201/UAB3201_unit.bp
  units/UAB3202/UAB3202_unit.bp
  units/UEB1103/UEB1103_unit.bp
  units/UEB1202/UEB1202_unit.bp
  units/UEB3101/UEB3101_unit.bp
  units/UEB3102/UEB3102_unit.bp
  units/UEB3201/UEB3201_unit.bp
  units/UEB3202/UEB3202_unit.bp
  units/UEB4202/UEB4202_unit.bp
  units/URB1103/URB1103_unit.bp
  units/URB1202/URB1202_unit.bp
  units/URB3101/URB3101_unit.bp
  units/URB3102/URB3102_unit.bp
  units/URB3201/URB3201_unit.bp
  units/URB3202/URB3202_unit.bp
  units/URB4202/URB4202_unit.bp
  units/URB4206/URB4206_unit.bp
  units/XEB0104/XEB0104_unit.bp
  units/XRB0104/XRB0104_unit.bp
  units/XRB0204/XRB0204_unit.bp
  units/XSB1103/XSB1103_unit.bp
  units/XSB1202/XSB1202_unit.bp
  units/XSB3101/XSB3101_unit.bp
  units/XSB3102/XSB3102_unit.bp
  units/XSB3201/XSB3201_unit.bp
  units/XSB4202/XSB4202_unit.bp
Labels: enhancement, in progress

#2543 remove player color that is to close to civilian one
  lua/GameColors.lua
Labels: in progress

#2585 Sera arty dmg
  projectiles/SIFSuthanusArtilleryShell02/SIFSuthanusArtilleryShell02_script.lua
Labels: balance

#2539 [Issue#1260] Ythotha fix destroy
  units/XSL0401/XSL0401_Script.lua
Labels: balance, in progress
