Repository FAForever/fa, pull requests merged in 2018-10, with the labels that each got.

#2608 make ally/owner triggers the storm by reclaiming
  units/XSL0401/XSL0401_Script.lua
Labels: balance

#2570 An attempt to fix strats. Feel free to leave feedback
  units/UAA0304/UAA0304_Script.lua
  units/UAA0304/UAA0304_unit.bp
  units/UEA0304/UEA0304_Script.lua
  units/UEA0304/UEA0304_unit.bp
  units/URA0304/URA0304_Script.lua
  units/URA0304/URA0304_unit.bp
  units/XSA0304/XSA0304_Script.lua
  units/XSA0304/XSA0304_unit.bp
Labels: balance

#2616 Nuke bp change
  projectiles/AIFQuantumWarhead01/AIFQuantumWarhead01_proj.bp
  projectiles/CIFEMPFluxWarhead01/CIFEMPFluxWarhead01_proj.bp
  projectiles/SIFInainoStrategicMissile01/SIFInainoStrategicMissile01_proj.bp
  projectiles/TIFMissileNuke01/TIFMissileNuke01_proj.bp
  units/UAB2305/UAB2305_unit.bp
  units/UEB2305/UEB2305_unit.bp
  units/URB2305/URB2305_unit.bp
  units/XSB2305/XSB2305_unit.bp
Labels: balance

#2624 Don't try to set invalid army color
  lua/ui/lobby/lobby.lua
Labels: ui

#2613 changing tml missle cost
  projectiles/AIFMissileTactical01/AIFMissileTactical01_proj.bp
  projectiles/CIFMissileTactical03/CIFMissileTactical03_proj.bp
  projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_proj.bp
  projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_proj.bp
  projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_proj.bp
  projectiles/TIFMissileCruise01/TIFMissileCruise01_proj.bp
  projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_proj.bp
Labels: balance

#2628 Relocate versionnr
  lua/ui/lobby/lobby.lua
Labels: lobby, ui

#2622 Disable notify during cinematics
  lua/ui/notify/notify.lua
Labels: ui
