Repository FAForever/fa, pull requests merged in 2020-05, with the labels that each got.

#3080 update changelogData.lua and changelog.md
  changelog.md
  lua/ui/lobby/changelogData.lua
Labels: area: balance

#3065 Fix bigger strat icons
  lua/ui/game/construction.lua
Labels: area: ui

#3067 Sera SCU changes
  units/XSL0301/XSL0301_script.lua
  units/XSL0301/XSL0301_unit.bp
Labels: area: balance

#3066 UEF SCU changes
  lua/terranprojectiles.lua
  projectiles/TDFFragmentationGrenade02/TDFFragmentationGrenade02_proj.bp
  projectiles/TDFFragmentationGrenade02/TDFFragmentationGrenade02_script.lua
  units/UEL0301/UEL0301_script.lua
  units/UEL0301/UEL0301_unit.bp
Labels: area: balance

#3063 Cyb SCU changes
  lua/sim/Buff.lua
  units/URL0301/URL0301_script.lua
  units/URL0301/URL0301_unit.bp
Labels: area: balance

#3106 rebalance T3 sonar stealth
  units/URS0305/URS0305_unit.bp
Labels: area: balance

#3116 Scu changes
  loc/US/strings_db.lua
  lua/sim/Buff.lua
  lua/terranprojectiles.lua
  lua/ui/help/unitdescription.lua
  projectiles/TDFFragmentationGrenade02/TDFFragmentationGrenade02_proj.bp
  projectiles/TDFFragmentationGrenade02/TDFFragmentationGrenade02_script.lua
  textures/ui/common/icons/units/UAL0301_NanoCombat_icon.dds
  textures/ui/common/icons/units/XSL0301_AdvancedCombat_icon.dds
  units/UAB0304/UAB0304_unit.bp
  units/UAL0301/UAL0301_script.lua
  units/UAL0301/UAL0301_unit.bp
  units/UEB0304/UEB0304_unit.bp
  units/UEL0301/UEL0301_script.lua
  units/UEL0301/UEL0301_unit.bp
  units/URB0304/URB0304_unit.bp
  units/URL0301/URL0301_script.lua
  units/URL0301/URL0301_unit.bp
  units/XSB0304/XSB0304_unit.bp
  units/XSL0301/XSL0301_script.lua
  units/XSL0301/XSL0301_unit.bp
Labels: area: balance

#3064 Window Resize Fix
  lua/maui/window.lua
Labels: status: ready-to-merge
