Repository FAForever/fa, pull requests merged in 2020-03, with the labels that each got.

#3019 fix regen field for scu and t4
  lua/sim/Buff.lua
  units/XSL0001/XSL0001_script.lua
  units/XSL0001/XSL0001_unit.bp
Labels: area: balance

#2978 T3 mobile artilery nerf
  projectiles/CIFArtilleryProton01/CIFArtilleryProton01_script.lua
  projectiles/CIFArtilleryProton02/CIFArtilleryProton02_proj.bp
  projectiles/CIFArtilleryProton02/CIFArtilleryProton02_script.lua
  projectiles/CIFArtilleryProton03/CIFArtilleryProton03_proj.bp
  projectiles/CIFArtilleryProton03/CIFArtilleryProton03_script.lua
  units/UAL0304/UAL0304_unit.bp
  units/UEL0304/UEL0304_unit.bp
  units/URB2302/URB2302_unit.bp
  units/URL0304/URL0304_unit.bp
  units/URL0401/URL0401_unit.bp
  units/XSL0304/XSL0304_unit.bp
Labels: area: balance

#2998 Czar movementspeed adjustment
  units/UAA0310/UAA0310_unit.bp
Labels: area: balance

#2776 rebalance Quantum Gateway
  units/UAB0304/UAB0304_unit.bp
  units/UEB0304/UEB0304_unit.bp
  units/URB0304/URB0304_unit.bp
  units/XSB0304/XSB0304_unit.bp
Labels: area: balance

#2856 replace sera scu advanced combat preset by rambo
  loc/US/strings_db.lua
  lua/ui/help/unitdescription.lua
  textures/ui/common/icons/units/XSL0301_AdvancedCombat_icon.dds
  units/XSL0301/XSL0301_unit.bp
Labels: area: balance

#2866 scu raw and ras rework
  units/UAL0301/UAL0301_unit.bp
  units/UEL0301/UEL0301_unit.bp
  units/URL0301/URL0301_unit.bp
  units/XSL0301/XSL0301_unit.bp
Labels: area: balance

#3027 Improve Sim Dialogue
  lua/ui/game/simdialogue.lua
Labels: area: ui, type: enhancement

#2907 Corrects text display if video doesn't play
  lua/ui/game/missiontext.lua
Labels: area: coop

#2948 Added PauseUnitDeath control
  lua/ScenarioFramework.lua
Labels: area: coop
