Repository FAForever/fa, pull requests merged in 2020-11, with the labels that each got.

#3192 Labs and t1 tanks tweaks
  units/UAL0106/UAL0106_unit.bp
  units/UAL0201/UAL0201_unit.bp
  units/UEL0106/UEL0106_unit.bp
  units/URL0106/URL0106_unit.bp
  units/URL0107/URL0107_unit.bp
  units/XSL0101/XSL0101_unit.bp
Labels: area: balance

#3189 T1 bomber and scout adjustments
  units/UAA0101/UAA0101_unit.bp
  units/UAA0103/UAA0103_unit.bp
  units/UEA0101/UEA0101_unit.bp
  units/UEA0103/UEA0103_unit.bp
  units/URA0101/URA0101_unit.bp
  units/URA0103/URA0103_unit.bp
  units/XSA0101/XSA0101_unit.bp
  units/XSA0103/XSA0103_unit.bp
Labels: area: balance

#3170 Improve BaseManager unit upgrades
  lua/AI/OpAI/BaseManager.lua
Labels: area: coop, area: sim, type: enhancement

#3180 Allow sending resources only to allies
  lua/SimUtils.lua
Labels: area: sim

#3184 increase performance of table.empty and math.round
  lua/system/utils.lua
Labels: status: ready-to-merge

#3187 Add option to hide resource markers on preview
  lua/ui/controls/resmappreview.lua
  lua/ui/lobby/lobby.lua
Labels: area: ui

#3194 Improve build effects logic
  lua/EffectUtilities.lua
  lua/terranunits.lua
  units/UEL0001/UEL0001_script.lua
  units/UEL0301/UEL0301_script.lua
Labels: area: sim

#3196 Simplify Sera effect flash at finished structure
  lua/EffectUtilities.lua
Labels: area: sim

#3197 Speed up Aeon shields death animation
  units/UAB4202/UAB4202_unit.bp
  units/UAB4301/UAB4301_unit.bp
Labels: area: sim

#3198 Remove set up of build effect from TShield
  lua/terranunits.lua
Labels: area: sim

#3210 Add link to the patchnotes to the changelog popup
  lua/ui/lobby/changelog.lua
Labels: area: ui, type: enhancement

#3213 Fixed unit cap displaying in coop
  lua/ui/game/objectives2.lua
Labels: area: ui

#3158 death explosion t4 nuke launcher
  effects/QuantumWarhead/QuantumWarheadEffect01_proj.bp
  projectiles/SIFExperimentalStrategicDeath01/SIFExperimentalStrategicDeath01_proj.bp
  projectiles/SIFExperimentalStrategicDeath01/SIFExperimentalStrategicDeath01_script.lua
  units/XSB2401/XSB2401_script.lua
  units/XSB2401/XSB2401_unit.bp
Labels: area: balance

#3204 OC dmg/e ratio 1/4
  lua/sim/DefaultProjectiles.lua
  units/UAL0001/UAL0001_unit.bp
  units/UEL0001/UEL0001_unit.bp
  units/URL0001/URL0001_unit.bp
  units/XSL0001/XSL0001_unit.bp
  units/XSL0301/XSL0301_unit.bp
Labels: area: balance

#3207 Make yolo a little smoother
  units/XSB2401/XSB2401_unit.bp
Labels: area: balance

#3208 t1 airscout masscost 50 -> 40
  units/UAA0101/UAA0101_unit.bp
  units/UEA0101/UEA0101_unit.bp
  units/URA0101/URA0101_unit.bp
  units/XSA0101/XSA0101_unit.bp
Labels: area: balance

#3205 Range bot nerf
  units/DEL0204/DEL0204_unit.bp
  units/DRL0204/DRL0204_unit.bp
  units/UAL0307/UAL0307_unit.bp
  units/UEL0307/UEL0307_unit.bp
Labels: area: balance
