Repository FAForever/fa, pull requests merged in 2020-02, with the labels that each got.

#2976 Fixed position autofill window when resize the gamewindow
  lua/ui/lobby/lobby.lua
Labels: area: lobby

#2989 Fix building effect playing twice for command units
  lua/defaultunits.lua
Labels: area: sim

#2983 Improve Frigate sink animation rate
  units/UAS0103/UAS0103_unit.bp
  units/URS0103/URS0103_unit.bp
Labels: area: unit-blueprint, type: enhancement

#2979 stealth boat size increase, maneuverability nerf
  units/XRS0205/XRS0205_unit.bp
Labels: area: balance

#2977 notha fix
  units/XSA0202/XSA0202_unit.bp
Labels: area: balance

#2973 Banel.. i mean beetle stuff
  effects/emitters/cannon_muzzle_smoke_12_emit.bp
  units/XRL0302/XRL0302_Script.lua
  units/XRL0302/XRL0302_unit.bp
Labels: area: balance

#2966 normalize gunship behavior
  units/UEA0203/UEA0203_unit.bp
  units/XRA0105/XRA0105_unit.bp
Labels: area: balance

#2949 Fix Aurora missing first shot
  units/UAL0201/UAL0201_unit.bp
Labels: area: balance

#2997 Don't set the center background Tiled in the popout window
  lua/ui/controls/ninepatch.lua
Labels: area: ui

#2993 Fixed closing spawning menu by Alt+F2
  lua/ui/dialogs/createunit.lua
Labels: area: ui
