Repository FAForever/fa, pull requests merged in 2021-06, with the labels that each got.

#3291 Fix bugged acu button textoverlay labels when opening large map preview for second time
  lua/ui/controls/acubutton.lua
Labels: area: lobby

#3297 Add dock hotkey with translations
  loc/CN/strings_db.lua
  loc/CZ/strings_db.lua
  loc/DE/strings_db.lua
  loc/ES/strings_db.lua
  loc/FR/strings_db.lua
  loc/IT/strings_db.lua
  loc/PL/strings_db.lua
  loc/RU/strings_db.lua
  loc/TW/strings_db.lua
  loc/TZM/strings_db.lua
  loc/US/strings_db.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/ui/game/orders.lua
Labels: area: ui

#3309 Slight tweak of UEF T1 bomber
  units/UEA0103/UEA0103_unit.bp
Labels: area: balance

#3311 Buff BT and E cost of Loya & Titan
  units/UEL0303/UEL0303_unit.bp
  units/URL0303/URL0303_unit.bp
Labels: area: balance

#3308 Increase the BT of Fobo
  units/XSL0103/XSL0103_unit.bp
Labels: area: balance
