Repository FAForever/fa, pull requests merged in 2021-11, with the labels that each got.

#3512 Fixes ai detection and threat addition
  lua/defaultunits.lua
  lua/simInit.lua
Labels: area: AI

#3119 Add dummy Weapon to Tech 1 transporter
  units/UAA0107/UAA0107_Script.lua
  units/UAA0107/UAA0107_unit.bp
  units/UEA0107/UEA0107_Script.lua
  units/UEA0107/UEA0107_unit.bp
  units/URA0107/URA0107_Script.lua
  units/URA0107/URA0107_unit.bp
  units/XSA0107/XSA0107_Script.lua
  units/XSA0107/XSA0107_unit.bp
Labels: area: balance

#3569 Revert the maxRadius changes for strategic bombers
  units/UAA0304/UAA0304_unit.bp
  units/UEA0304/UEA0304_unit.bp
  units/URA0304/URA0304_unit.bp
  units/XSA0304/XSA0304_unit.bp
Labels: type: bug, area: balance, priority: critical
