Repository FAForever/fa, pull requests merged in 2021-07, with the labels that each got.

#3286 Fix shield ApplyDamage() function for ACU overcharge
  lua/shield.lua
Labels: status: ready-to-merge, type: bug

#3314 fix ArmyBrain result not equal to defeat bug in Sorian AI logic
  lua/AI/AIBuilders/SorianStrategyBuilders.lua
  lua/editor/SorianBuildConditions.lua
  lua/platoon.lua
Labels: area: AI, status: ready-to-merge, type: bug

#3301 fix BaseMonitorPlatoonDistress function from creating infinite table …
  lua/aibrain.lua
Labels: area: AI, status: ready-to-merge, type: bug

#3313 New link for curated map button
  lua/ui/lobby/lobby.lua
Labels: area: lobby, status: ready-to-merge, type: bug
