Repository FAForever/fa, pull requests merged in 2022-11, with the labels that each got.

#4287 Adjust factory behavior when building and finished building a unit
  engine/Core.lua
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/aibrain.lua
  lua/defaultunits.lua
  lua/sim/Unit.lua
Labels: area: balance

#4366 Make changelog slightly transparent
  lua/ui/lobby/changelog.lua
Labels: area: ui, area: lobby

#4421 Turn all imports of build conditions into lower case
  lua/AI/AIBuilders/AIAirAttackBuilders.lua
  lua/AI/AIBuilders/AIArtilleryBuilders.lua
  lua/AI/AIBuilders/AIDefenseBuilders.lua
  lua/AI/AIBuilders/AIEconomicBuilders.lua
  lua/AI/AIBuilders/AIEconomyUpgradeBuilders.lua
  lua/AI/AIBuilders/AIExpansionBuilders.lua
  lua/AI/AIBuilders/AIExperimentalBuilders.lua
  lua/AI/AIBuilders/AIFactoryConstructionBuilders.lua
  lua/AI/AIBuilders/AIIntelBuilders.lua
  lua/AI/AIBuilders/AILandAttackBuilders.lua
  lua/AI/AIBuilders/AINavalBuilders.lua
  lua/AI/AIBuilders/AISeaAttackBuilders.lua
  lua/AI/AIBuilders/SorianAirAttackBuilders.lua
  lua/AI/AIBuilders/SorianArtilleryBuilders.lua
  lua/AI/AIBuilders/SorianDefenseBuilders.lua
  lua/AI/AIBuilders/SorianEconomicBuilders.lua
  lua/AI/AIBuilders/SorianEconomyUpgradeBuilders.lua
  lua/AI/AIBuilders/SorianExpansionBuilders.lua
  lua/AI/AIBuilders/SorianExperimentalBuilders.lua
  lua/AI/AIBuilders/SorianFactoryConstructionBuilders.lua
  lua/AI/AIBuilders/SorianIntelBuilders.lua
  lua/AI/AIBuilders/SorianLandAttackBuilders.lua
  lua/AI/AIBuilders/SorianNavalBuilders.lua
  lua/AI/AIBuilders/SorianSeaAttackBuilders.lua
  lua/AI/AIBuilders/SorianStrategyBuilders.lua
  lua/AI/AIBuilders/SorianStrategyPlatoonBuilders.lua
  lua/AI/OpAI/BaseManager.lua
  lua/AI/OpAI/BaseManagerEngineerBuilders.lua
  lua/AI/OpAI/BaseOpAI.lua
  lua/AI/OpAI/NavalOpAI.lua
  lua/AI/OpAI/ReactiveAI.lua
  lua/AI/Strategy-Test.lua
  lua/sim/BrainConditionsMonitor.lua
  lua/system/utils.lua
Labels: area: sim, area: AI

#4433 Allow Sparkys to Build Stealth and T1 Factories
  units/XEL0209/XEL0209_unit.bp
Labels: area: balance

#4428 Add Jamming to UEF strats and spy planes
  units/UEA0302/UEA0302_unit.bp
  units/UEA0304/UEA0304_Script.lua
  units/UEA0304/UEA0304_unit.bp
Labels: area: balance

#4455 AI - Change ReturnToBaseAI to use factorymanager rallypoint
  lua/platoon.lua
Labels: area: AI
