Repository FAForever/fa, pull requests merged in 2022-09, with the labels that each got.

#4101 Integrated STP with Category Support
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/misckeyactions.lua
Labels: area: balance, area: sim, area: ui

#4201 Fix issues with Ythotha
  units/XSL0401/XSL0401_unit.bp
Labels: type: bug

#4202 Fix duration of death animations
  lua/defaultexplosions.lua
  lua/defaultunits.lua
  lua/utilities.lua
Labels: type: bug

#4214 Reorder Lobby Options
  lua/ui/lobby/lobbyOptions.lua
Labels: area: lobby

#4200 Introduce depth scanning feature
  lua/options/options.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/cursor/depth.lua
  lua/ui/game/cursor/hover.lua
  lua/ui/game/gamemain.lua
Labels: area: ui

#4220 Attempt at fixing the issues with the depth scanning
  lua/ui/game/cursor/depth.lua
  lua/ui/game/cursor/hover.lua
  lua/ui/game/gamemain.lua
Labels: area: ui

#4225 Make Harbinger behave like SACU's
  lua/system/blueprints-units.lua
  units/UAL0303/UAL0303_unit.bp
Labels: area: balance, area: requires engine patch

#4234 Fix "reveal civilians" not resetting civilians to neutral
  lua/sim/ScenarioUtilities.lua
Labels: type: bug

#4226 Decouple UI intialization and laying out
  engine/User/UserUnit.lua
  lua/lazyvar.lua
  lua/maui/border.lua
  lua/maui/layouthelpers.lua
  lua/maui/window.lua
  lua/system/Localization.lua
  lua/system/class.lua
  lua/ui/game/diplomacy.lua
  lua/ui/game/gamemain.lua
  lua/ui/game/recall.lua
  lua/ui/lobby/data/watchedvalue/watchedvalue.lua
  lua/ui/uiutil.lua
Labels: area: ui

#4237 Change `self.Fun(self, ...)` to `self:Fun(...)`
  engine/Sim.lua
  lua/aeonprojectiles.lua
  lua/cybranprojectiles.lua
  lua/defaultunits.lua
  lua/keymap/hotkeylabels.lua
  lua/proptree.lua
  lua/sim/DefaultProjectiles.lua
  lua/sim/Entity.lua
  lua/sim/Prop.lua
  lua/sim/Unit.lua
  lua/system/class.lua
  lua/ui/controls/filepicker.lua
  lua/ui/dialogs/options.lua
  lua/ui/game/tooltip.lua
  lua/ui/lobby/ModsManager.lua
  lua/ui/lobby/chatarea.lua
  lua/ui/lobby/lobby.lua
  lua/wreckage.lua
  projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
  projectiles/AANDepthCharge03/AANDepthCharge03_script.lua
  projectiles/AANTorpedoClusterSplit01/AANTorpedoClusterSplit01_script.lua
  projectiles/CANTorpedoNanite02/CANTorpedoNanite02_script.lua
  projectiles/CANTorpedoNanite03/CANTorpedoNanite03_script.lua
  projectiles/CIFBrackmanHackPegs02/CIFBrackmanHackPegs02_script.lua
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua
  units/UAL0401/UAL0401_Script.lua
  units/UEL0301/UEL0301_script.lua
  units/URL0001/URL0001_script.lua
  units/URL0301/URL0301_script.lua
  units/URS0201/URS0201_script.lua
  units/XRB2308/XRB2308_script.lua
  units/XRB2309/XRB2309_script.lua
  units/XRL0302/XRL0302_Script.lua
  units/XSL0401/XSL0401_Script.lua
Labels: area: code style

#4232 Optimize Reclaim Labels attempt 69
  init.lua
  init_faf.lua
  init_fafbeta.lua
  init_fafdevelop.lua
  init_shared.lua
  lua/ui/game/gamemain.lua
  lua/ui/game/reclaim.lua
Labels: area: ui

#4228 Add key action localization directives
  lua/keymap/keymapper.lua
  lua/system/Localization.lua
  lua/ui/lobby/lobby.lua
  lua/ui/menus/main.lua
Labels: area: ui

#4227 Annotate UI Controls part 1
  engine/AnnotationCommon.lua
  engine/User.lua
  engine/User/CMauiEdit.lua
  lua/maui/bitmap.lua
  lua/maui/button.lua
  lua/maui/checkbox.lua
  lua/maui/control.lua
  lua/maui/cursor.lua
  lua/maui/dragger.lua
  lua/maui/frame.lua
  lua/maui/group.lua
  lua/maui/mesh.lua
  lua/maui/scrollbar.lua
  lua/ui/controls/border.lua
  lua/ui/controls/checkbox.lua
  lua/ui/controls/mappreview.lua
  lua/ui/controls/ninepatch.lua
Labels: area: ui

#4238 More minor changes
  engine/Library.lua
  lua/system/Blueprints.lua
  lua/system/class.lua
  lua/system/dkson.lua
  lua/system/performance.lua
  lua/tests/lazyvar_test.lua
  lua/ui/campaign/campaignmanager.lua
  lua/ui/campaign/campaignmovies.lua
  lua/ui/campaign/operationbriefing.lua
  lua/ui/campaign/selectcampaign.lua
  lua/ui/controls/combo.lua
  lua/ui/controls/specialgrid.lua
  lua/ui/dialogs/AIUtilitiesView.lua
  lua/ui/dialogs/console.lua
  lua/ui/dialogs/createprop.lua
  lua/ui/dialogs/createunit.lua
  lua/ui/dialogs/disconnect.lua
  lua/ui/dialogs/eschandler.lua
  lua/ui/dialogs/hotstats.lua
  lua/ui/dialogs/keybindings.lua
  lua/ui/dialogs/mapselect.lua
  lua/ui/dialogs/myeffecthelpers.lua
  lua/ui/dialogs/options.lua
  lua/ui/dialogs/profile.lua
  lua/ui/dialogs/replay.lua
  lua/ui/dialogs/saveload.lua
  lua/ui/dialogs/score.lua
Labels: type: intellisense
