Repository FAForever/fa, pull requests merged in 2022-08, with the labels that each got.

#4092 Fix the guard return radius of naval units
  units/UAS0102/UAS0102_unit.bp
  units/UAS0103/UAS0103_unit.bp
  units/UAS0201/UAS0201_unit.bp
  units/UAS0202/UAS0202_unit.bp
  units/UAS0203/UAS0203_unit.bp
  units/UAS0302/UAS0302_unit.bp
  units/UAS0303/UAS0303_unit.bp
  units/UAS0304/UAS0304_unit.bp
  units/UAS0401/UAS0401_unit.bp
  units/UES0103/UES0103_unit.bp
  units/UES0201/UES0201_unit.bp
  units/UES0202/UES0202_unit.bp
  units/UES0203/UES0203_unit.bp
  units/UES0302/UES0302_unit.bp
  units/UES0304/UES0304_unit.bp
  units/UES0401/UES0401_unit.bp
  units/URS0103/URS0103_unit.bp
  units/URS0201/URS0201_unit.bp
  units/URS0202/URS0202_unit.bp
  units/URS0203/URS0203_unit.bp
  units/URS0302/URS0302_unit.bp
  units/URS0303/URS0303_unit.bp
  units/URS0304/URS0304_unit.bp
  units/XAS0204/XAS0204_unit.bp
  units/XAS0306/XAS0306_unit.bp
  units/XES0102/XES0102_unit.bp
  units/XES0205/XES0205_unit.bp
  units/XES0307/XES0307_unit.bp
  units/XRS0204/XRS0204_unit.bp
  units/XRS0205/XRS0205_unit.bp
  units/XSS0103/XSS0103_unit.bp
  units/XSS0201/XSS0201_unit.bp
  units/XSS0202/XSS0202_unit.bp
  units/XSS0203/XSS0203_unit.bp
  units/XSS0302/XSS0302_unit.bp
  units/XSS0303/XSS0303_unit.bp
  units/XSS0304/XSS0304_unit.bp
Labels: area: sim

#4093 Add guard if the weapon has been destroyed
  units/UAL0307/UAL0307_script.lua
  units/UEL0307/UEL0307_script.lua
  units/XRL0403/XRL0403_script.lua
  units/XSL0307/XSL0307_script.lua
Labels: area: sim

#4110 Add guard when creating impact effects
  lua/shield.lua
Labels: area: sim

#4109 Add check if on overcharge if weapon is destroyed
  lua/sim/DefaultProjectiles.lua
Labels: area: sim

#4103 Fix a shield assist bug where resources were sent into Limbo
  lua/defaultunits.lua
Labels: area: sim

#4113 Reduce projectile speed of air to air weapons
  units/DEA0202/DEA0202_unit.bp
  units/UAA0102/UAA0102_unit.bp
  units/UAA0303/UAA0303_unit.bp
  units/UEA0102/UEA0102_unit.bp
  units/UEA0303/UEA0303_unit.bp
  units/URA0102/URA0102_unit.bp
  units/XAA0202/XAA0202_unit.bp
  units/XSA0102/XSA0102_unit.bp
  units/XSA0202/XSA0202_unit.bp
  units/XSA0303/XSA0303_unit.bp
  units/XSL0305/XSL0305_unit.bp
Labels: area: balance, area: sim

#4125 Fix Solace not having the bomber category
  units/XAA0306/XAA0306_unit.bp
Labels: area: sim

#4111 Reduce memory impact of weapons
  lua/sim/defaultweapons.lua
  lua/sim/weapon.lua
  units/DSLK004/DSLK004_unit.bp
  units/XEA0002/XEA0002_unit.bp
  units/XES0307/XES0307_unit.bp
  units/XSB2301/XSB2301_unit.bp
  units/XSS0201/XSS0201_unit.bp
Labels: area: balance

#4132 Fix The Mass Left Behind when the upgrade kennel is destroyed
  units/XEB0204/XEB0204_unit.bp
Labels: area: balance, area: sim

#4144 Fix the death animation of the tempest
  lua/sim/Unit.lua
  units/UAS0401/UAS0401_unit.bp
Labels: area: sim

#4141 Reduce pre-allocated trashbag count
  lua/cybranunits.lua
  lua/defaultunits.lua
  lua/sim/Unit.lua
Labels: area: sim

#4140 Remove cache concept of units
  lua/EffectUtilitiesAeon.lua
  lua/EffectUtilitiesSeraphim.lua
  lua/defaultunits.lua
  lua/shield.lua
  lua/sim/Unit.lua
Labels: area: sim

#4152 Fix HQs not working
  lua/defaultunits.lua
Labels: area: sim

#3916 Passing statistics of individual units to UI
  lua/sim/Prop.lua
  lua/sim/Unit.lua
  lua/system/blueprints-units.lua
  lua/ui/game/layouts/unitview_left.lua
  lua/ui/game/layouts/unitview_mini.lua
  lua/ui/game/unitview.lua
  lua/utilities.lua
  textures/ui/common/game/unit_view_icons/reclaim_alt_energy.dds
  textures/ui/common/game/unit_view_icons/reclaim_alt_mass.dds
  textures/ui/common/game/unit_view_icons/reclaim_energy.dds
  textures/ui/common/game/unit_view_icons/reclaim_mass.dds
Labels: area: sim

#4154 Fix beam weapons everlasting
  lua/sim/defaultweapons.lua
Labels: area: sim

#4155 Fix the balance of some of the adjusted mechanics
  lua/aeonweapons.lua
  projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_proj.bp
  projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_proj.bp
  projectiles/TIFMissileCruise04/TIFMissileCruise04_proj.bp
Labels: area: balance, area: sim

#4156 Remove LOG statement and add guards
  lua/SimCallbacks.lua
  lua/SimHooks.lua
  lua/sim/Unit.lua
Labels: area: sim

#4159 Do not gift units that are not finished
  changelog-dev.md
  lua/SimUtils.lua
Labels: area: sim

#4160 Add a check if the shield is destroyed
  lua/shield.lua
Labels: area: sim

#4162 Re-introduce `table.insert` over using a separate counter
  lua/sim/defaultweapons.lua
Labels: area: sim

#4161 Changelog 3741
  changelog-dev.md
  changelog.md
  lua/ui/lobby/changelogData.lua
  lua/version.lua
  mod_info.lua
Labels: area: ui

#4169 Fix internal state of HQs
  lua/defaultunits.lua
Labels: area: sim

#4173 Fix typo
  lua/sim/defaultweapons.lua
Labels: area: sim

#4166 Fix LOD1 of T1 Seraphim Power Generator - it was rotated
  units/XSB1101/XSB1101_lod1.scm
Labels: area: sim

#4119 Extend functionality of selection sets (control groups)
  engine/User/CameraImpl.lua
  init_faf.lua
  init_fafbeta.lua
  init_fafdevelop.lua
  init_shared.lua
  lua/SimCallbacks.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/options/options.lua
  lua/options/optionsLogic.lua
  lua/ui/dialogs/options.lua
  lua/ui/game/selection.lua
  lua/ui/game/selectionsort.lua
Labels: area: ui

#4124 Improved cursor / command behaviors
  effects/mesh.fx
  init_faf.lua
  init_fafbeta.lua
  init_fafdevelop.lua
  init_shared.lua
  lua/keymap/keyactions.lua
  lua/options/options.lua
  lua/skins/skins.lua
  lua/ui/controls/worldview.lua
  lua/ui/game/commandmode.lua
  lua/ui/help/tooltips.lua
  lua/usercamera.lua
  meshes/game/PathCylinder_LOD0.scm
  meshes/game/PathRing_LOD0.scm
  meshes/game/PathSquare_LOD0.scm
  textures/ui/common/game/cursors/disabled.png
  textures/ui/common/game/cursors/reclaim-disabled.tga
Labels: area: ui

#4180 refactor AI economy conditions
  lua/editor/EconomyBuildConditions.lua
Labels: area: sim, area: AI

#4188 Share mouse position of players with observers
  engine/User.lua
  engine/User/CUIWorldMesh.lua
  lua/UserSync.lua
  lua/maui/control.lua
  lua/ui/game/casting/mouse.lua
  lua/ui/game/gamemain.lua
Labels: area: ui
