Repository FAForever/fa, pull requests merged in 2023-02, with the labels that each got.

#4663 Fix infinite loop of treads
  lua/defaultcomponents.lua
  units/URL0104/URL0104_unit.bp
Labels: area: sim

#4638 Fix incorrect substitution in shader
  effects/mesh.fx
Labels: area: graphics

#4576 Reduce impact of intel management on simulation
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/RemoteViewing.lua
  lua/aeonunits.lua
  lua/aibrain.lua
  lua/defaultcomponents.lua
  lua/defaultunits.lua
  lua/shield.lua
  lua/sim/Unit.lua
  lua/system/Blueprints.lua
  lua/system/blueprints-units.lua
  lua/terranunits.lua
  units/UAB3101/UAB3101_script.lua
  units/UAB3104/UAB3104_script.lua
  units/UAB3201/UAB3201_script.lua
  units/UEB3104/UEB3104_script.lua
  units/UEB3201/UEB3201_script.lua
  units/UEL0301/UEL0301_script.lua
  units/URB3101/URB3101_script.lua
  units/URB3104/URB3104_script.lua
  units/URB3201/URB3201_script.lua
  units/URL0001/URL0001_script.lua
  units/URL0101/URL0101_unit.bp
  units/URL0203/URL0203_script.lua
  units/URL0301/URL0301_script.lua
  units/XRB3301/XRB3301_script.lua
  units/XRS0205/XRS0205_script.lua
  units/XSB3101/XSB3101_script.lua
  units/XSB3104/XSB3104_script.lua
  units/XSB3201/XSB3201_script.lua
Labels: area: sim

#4664 fixing conflicts from last branch
  units/URB0102/URB0102_Albedo.dds
  units/URB0102/URB0102_Aupgrade.sca
  units/URB0102/URB0102_Aupgrade_sup.sca
  units/URB0102/URB0102_SpecTeam.dds
  units/URB0102/URB0102_lod0.scm
  units/URB0102/URB0102_lod1.scm
  units/URB0102/URB0102_lod1_Albedo.dds
  units/URB0102/URB0102_lod1_SpecTeam.dds
  units/URB0102/URB0102_lod1_normalsTS.dds
  units/URB0102/URB0102_normalsTS.dds
  units/URB0102/URB0102_script.lua
  units/URB0102/URB0102_unit.bp
  units/URB0202/URB0202_Aupgrade.sca
  units/URB0202/URB0202_lod0.scm
  units/URB0202/URB0202_lod1.scm
  units/URB0202/URB0202_script.lua
  units/URB0202/URB0202_unit.bp
  units/URB0302/URB0302_lod0.scm
  units/URB0302/URB0302_lod1.scm
  units/URB0302/URB0302_script.lua
  units/URB0302/URB0302_unit.bp
  units/ZRB9502/ZRB9502_Aupgrade.sca
  units/ZRB9502/ZRB9502_lod0.scm
  units/ZRB9502/ZRB9502_lod1.scm
  units/ZRB9502/ZRB9502_script.lua
  units/ZRB9502/ZRB9502_unit.bp
  units/ZRB9602/ZRB9602_lod0.scm
  units/ZRB9602/ZRB9602_lod1.scm
  units/ZRB9602/ZRB9602_script.lua
  units/ZRB9602/ZRB9602_unit.bp
Labels: area: pbr

#4665 Cybran air factories fix
  units/ZRB9502/ZRB9502_Albedo.dds
  units/ZRB9502/ZRB9502_SpecTeam.dds
  units/ZRB9502/ZRB9502_lod1_Albedo.dds
  units/ZRB9502/ZRB9502_lod1_SpecTeam.dds
  units/ZRB9502/ZRB9502_lod1_normalsTS.dds
  units/ZRB9502/ZRB9502_normalsTS.dds
  units/ZRB9602/ZRB9602_Albedo.dds
  units/ZRB9602/ZRB9602_SpecTeam.dds
  units/ZRB9602/ZRB9602_lod1_Albedo.dds
  units/ZRB9602/ZRB9602_lod1_SpecTeam.dds
  units/ZRB9602/ZRB9602_lod1_normalsTS.dds
  units/ZRB9602/ZRB9602_normalsTS.dds
Labels: area: pbr

#4668 Fix trees not falling when colliding with units
  lua/proptree.lua
Labels: type: bug, area: sim

#4669 Fix logging of intel and Parashield not having its effects
  lua/defaultcomponents.lua
  lua/system/blueprints-units.lua
  units/UEL0307/UEL0307_script.lua
Labels: area: sim

#4442 GC Claw Adjustment
  lua/aeonweapons.lua
Labels: area: balance

#3918 Initial Chrono Dampener effect based on implementation of Deribus
  effects/emitters/aeon_chrono_dampener_large_01_emit.bp
  effects/emitters/aeon_chrono_dampener_large_02_emit.bp
  effects/emitters/aeon_chrono_dampener_large_03_emit.bp
  effects/emitters/aeon_chrono_dampener_large_04_emit.bp
  lua/EffectTemplates.lua
  lua/aeonweapons.lua
  units/UAL0001/UAL0001_unit.bp
Labels: area: balance

#4672 Fix missed replacement
  lua/sim/Buff.lua
Labels: type: bug, area: sim

#4675 Dynamically compute LODs of units like we do with props
  engine/Core/Blueprints/ProjectileBlueprint.lua
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/SimCallbacks.lua
  lua/aibrain.lua
  lua/defaultunits.lua
  lua/sim/ScenarioUtilities.lua
  lua/system/blueprints-lod.lua
  lua/tarmacs.lua
Labels: area: graphics

#4678 Add more imports to break cycle in import dependencies
  lua/simInit.lua
Labels: type: bug, area: sim

#4679 Remove the intel disables table, it is no longer used by base game
  lua/sim/Unit.lua
Labels: area: sim

#4680 Revert a few decisions made the past year
  lua/sim/Unit.lua
  lua/sim/weapon.lua
Labels: type: bug, area: sim

#4569 Generate expansion markers
  engine/User/UserUnit.lua
  lua/AI/aiattackutilities.lua
  lua/platoon.lua
  lua/sim/MapUtilities.lua
  lua/sim/MarkerGenerator.lua
  lua/sim/MarkerUtilities.lua
  lua/sim/NavDatastructures.lua
  lua/sim/NavGenerator.lua
  lua/ui/game/MapUtilitiesMarkersTab.lua
Labels: area: nav-mesh

#4681 Factor out hash operations and reduce number of fields of projectiles
  engine/Core/Blueprints/ProjectileBlueprint.lua
  lua/sim/DefaultProjectiles.lua
  lua/sim/Projectile.lua
  lua/system/class.lua
  lua/ui/game/casting/mouse.lua
  lua/ui/lobby/lobby-ping.lua
  projectiles/AANTorpedoClusterSplit01/AANTorpedoClusterSplit01_script.lua
  projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
  projectiles/AIFMissileSerpentine02/AIFMissileSerpentine02_script.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
  projectiles/AIFMissileTactical01/AIFMissileTactical01_Script.lua
  projectiles/AIFMissileTactical02/AIFMissileTactical02_Script.lua
  projectiles/CANKrilTorpedo01/CANKrilTorpedo01_script.lua
  projectiles/CANTorpedoMeson01/CANTorpedoMeson01_script.lua
  projectiles/CIFMissileTactical01/CIFMissileTactical01_Script.lua
  projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua
  projectiles/CIFMissileTactical03/CIFMissileTactical03_Script.lua
  projectiles/SANHeavyCavitationTorpedo01/SANHeavyCavitationTorpedo01_script.lua
  projectiles/SANHeavyCavitationTorpedo02/SANHeavyCavitationTorpedo02_script.lua
  projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_Script.lua
  projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_Script.lua
  projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_Script.lua
  projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_Script.lua
  projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_script.lua
  projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_script.lua
  projectiles/TANAnglerTorpedo01/TANAnglerTorpedo01_script.lua
  projectiles/TIFMissileCruise01/TIFMissileCruise01_Script.lua
  projectiles/TIFMissileCruise02/TIFMissileCruise02_script.lua
  projectiles/TIFMissileCruise03/TIFMissileCruise03_Script.lua
  projectiles/TIFMissileCruise04/TIFMissileCruise04_Script.lua
  projectiles/TIFMissileCruise05/TIFMissileCruise05_Script.lua
  projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_Script.lua
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua
  projectiles/TorpedoShipTerran02/TorpedoShipTerran02_script.lua
Labels: area: sim

#4686 Re-implement veterancy system
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/defaultcomponents.lua
  lua/sim/Unit.lua
  lua/system/blueprints-units.lua
  lua/ui/controls/worldview.lua
  lua/ui/game/unitview.lua
Labels: area: sim, area: ui

#4699 Fix units jumping and rotating as they are being built
  lua/defaultunits.lua
  lua/seraphimunits.lua
Labels: area: graphics

#4703 Fix issues with veterancy
  lua/SimUtils.lua
  lua/defaultcomponents.lua
  lua/sim/Entity.lua
  lua/sim/Unit.lua
  lua/system/config.lua
  lua/ui/game/unitview.lua
Labels: type: bug, area: sim, area: ui

#4711 Take into account omni intel
  lua/system/blueprints-units.lua
Labels: area: sim

#4712 Fix issues with re-implementation of veterancy
  lua/defaultcomponents.lua
  lua/defaultunits.lua
  lua/sim/Unit.lua
Labels: area: sim

#4714 Fix terrain alignment issues
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/defaultunits.lua
  units/UAB5101/UAB5101_unit.bp
  units/UEB5101/UEB5101_unit.bp
  units/URB5101/URB5101_unit.bp
  units/XSB5101/XSB5101_unit.bp
Labels: area: sim

#4715 Fix units showing initially hidden bones
  lua/defaultunits.lua
Labels: area: sim

#4725 Add missing max reverse speed field to allow reverse movement
  units/UAL0208/UAL0208_unit.bp
  units/UAL0309/UAL0309_unit.bp
Labels: type: bug, area: sim

#4726 Fix lingering decals and add toggle for force alt move
  lua/options/options.lua
  lua/ui/controls/worldview.lua
  lua/ui/game/gamemain.lua
  lua/ui/game/selection.lua
  lua/ui/help/tooltips.lua
Labels: type: bug, area: ui

#4732 Add an army check to new guard behavior
  lua/ui/game/commandmode.lua
Labels: type: bug

#4731 Updated the Enlarged AutoBalance
  textures/ui/AEON/BUTTON/autobalance/_btn_dis.dds
  textures/ui/AEON/BUTTON/autobalance/_btn_down.dds
  textures/ui/AEON/BUTTON/autobalance/_btn_over.dds
  textures/ui/AEON/BUTTON/autobalance/_btn_up.dds
  textures/ui/CYBRAN/BUTTON/autobalance/_btn_dis.dds
  textures/ui/CYBRAN/BUTTON/autobalance/_btn_down.dds
  textures/ui/CYBRAN/BUTTON/autobalance/_btn_over.dds
  textures/ui/CYBRAN/BUTTON/autobalance/_btn_up.dds
  textures/ui/SERAPHIM/BUTTON/autobalance/_btn_dis.dds
  textures/ui/SERAPHIM/BUTTON/autobalance/_btn_down.dds
  textures/ui/SERAPHIM/BUTTON/autobalance/_btn_over.dds
  textures/ui/SERAPHIM/BUTTON/autobalance/_btn_up.dds
  textures/ui/common/BUTTON/autobalance/_btn_dis.dds
  textures/ui/common/BUTTON/autobalance/_btn_down.dds
  textures/ui/common/BUTTON/autobalance/_btn_over.dds
  textures/ui/common/BUTTON/autobalance/_btn_up.dds
Labels: area: ui, area: lobby

#4734 Remove temporary files surrounding the Ythotha walk animation
  units/XSL0401/XSL0401_lod0.scm
  units/XSL0401/xsl0401_walkanim_02.sca
Labels: type: bug, area: graphics

#4676 Add more PBR techniques
  effects/mesh.fx
  textures/environment/DefaultEnvCube_mirrored.dds
  units/UAL0202/UAL0202_personalshield_mesh.bp
  units/UAL0301/UAL0301_personalshield_mesh.bp
Labels: area: pbr

#4736 Changelog 3752
  changelog-dev.md
  changelog.md
  lua/ui/game/reclaim.lua
  lua/ui/lobby/autolobby.lua
  lua/ui/lobby/changelogData.lua
  lua/version.lua
  mod_info.lua
  scripts/release-faf-develop.sh
Labels: type: bug

#4740 Fix reclaim values of wrecks
  lua/sim/Prop.lua
Labels: type: bug

#4739 Give the Aloha missile its vulnerability back
  projectiles/TIFMissileCruise01/TIFMissileCruise01_Script.lua
Labels: type: bug

#4741 Fix build preview location of ringing underwater extractors
  lua/SimCallbacks.lua
Labels: type: bug

#4745 Adjust network parameters in an attempt to reduce lag
  lua/ui/game/gamemain.lua
Labels: type: enhancement
