Repository FAForever/fa, pull requests merged in 2023-04, with the labels that each got.

#4853 Annotate and refactor the builder manager of AIs
  lua/aibrains/base-ai.lua
  lua/editor/UnitCountBuildConditions.lua
  lua/sim/Builder.lua
  lua/sim/BuilderManager.lua
  lua/sim/EngineerManager.lua
  lua/sim/FactoryBuilderManager.lua
  lua/sim/PlatoonFormManager.lua
  lua/sim/StrategyManager.lua
  lua/system/GlobalBuilderTemplate.lua
Labels: area: sim, area: AI

#4832 AI Reclaim Platoon leveraging ReclaimGrid
  engine/Sim/CPlatoon.lua
  lua/AI/AIBuilders/AIEconomicBuilders.lua
  lua/AI/Grid.lua
  lua/AI/GridBrain.lua
  lua/AI/GridReclaim.lua
  lua/AI/PlatoonTemplates/EngineerPlatoonTemplates.lua
  lua/AI/aiutilities.lua
  lua/aibrain.lua
  lua/aibrains/base-ai.lua
  lua/editor/MiscBuildConditions.lua
  lua/platoon.lua
  lua/sim/EngineerManager.lua
Labels: area: sim, area: AI

#4861 Fix typo in brain class
  lua/aibrain.lua
Labels: type: bug

#4863 Fix state being unable to call the base class
  lua/sim/defaultweapons.lua
  lua/system/class.lua
Labels: type: bug

#4738 PBR tuning
  effects/mesh.fx
Labels: area: pbr

#4867 Recover missile progress when gifting a unit
  engine/Sim/Unit.lua
  lua/SimUtils.lua
  lua/sim/Unit.lua
Labels: type: bug

#4589 Initial draft for threat threshold for navigational mesh
  lua/SimCallbacks.lua
  lua/maui/slider.lua
  lua/shared/NavGenerator.lua
  lua/sim/NavDebug.lua
  lua/sim/NavGenerator.lua
  lua/sim/NavUtils.lua
  lua/ui/game/NavGenerator.lua
Labels: area: nav-mesh

#4876 Add path visualisation for navigational mesh
  lua/SimCallbacks.lua
  lua/sim/NavDebug.lua
  lua/sim/NavUtils.lua
  lua/ui/game/NavGenerator.lua
Labels: area: sim, area: ui, area: AI, area: nav-mesh

#4881 Cast shadows on all props
  effects/mesh.fx
Labels: area: graphics

#4870 Tweak PBR shader to be darker in the shadows
  effects/mesh.fx
Labels: area: pbr

#4885 build sort priority of crab eggs
  units/DRLK005/DRLK005_unit.bp
  units/XRL0003/XRL0003_unit.bp
  units/XRL0004/XRL0004_unit.bp
  units/XRL0005/XRL0005_unit.bp
Labels: area: ui, area: unit-blueprint

#4888 Fix - AI pgen reclaim builders to ignore hydros
  lua/AI/AIBuilders/AIEconomicBuilders.lua
Labels: area: sim, area: AI
