Repository FAForever/fa, pull requests merged in 2023-10, with the labels that each got.

#5491 Tune Cybran albedo
  effects/mesh.fx
Labels: area: graphics, area: pbr

#5490 Add missing emission on maps without water
  effects/mesh.fx
Labels: area: graphics, area: pbr

#5489 Remove global state surrounding roll off for units
  lua/DefaultUnits/Factory.lua
Labels: area: code style, area: sim

#5493 Fix look of cybran units on medium fidelity
  effects/mesh.fx
Labels: area: graphics

#5494 Fix small details related to the mobile factory
  lua/DefaultUnits/ExternalFactory.lua
  lua/defaultcomponents.lua
Labels: type: bug, feature: mobile factories

#5495 No longer force the fire state of mobile units to ground attack
  lua/DefaultUnits/Mobile.lua
Labels: type: bug, area: sim

#5498 Tweak trajectory of the tactical missiles
  lua/DefaultUnits/Air.lua
  lua/sim/components-projectile/TacticalMissileComponent.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_proj.bp
  projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_Script.lua
  projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_Script.lua
  projectiles/TIFMissileCruise04/TIFMissileCruise04_Script.lua
  units/XAS0306/XAS0306_unit.bp
  units/XSS0202/XSS0202_unit.bp
  units/XSS0303/XSS0303_unit.bp
Labels: feature: tactical missiles

#5501 Add a bit of a fudge factor to the arc of tactical missiles
  lua/sim/components-projectile/SemiBallisticComponent.lua
  lua/sim/components-projectile/TacticalMissileComponent.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
  projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_Script.lua
  projectiles/TIFMissileCruise04/TIFMissileCruise04_Script.lua
Labels: feature: tactical missiles

#5504 Introduce a generic on-air-collision-kill category
  lua/DefaultUnits/Air.lua
  projectiles/AIFQuantumWarhead01/AIFQuantumWarhead01_proj.bp
  projectiles/AIFQuantumWarhead03/AIFQuantumWarhead03_proj.bp
  projectiles/AIMSaintAntiNuke01/AIMSaintAntiNuke01_proj.bp
  projectiles/CAADissidentAntiNuke01/CAADissidentAntiNuke01_proj.bp
  projectiles/CIFEMPFluxWarhead01/CIFEMPFluxWarhead01_proj.bp
  projectiles/CIFEMPFluxWarhead04/CIFEMPFluxWarhead04_proj.bp
  projectiles/CIFProtonBomb01/CIFProtonBomb01_proj.bp
  projectiles/SIFExperimentalStrategicMissile01/SIFExperimentalStrategicMissile01_proj.bp
  projectiles/SIFHuAntiNuke01/SIFHuAntiNuke01_proj.bp
  projectiles/SIFInainoStrategicMissile01/SIFInainoStrategicMissile01_proj.bp
  projectiles/SIFInainoStrategicMissile02/SIFInainoStrategicMissile02_proj.bp
  projectiles/TIFMissileNuke01/TIFMissileNuke01_proj.bp
  projectiles/TIFMissileNuke02/TIFMissileNuke02_proj.bp
  projectiles/TIFSmallYieldNuclearBomb01/TIFSmallYieldNuclearBomb01_proj.bp
  projectiles/TIMMissileIntercerptor01/TIMMissileIntercerptor01_proj.bp
  units/XES0307/XES0307_unit.bp
  units/XSB0103/XSB0103_lod1.scm
  units/XSB0103/XSB0103_unit.bp
  units/XSS0201/XSS0201_unit.bp
Labels: area: sim

#5505 Allow projectiles of strategic bombers to ignore ASF
  engine/Core/Blueprints/UnitBlueprint.lua
  engine/Core/Blueprints/WeaponBlueprint.lua
  lua/DefaultUnits/Air.lua
  lua/shield.lua
  lua/sim/Unit.lua
  lua/system/blueprints-projectiles.lua
  lua/system/blueprints-units.lua
  projectiles/AANDepthCharge01/AANDepthCharge01_proj.bp
  projectiles/AANDepthCharge02/AANDepthCharge02_proj.bp
  projectiles/AANDepthCharge03/AANDepthCharge03_proj.bp
  projectiles/AIFBombQuark01/AIFBombQuark01_proj.bp
  projectiles/CIFProtonBomb01/CIFProtonBomb01_proj.bp
  projectiles/SANHeavyCavitationTorpedo01/SANHeavyCavitationTorpedo01_proj.bp
  projectiles/SBOZhanaseeBomb01/SBOZhanaseeBomb01_proj.bp
  projectiles/TIFSmallYieldNuclearBomb01/TIFSmallYieldNuclearBomb01_proj.bp
Labels: area: sim

#5506 Fix not capturing the right click when exiting hot build
  lua/keymap/hotbuild.lua
  lua/ui/controls/worldview.lua
Labels: area: ui

#5503 Fix issues surrounding the Ahwassa
  effects/emitters/contrail_delayed_mist_01_emit.bp
  effects/emitters/contrail_delayed_mist_02_emit.bp
  lua/sim/Unit.lua
  units/XSA0402/XSA0402_lod1.scm
  units/XSA0402/XSA0402_unit.bp
Labels: area: graphics

#5492 Clarify what the pathing matrices are checking for
  lua/sim/NavGenerator.lua
Labels: area: nav-mesh

#5497 Carriers with external factories can auto deploy constructed units
  lua/system/blueprints-units.lua
  lua/ui/game/orders.lua
  lua/ui/help/tooltips.lua
  textures/ui/common/game/orders/ring-yellow_mod.dds
  units/UAA0310/UAA0310_script.lua
  units/UAS0303/UAS0303_script.lua
  units/UES0401/UES0401_script.lua
  units/URS0303/URS0303_script.lua
  units/XSS0303/XSS0303_script.lua
Labels: feature: mobile factories

#5511 Fix a bug where the map is (partially) turned flat
  lua/sim/DefaultUnits/StructureUnit.lua
Labels: type: bug

#5509 AI - Update factory upgrade and t3 mex upgrade limits
  lua/AI/AIBuilders/AIEconomyUpgradeBuilders.lua
Labels: area: AI

#5512 Re-introduce mobile factory to CZAR
  units/UAA0310/UAA0310_script.lua
  units/UAA0310/UAA0310_unit.bp
  units/UAS0303/UAS0303_script.lua
  units/UES0401/UES0401_script.lua
  units/URS0303/URS0303_script.lua
  units/XSS0303/XSS0303_script.lua
Labels: feature: mobile factories

#5513 Separate blueprint fields for an external factory
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/defaultcomponents.lua
  lua/system/blueprints-units.lua
  lua/ui/lobby/lobby.lua
  units/UAA0310/UAA0310_script.lua
  units/UAA0310/UAA0310_unit.bp
  units/UAS0303/UAS0303_unit.bp
  units/UAS0401/UAS0401_unit.bp
  units/UEL0401/UEL0401_unit.bp
  units/UES0401/UES0401_unit.bp
  units/URS0303/URS0303_unit.bp
  units/XSS0303/XSS0303_unit.bp
Labels: feature: mobile factories

#5488 Try to preserve the original name field of a marker
  lua/aibrains/adaptive-ai.lua
  lua/sim/MarkerUtilities.lua
  lua/sim/MarkerUtilities/NavalAreas.lua
  lua/sim/ScenarioUtilities.lua
Labels: area: AI

#5500 Fix tac/strat launcher unit descriptions.
  loc/US/strings_db.lua
Labels: area: ui

#5514 Introduce a wall overspill mechanic
  lua/armordefinition.lua
  lua/sim/DefaultUnits/StructureUnit.lua
  lua/sim/DefaultUnits/WallStructureUnit.lua
  units/UAB5101/UAB5101_unit.bp
  units/UEB5101/UEB5101_unit.bp
  units/URB5101/URB5101_unit.bp
  units/XSB5101/XSB5101_unit.bp
Labels: area: balance

#5508 AI simple factory behavior
  engine/Sim/CAiBrain.lua
  lua/aibrains/components/economy.lua
  lua/aibrains/conditions/EconomyConditions.lua
  lua/aibrains/conditions/EngineerManagerConditions.lua
  lua/aibrains/conditions/FactoryManagerConditions.lua
  lua/aibrains/conditions/GenericConditions.lua
  lua/aibrains/conditions/StructureManagerConditions.lua
  lua/aibrains/conditions/factory-manager-conditions.lua
  lua/aibrains/easy-ai.lua
  lua/aibrains/managers/base-manager.lua
  lua/aibrains/managers/builder-manager.lua
  lua/aibrains/managers/engineer-manager.lua
  lua/aibrains/managers/factory-manager.lua
  lua/aibrains/managers/structure-manager.lua
  lua/aibrains/platoons/platoon-base.lua
  lua/aibrains/platoons/platoon-simple-factory.lua
  lua/aibrains/templates/base/easy-main.lua
  lua/aibrains/templates/builder-groups/Factories/Air/EasyAirFactoryBuilderGroups.lua
  lua/aibrains/templates/builder-groups/Factories/Land/EasyLandFactoryBuilderGroups.lua
  lua/aibrains/templates/builder-groups/Factories/Naval/EasyNavalFactoryBuilderGroups.lua
  lua/aibrains/templates/builder-groups/builder-group-template.lua
  lua/aibrains/templates/builders/Factories/Air/EasyAirFactoryBuilders.lua
  lua/aibrains/templates/builders/Factories/Land/EasyLandFactoryBuilders.lua
  lua/aibrains/templates/builders/Factories/Naval/EasyNavalFactoryBuilders.lua
  lua/aibrains/templates/builders/Factories/Shared/EasySharedFactoryBuilders.lua
  lua/aibrains/templates/builders/builder-template.lua
  lua/aibrains/templates/builders/builder.lua
  lua/platoon.lua
  lua/sim/Unit.lua
Labels: area: AI

#5520 projectiles/components structure
  lua/sim/DefaultProjectiles.lua
  lua/sim/projectiles/DebrisProjectile.lua
  lua/sim/projectiles/EmitterProjectile.lua
  lua/sim/projectiles/MultiBeamProjectile.lua
  lua/sim/projectiles/MultiCompositeEmitterProjectile.lua
  lua/sim/projectiles/MultiPolyTrailProjectile.lua
  lua/sim/projectiles/NukeProjectile.lua
  lua/sim/projectiles/NullProjectile.lua
  lua/sim/projectiles/OnWaterEntryEmitterProjectile.lua
  lua/sim/projectiles/OverchargeProjectile.lua
  lua/sim/projectiles/SingleBeamProjectile.lua
  lua/sim/projectiles/SingleCompositeEmitterProjectile.lua
  lua/sim/projectiles/SinglePolyTrailProjectile.lua
  lua/sim/projectiles/components/SemiBallisticComponent.lua
  lua/sim/projectiles/components/TacticalMissileComponent.lua
Labels: area: code style

#5518 Unlocking projectile defending weaponry
  effects/emitters/seraphim_lancer_missile_hit_02_none_emit.bp
  effects/emitters/seraphim_lancer_missile_hit_03_none_emit.bp
  engine/Core/Blueprints/WeaponBlueprint.lua
  lua/EffectTemplates.lua
  lua/defaultantiprojectile.lua
  lua/seraphimprojectiles.lua
  lua/sim/defaultweapons.lua
  projectiles/AIMAntiMissile01/AIMAntiMissile01_proj.bp
  units/UAS0103/UAS0103_unit.bp
  units/UAS0201/UAS0201_unit.bp
  units/UAS0202/UAS0202_unit.bp
  units/UAS0302/UAS0302_unit.bp
  units/UAS0303/UAS0303_unit.bp
  units/UAS0305/UAS0305_unit.bp
  units/UAS0401/UAS0401_unit.bp
  units/UEB4201/UEB4201_unit.bp
  units/UES0201/UES0201_unit.bp
  units/UES0202/UES0202_unit.bp
  units/UES0302/UES0302_unit.bp
  units/URB4201/URB4201_unit.bp
  units/URS0201/URS0201_unit.bp
  units/URS0202/URS0202_unit.bp
  units/URS0302/URS0302_unit.bp
  units/URS0303/URS0303_unit.bp
  units/XAS0204/XAS0204_unit.bp
  units/XAS0306/XAS0306_unit.bp
  units/XES0102/XES0102_unit.bp
  units/XES0307/XES0307_unit.bp
  units/XRL0305/XRL0305_unit.bp
  units/XRL0403/XRL0403_unit.bp
  units/XRS0204/XRS0204_unit.bp
  units/XRS0205/XRS0205_unit.bp
  units/XSB2205/XSB2205_unit.bp
  units/XSB4201/XSB4201_unit.bp
  units/XSS0201/XSS0201_unit.bp
  units/XSS0203/XSS0203_unit.bp
  units/XSS0302/XSS0302_unit.bp
  units/XSS0303/XSS0303_unit.bp
  units/XSS0304/XSS0304_unit.bp
Labels: area: balance, feature: tactical missiles, feature: anti projectile weaponry

#5525 Processing UEF tactical missiles
  lua/EffectTemplates.lua
  lua/aeonprojectiles.lua
  lua/defaultantiprojectile.lua
  lua/seraphimprojectiles.lua
  lua/sim/defaultweapons.lua
  lua/simInit.lua
  lua/terranprojectiles.lua
  projectiles/AIMAntiMissile01/AIMAntiMissile01_script.lua
  projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_proj.bp
  projectiles/TIFMissileCruise01/TIFMissileCruise01_Script.lua
  projectiles/TIFMissileCruise01/TIFMissileCruise01_proj.bp
  projectiles/TIFMissileCruise02/TIFMissileCruise02_proj.bp
  projectiles/TIFMissileCruise02/TIFMissileCruise02_script.lua
  projectiles/TIFMissileCruise03/TIFMissileCruise03_Script.lua
  projectiles/TIFMissileCruise03/TIFMissileCruise03_proj.bp
  projectiles/TIFMissileCruise04/TIFMissileCruise04_Script.lua
  projectiles/TIFMissileCruise04/TIFMissileCruise04_proj.bp
  projectiles/TIFMissileCruise05/TIFMissileCruise05_Script.lua
  projectiles/TIFMissileCruise05/TIFMissileCruise05_proj.bp
  projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_Script.lua
  projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_proj.bp
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_proj.bp
  units/UAB4201/UAB4201_unit.bp
  units/UEB4201/UEB4201_unit.bp
  units/UEL0001/UEL0001_unit.bp
  units/UEL0111/UEL0111_unit.bp
  units/UES0202/UES0202_unit.bp
  units/UES0304/UES0304_unit.bp
  units/URB4201/URB4201_unit.bp
  units/URS0202/URS0202_unit.bp
  units/URS0302/URS0302_unit.bp
  units/URS0303/URS0303_unit.bp
  units/XEL0306/XEL0306_unit.bp
Labels: area: balance, area: graphics, feature: tactical missiles

#5528 Fix various mistakes in behavior and reload time of TMDs
  lua/sim/defaultweapons.lua
  units/UAB4201/UAB4201_unit.bp
  units/UAS0201/UAS0201_unit.bp
  units/UAS0202/UAS0202_unit.bp
  units/UAS0302/UAS0302_unit.bp
  units/UAS0303/UAS0303_unit.bp
  units/UEB4201/UEB4201_unit.bp
  units/UES0202/UES0202_unit.bp
  units/UES0302/UES0302_unit.bp
  units/URB4201/URB4201_unit.bp
  units/URS0202/URS0202_unit.bp
  units/URS0302/URS0302_unit.bp
  units/URS0303/URS0303_unit.bp
  units/XES0307/XES0307_unit.bp
  units/XSB2205/XSB2205_unit.bp
  units/XSB4201/XSB4201_unit.bp
  units/XSS0202/XSS0202_unit.bp
  units/XSS0302/XSS0302_unit.bp
  units/XSS0303/XSS0303_unit.bp
Labels: area: balance, feature: tactical missiles

#5530 Process Cybran missiles in great detail
  lua/cybranprojectiles.lua
  lua/sim/defaultweapons.lua
  lua/sim/projectiles/components/SemiBallisticComponent.lua
  lua/sim/projectiles/components/SplitComponent.lua
  lua/sim/projectiles/components/TacticalMissileComponent.lua
  projectiles/CIFMissileTactical01/CIFMissileTactical01_Script.lua
  projectiles/CIFMissileTactical01/CIFMissileTactical01_proj.bp
  projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua
  projectiles/CIFMissileTactical02/CIFMissileTactical02_proj.bp
  projectiles/CIFMissileTactical03/CIFMissileTactical03_Script.lua
  projectiles/CIFMissileTactical03/CIFMissileTactical03_proj.bp
  projectiles/CIFMissileTacticalSplit01/CIFMissileTacticalSplit01_Script.lua
  projectiles/CIFMissileTacticalSplit01/CIFMissileTacticalSplit01_proj.bp
  units/URL0111/URL0111_unit.bp
Labels: area: balance, area: graphics

#5535 Process Aeon tactical missiles in great detail
  lua/aeonprojectiles.lua
  lua/cybranprojectiles.lua
  lua/seraphimprojectiles.lua
  lua/sim/projectiles/components/DebrisComponent.lua
  lua/sim/projectiles/components/TacticalMissileComponent.lua
  lua/terranprojectiles.lua
  projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_proj.bp
  projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
  projectiles/AIFMissileSerpentine02/AIFMissileSerpentine02_proj.bp
  projectiles/AIFMissileSerpentine02/AIFMissileSerpentine02_script.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_proj.bp
  projectiles/AIFMissileTactical01/AIFMissileTactical01_Script.lua
  projectiles/AIFMissileTactical01/AIFMissileTactical01_proj.bp
  projectiles/AIFMissileTactical02/AIFMissileTactical02_Script.lua
  projectiles/AIFMissileTactical02/AIFMissileTactical02_proj.bp
  projectiles/CIFMissileTacticalSplit01/CIFMissileTacticalSplit01_Script.lua
  units/UAL0111/UAL0111_unit.bp
  units/XAS0306/XAS0306_unit.bp
Labels: area: graphics, feature: tactical missiles

#5536 Add more diverse debris to tactical missiles
  effects/Entities/TacticalDebris01/TacticalDebris01_proj.bp
  effects/Entities/TacticalDebris01/TacticalDebris01_script.lua
  effects/Entities/TacticalDebris02/TacticalDebris02_proj.bp
  effects/Entities/TacticalDebris02/TacticalDebris02_script.lua
  effects/Entities/TacticalDebris03/TacticalDebris03_proj.bp
  effects/Entities/TacticalDebris03/TacticalDebris03_script.lua
  effects/emitters/tactical_debris_distortion_01_emit.bp
  effects/emitters/tactical_debris_fire_01_emit.bp
  effects/emitters/tactical_debris_smoke_01_emit.bp
  effects/emitters/tactical_debris_smoke_02_emit.bp
  effects/emitters/tactical_debris_smoke_03_emit.bp
  effects/emitters/tactical_debris_smoke_04_emit.bp
  effects/emitters/tactical_debris_trail_01_emit.bp
  lua/EffectTemplates.lua
  lua/aeonprojectiles.lua
  lua/cybranprojectiles.lua
  lua/terranprojectiles.lua
Labels: area: graphics, feature: tactical missiles

#5522 Make menu popout-speed faster
  lua/ui/game/tabs.lua
Labels: area: ui

#5523 Mute scoreboard background ambient if music is off
  lua/ui/dialogs/score.lua
Labels: ui: scoreboard

#5538 Display Sera Sniper/Loyalist secondary ranges
  units/URL0303/URL0303_unit.bp
  units/XSL0305/XSL0305_unit.bp
Labels: area: sim

#5524 Scoreboard graph optimization and cleanup
  lua/ui/dialogs/hotstats.lua
Labels: area: ui, ui: scoreboard

#5541 Make it easier to start building extractors while zoomed out
  lua/ui/game/hotkeys/context-based-templates.lua
Labels: area: ui, feature: context-based templates

#5543 Context based templates that trigger on the command mode
  lua/ui/game/hotkeys/context-based-templates-data.lua
  lua/ui/game/hotkeys/context-based-templates-data/AirDefenseLand.lua
  lua/ui/game/hotkeys/context-based-templates-data/AirDefenseWater.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendAirGrid.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendMassStorages.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendMassStoragesAndFabricators.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToArtillery.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToEnergyStorage.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToRadar.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToTML.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendWallsToPointDefense.lua
  lua/ui/game/hotkeys/context-based-templates-data/CapExtractorWithFabs.lua
  lua/ui/game/hotkeys/context-based-templates-data/CapExtractorWithStorages.lua
  lua/ui/game/hotkeys/context-based-templates-data/CapRadarWithPower.lua
  lua/ui/game/hotkeys/context-based-templates-data/CapT2ArtilleryWithPower.lua
  lua/ui/game/hotkeys/context-based-templates-data/CapT3ArtilleryWithPower.lua
  lua/ui/game/hotkeys/context-based-templates-data/CapT3FabricatorWithStorages.lua
  lua/ui/game/hotkeys/context-based-templates-data/PointDefense.lua
  lua/ui/game/hotkeys/context-based-templates-data/T1Extractor.lua
  lua/ui/game/hotkeys/context-based-templates-data/T1Hydrocarbon.lua
  lua/ui/game/hotkeys/context-based-templates-data/T2ExtractorWithStorages.lua
  lua/ui/game/hotkeys/context-based-templates-data/T3ExtractorWithStorages.lua
  lua/ui/game/hotkeys/context-based-templates-data/T3ExtractorWithStoragesAndFabs.lua
  lua/ui/game/hotkeys/context-based-templates-data/TorpedoDefense.lua
  lua/ui/game/hotkeys/context-based-templates.lua
Labels: feature: context-based templates

#5540 Assist to copy the command queue of an engineer
  lua/options/options.lua
  lua/ui/game/commandmode.lua
  lua/ui/help/tooltips.lua
Labels: feature: distribute orders

#5545 Process the balance changes to walls
  units/UAB5101/UAB5101_unit.bp
  units/UEB5101/UEB5101_unit.bp
  units/URB5101/URB5101_unit.bp
  units/XSB5101/XSB5101_unit.bp
Labels: area: balance

#5546 Process build time changes for stationary tech 3 anti air
  units/UAB2304/UAB2304_unit.bp
  units/UEB2304/UEB2304_unit.bp
  units/URB2304/URB2304_unit.bp
  units/XSB2304/XSB2304_unit.bp
Labels: area: balance

#5548 Reduce built time of beetles and adjust their explosion behavior
  units/XRL0302/XRL0302_unit.bp
Labels: area: balance

#5547 Buff Brick
  units/XRL0305/XRL0305_unit.bp
Labels: area: balance

#5549 Increase break off distance for Solace for better bombing runs
  units/XAA0306/XAA0306_unit.bp
Labels: type: bug, area: sim

#5550 Increase collision box to prevent beams missing Lobo and Blaze
  units/UEL0103/UEL0103_unit.bp
  units/XAL0203/XAL0203_unit.bp
Labels: type: bug

#5553 Fixed Transports in the game to not ignore sera's ACU regen field
  units/XSL0001/XSL0001_unit.bp
Labels: type: bug

#5555 Fix flak acting like a gattling cannon
  lua/sim/defaultweapons.lua
  units/XEL0306/XEL0306_unit.bp
Labels: type: bug

#5556 Apply `NOSPLASHDAMAGE` category to sera MML missiles.
  projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_proj.bp
Labels: feature: tactical missiles

#5554 Fix: Enable the Sparky to be buffed by the RegenAura-upgrades
  units/XSL0001/XSL0001_unit.bp
Labels: type: bug

#5438 Cycle templates hotbuild
  loc/US/strings_db.lua
  lua/keymap/hotbuild.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/unitkeygroups.lua
Labels: area: ui, feature: hotkeys

#5567 Add a guard before applying the reclaim order
  lua/sim/commands/shared.lua
Labels: type: bug, feature: distribute orders

#5568 Reduce memory footprint of navigational mesh by ~ 10%
  lua/sim/NavGenerator.lua
Labels: area: nav-mesh

#5564 Fix aeon bomber getting stuck flipping
  units/UAA0103/UAA0103_unit.bp
Labels: type: bug

#5570 Process balance changes on tech 3 mobile artillery
  units/UEL0304/UEL0304_unit.bp
  units/URL0304/URL0304_unit.bp
  units/XSL0304/XSL0304_unit.bp
Labels: area: balance

#5572 Reduce the range and increase firing randomness of tech 2 artillery
  units/UAB2303/UAB2303_unit.bp
  units/UEB2303/UEB2303_unit.bp
  units/URB2303/URB2303_unit.bp
  units/XSB2303/XSB2303_unit.bp
Labels: area: balance

#5569 Fix mercy fishtailing
  units/DAA0206/DAA0206_unit.bp
Labels: area: graphics

#5565 Adjust t1 bomb max speeds.
  projectiles/AIFBombGraviton01/AIFBombGraviton01_proj.bp
  projectiles/CIFNeutronClusterBomb01/CIFNeutronClusterBomb01_proj.bp
  projectiles/SBOOtheTacticalBomb01/SBOOtheTacticalBomb01_proj.bp
  projectiles/TIFNapalmCarpetBomb01/TIFNapalmCarpetBomb01_proj.bp
Labels: area: balance

#5559 Add localization for mobile factory select and auto-deploy
  loc/US/strings_db.lua
  lua/ui/help/tooltips.lua
Labels: area: ui, feature: mobile factories

#5534 AI - state machine fixes and guardrails
  lua/AI/Transportutilities.lua
  lua/AI/aiutilities.lua
  lua/aibrains/platoons/platoon-adaptive-attack.lua
  lua/aibrains/platoons/platoon-adaptive-guard.lua
  lua/aibrains/platoons/platoon-adaptive-raid.lua
  lua/aibrains/platoons/platoon-adaptive-reclaim.lua
  lua/aibrains/platoons/platoon-adaptive-returntobase.lua
  lua/aibrains/platoons/platoon-base.lua
  lua/aibrains/platoons/platoon-simple-raid.lua
  lua/platoon.lua
Labels: area: AI

#5574 Nav mesh/performance 01
  lua/aibrains/platoons/platoon-adaptive-guard.lua
  lua/aibrains/platoons/platoon-adaptive-reclaim.lua
  lua/aibrains/platoons/platoon-adaptive-returntobase.lua
  lua/aibrains/platoons/platoon-simple-raid.lua
  lua/sim/NavDatastructures.lua
  lua/sim/NavGenerator.lua
  lua/sim/NavUtils.lua
  tests/test_NavDatastructures.lua
Labels: area: AI, area: nav-mesh

#5533 Terrain advancements
  effects/terrain.fx
  effects/water2.fx
Labels: area: graphics

#5577 Simplify the death thread of walls
  lua/defaultexplosions.lua
  lua/sim/units/WallStructureUnit.lua
Labels: area: sim, area: graphics

#5562 Sniper mode description mentions slowdown.
  loc/US/strings_db.lua
Labels: area: ui

#5581 Adds stat toggle infrastructure and switches AutoDeploy to use it
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/SimCallbacks.lua
  lua/defaultcomponents.lua
  lua/system/blueprints-units.lua
  lua/ui/game/orders.lua
  units/UAA0310/UAA0310_script.lua
  units/UAS0303/UAS0303_script.lua
  units/UES0401/UES0401_script.lua
  units/URS0303/URS0303_script.lua
  units/XSS0303/XSS0303_script.lua
Labels: feature: mobile factories

#5575 Fix Various Weapon Tooltips and Display Weapon Costs
  loc/RU/strings_db.lua
  loc/TW/strings_db.lua
  loc/US/strings_db.lua
  lua/ui/game/unitviewDetail.lua
  units/DRLK001/DRLK001_unit.bp
  units/UAL0001/UAL0001_unit.bp
  units/UEL0001/UEL0001_unit.bp
  units/URL0001/URL0001_unit.bp
  units/URL0104/URL0104_unit.bp
  units/URS0202/URS0202_unit.bp
  units/XAS0306/XAS0306_unit.bp
  units/XSL0001/XSL0001_unit.bp
  units/XSL0301/XSL0301_unit.bp
  units/XSL0305/XSL0305_unit.bp
  units/XSS0201/XSS0201_unit.bp
Labels: area: ui

#5585 Add stat changes to SACU Enhancement Descriptions
  loc/US/strings_db.lua
  lua/ui/help/unitdescription.lua
Labels: area: ui

#5582 Close NukePing cheat vector
  lua/sim/defaultweapons.lua
  lua/ui/game/nukelaunchping.lua
Labels: type: bug

#5579 Introduce a coarse navigational grid
  engine/Sim/CPlatoon.lua
  lua/aibrains/platoons/platoon-adaptive-attack.lua
  lua/aibrains/platoons/platoon-adaptive-guard.lua
  lua/aibrains/platoons/platoon-adaptive-raid.lua
  lua/aibrains/platoons/platoon-adaptive-returntobase.lua
  lua/aibrains/platoons/platoon-base.lua
  lua/aibrains/platoons/platoon-simple-raid.lua
  lua/sim/NavDatastructures.lua
  lua/sim/NavDebug.lua
  lua/sim/NavDebug/DirectionTo.lua
  lua/sim/NavGenerator.lua
  lua/sim/NavUtils.lua
  tests/test_NavDatastructures.lua
Labels: area: AI, area: nav-mesh

#5608 Fix the easy AI not working
  lua/aibrains/index.lua
Labels: type: bug, area: AI

#5607 Fix `GetPositionsInRadius` to use the new format
  lua/aibrains/adaptive-ai.lua
  lua/aibrains/medium-ai.lua
  lua/aibrains/rush-ai.lua
  lua/aibrains/tech-ai.lua
  lua/aibrains/turtle-ai.lua
  lua/sim/NavUtils.lua
Labels: area: nav-mesh

#5609 Fix a bug with zappers intersecting the wrong missile
  lua/sim/Projectile.lua
Labels: type: bug, feature: tactical missiles

#5610 Fix a bug where factory modules would bug out campaign objectives
  lua/defaultcomponents.lua
  lua/sim/Projectile.lua
  lua/sim/units/ExternalFactoryUnit.lua
  lua/sim/units/components/TransportUnitComponent.lua
Labels: type: bug, feature: mobile factories

#5611 Fix a common edge case that prevents the Microwave Laser of firing
  units/URL0001/URL0001_unit.bp
Labels: type: bug, feature: target bones

#5604 Shield disruptor
  units/DAL0310/DAL0310_unit.bp
Labels: area: balance

#5603 Rebalance Cruisers
  units/UAS0202/UAS0202_unit.bp
  units/UES0202/UES0202_unit.bp
  units/URS0202/URS0202_unit.bp
  units/XSS0202/XSS0202_unit.bp
Labels: area: balance
