Repository FAForever/fa, pull requests merged in 2023-08, with the labels that each got.

#5302 Alternative to the capping / ringing behavior
  engine/User.lua
  lua/keymap/keyactions.lua
  lua/keymap/misckeyactions.lua
  lua/keymap/selectedinfo.lua
  lua/ui/game/commandmeshes.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/commands/generated-templates-data.lua
  lua/ui/game/commands/generated-templates.lua
  lua/ui/game/commandwaypoint.lua
  lua/ui/game/gamemain.lua
Labels: area: ui

#5305 Fix a typo
  lua/ui/game/commands/generated-templates-data.lua
Labels: area: ui

#5306 Process feedback on alternative capping feature
  lua/ui/game/commandmode.lua
  lua/ui/game/commands/generated-templates-data.lua
  lua/ui/game/commands/generated-templates.lua
Labels: area: ui

#5308 Allow for predefined templates that trigger on empty space
  lua/ui/game/commands/generated-templates-data.lua
  lua/ui/game/commands/generated-templates.lua
Labels: area: ui

#5309 Rename the feature and add support for custom factions
  lua/keymap/keyactions.lua
  lua/ui/game/commands/context-based-templates-data.lua
  lua/ui/game/commands/context-based-templates.lua
Labels: area: ui

#5310 Finalize new capping behavior
  lua/SimCallbacks.lua
  lua/keymap/defaultKeyMap.lua
  lua/keymap/keyactions.lua
  lua/keymap/keycategories.lua
  lua/keymap/keydescriptions.lua
  lua/options/options.lua
  lua/ui/controls/worldview.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/commands/context-based-templates-data.lua
  lua/ui/game/commands/context-based-templates.lua
Labels: area: ui

#5314 Remove a lingering LOG statement
  lua/ui/game/commands/context-based-templates.lua
Labels: area: ui

#5316 Process feedback on the capping feature
  lua/keymap/keyactions.lua
  lua/ui/controls/worldview.lua
  lua/ui/game/commands/context-based-templates.lua
Labels: area: ui

#5317 Re-introduces limited version of old capping behavior
  lua/SimCallbacks.lua
  lua/options/options.lua
  lua/sim/commands/ring-extractor.lua
  lua/sim/defaultweapons.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/commands/context-based-templates-data.lua
  lua/ui/game/commands/context-based-templates.lua
Labels: area: ui

#5319 Improve full redundancy of orders
  lua/SimCallbacks.lua
Labels: area: ui

#5321 Toggle reclaim effects when units are (un)paused
  lua/keymap/keydescriptions.lua
  lua/sim/Unit.lua
Labels: area: sim

#5320 Remove the old spread attack functionality
  engine/Sim.lua
  lua/SimCallbacks.lua
  lua/keymap/alternativeKeyMap.lua
  lua/keymap/defaultKeyMap.lua
  lua/keymap/hotbuildKeyMap.lua
  lua/keymap/keyactions.lua
  lua/spreadattack.lua
  lua/system/repr.lua
  lua/ui/game/commandmode.lua
Labels: area: ui

#5322 Move the distribute orders feature to a separate file
  lua/SimCallbacks.lua
  lua/sim/commands/distribute.lua
Labels: area: code style, area: sim

#5323 Add licenses to the top of the file
  lua/sim/commands/distribute.lua
  lua/sim/commands/ring-extractor.lua
Labels: area: code style

#5166 Reintroduce upper albedo scale as shader switch
  effects/terrain.fx
Labels: area: graphics

#5093 Add optimized PBR terrain shader - Terrain101
  effects/terrain.fx
  lua/ui/game/gamemain.lua
Labels: area: graphics

#5230 Map shaders
  effects/terrain.fx
Labels: area: graphics, sync-to-discord

#5332 Copy the command queue of the unit below the mouse
  lua/SimCallbacks.lua
  lua/keymap/keyactions.lua
  lua/keymap/misckeyactions.lua
  lua/sim/commands/orders-copy.lua
  lua/sim/commands/orders-distribute.lua
  lua/sim/commands/orders-shared.lua
Labels: area: sim, area: ui

#5334 Give more control over what orders end up being distributed
  lua/SimCallbacks.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/misckeyactions.lua
  lua/sim/commands/orders-distribute.lua
Labels: area: sim, area: ui

#5333 Add tread crushing for Fatboy
  lua/defaultcomponents.lua
  units/UEL0401/UEL0401_unit.bp
Labels: area: sim

#5261 Update for Campaign AI Brain, and ScenarioPlatoonAI
  lua/ScenarioPlatoonAI.lua
  lua/aibrains/campaign-ai.lua
Labels: area: AI

#5337 Add unit icons for mobile factories
  lua/keymap/misckeyactions.lua
  lua/ui/game/construction.lua
  lua/ui/uiutil.lua
  textures/ui/common/icons/units/UAS0303EF_icon.dds
  textures/ui/common/icons/units/UAS0401EF_icon.dds
  textures/ui/common/icons/units/UEL0401EF_icon.dds
  textures/ui/common/icons/units/UES0401EF_icon.dds
  textures/ui/common/icons/units/URS0303EF_icon.dds
  textures/ui/common/icons/units/XSS0303EF_icon.dds
Labels: area: sim

#5338 Remove mobile factory aspects of Megalith and CZAR
  units/UAA0310/UAA0310_unit.bp
  units/XRL0403/XRL0403_unit.bp
Labels: area: sim

#5339 Reduce build rates of mobile factories to match regular factories
  units/UAS0303/UAS0303_unit.bp
  units/UEL0401/UEL0401_unit.bp
  units/UES0401/UES0401_unit.bp
  units/URS0303/URS0303_unit.bp
  units/XSS0303/XSS0303_unit.bp
Labels: area: balance

#5340 Final tweaks to the terrain shader
  effects/terrain.fx
Labels: area: graphics

#5342 Add mobile factory component to the Tempest
  effects/emitters/watersplash_s.bp
  effects/emitters/watertower_m.bp
  effects/emitters/watertower_s.bp
  lua/defaultcomponents.lua
  lua/defaultunits.lua
  units/UAS0303/UAS0303_script.lua
  units/UAS0401/UAS0401_script.lua
  units/UAS0401/UAS0401_unit.bp
  units/UEL0401/UEL0401_script.lua
  units/UES0401/UES0401_script.lua
  units/URS0303/URS0303_script.lua
  units/XSS0303/XSS0303_script.lua
Labels: area: balance

#5343 Document terrain shaders and streamline how they interpret properties
  effects/terrain.fx
Labels: area: code style, area: graphics

#5353 Fix a bug that can cause the class loader to get into an infinite loop
  effects/Entities/DebrisBoneAttachChassis01/DebrisBoneAttachChassis01_script.lua
  effects/Entities/DebrisBoneAttachHigh01/DebrisBoneAttachHigh01_script.lua
  effects/Entities/DebrisBoneAttachLow01/DebrisBoneAttachLow01_script.lua
  effects/Entities/DestructionFire01/DestructionFire01_script.lua
  effects/Entities/DestructionFirePlume01/DestructionFirePlume01_script.lua
  effects/Entities/DestructionSpark01/DestructionSpark01_script.lua
  effects/Entities/EffectThrustTransport01/EffectThrustTransport01_script.lua
  effects/Entities/EffectThrustTransport02/EffectThrustTransport02_script.lua
  effects/Entities/SBOZhanaseeBombEffect01/SBOZhanaseeBombEffect01_script.lua
  effects/Entities/SBOZhanaseeBombEffect02/SBOZhanaseeBombEffect02_script.lua
  effects/Entities/UEFNukeFlavorPlume01/UEFNukeFlavorPlume01_script.lua
  lua/EffectTemplates.lua
  lua/aeonprojectiles.lua
  lua/aeonweapons.lua
  lua/cybranprojectiles.lua
  lua/defaultcollisionbeams.lua
  lua/kirvesbeams.lua
  lua/kirvesweapons.lua
  lua/seraphimprojectiles.lua
  lua/sim/CollisionBeam.lua
  lua/sim/DefaultProjectiles.lua
  lua/sim/Projectile.lua
  lua/sim/defaultweapons.lua
  lua/terranprojectiles.lua
  lua/terranweapons.lua
  projectiles/CIFEMPFluxWarhead01/CIFEMPFluxWarhead01_script.lua
  projectiles/CIFEMPFluxWarhead04/CIFEMPFluxWarhead04_script.lua
  projectiles/SIFInainoStrategicMissile01/SIFInainoStrategicMissile01_script.lua
  projectiles/SIFInainoStrategicMissile02/SIFInainoStrategicMissile02_script.lua
  projectiles/ShellTankTerran01/ShellTankTerran01_script.lua
  projectiles/TAARailgun01/TAARailgun01_script.lua
  projectiles/TAARailgun02/TAARailgun02_script.lua
  projectiles/TAARailgun03/TAARailgun03_script.lua
  projectiles/TestProjectile01/TestProjectile01_script.lua
  units/DSLK004/DSLK004_script.lua
  units/OPE3001/OPE3001_script.lua
  units/XRO4001/XRO4001_script.lua
Labels: type: bug

#5354 Re-introduce fields that mods may be missing
  lua/EffectTemplates.lua
Labels: type: bug, area: sim

#5355 Change external factory categories to fix AI
  units/ZXA0002/ZXA0002_unit.bp
Labels: area: sim, status: in-progress, area: AI

#5357 Fix the roll off order for the Tempest
  engine/Sim/Unit.lua
  units/UAS0401/UAS0401_script.lua
Labels: type: bug

#5358 Finalize new orders and add user feedback
  lua/SimCallbacks.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/misckeyactions.lua
  lua/sim/commands/orders-copy.lua
  lua/sim/commands/orders-distribute.lua
  lua/sim/commands/orders-load-in-transport.lua
Labels: area: sim, area: ui

#5360 Speed up death animations of structures
  lua/defaultexplosions.lua
  units/XSB1103/XSB1103_unit.bp
  units/XSB1202/XSB1202_unit.bp
  units/XSB1302/XSB1302_script.lua
  units/XSB1302/XSB1302_unit.bp
Labels: area: sim

#5362 Introduce URLs to the FAForever wiki to explain hotkeys
  lua/keymap/keyactions.lua
  lua/keymap/keymapper.lua
  lua/ui/dialogs/keybindings.lua
Labels: area: ui

#5361 Rename files and simplify descriptions
  lua/SimCallbacks.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/sim/commands/copy-queue.lua
  lua/sim/commands/distribute-queue.lua
  lua/sim/commands/load-in-transport.lua
  lua/sim/commands/shared.lua
Labels: area: code style, area: ui

#5364 Fix small bugs with the new queue-based features
  lua/sim/commands/shared.lua
  lua/ui/game/commands/context-based-templates-data.lua
Labels: area: sim, area: ui

#5366 Re-order files to stop polluting generic files
  lua/keymap/debugKeyActions.lua
  lua/keymap/keyactions.lua
  lua/keymap/keymapper.lua
  lua/keymap/misckeyactions.lua
  lua/options/options.lua
  lua/sim/commands/copy-queue.lua
  lua/sim/commands/distribute-queue.lua
  lua/sim/commands/load-in-transport.lua
  lua/sim/commands/ring-extractor.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/hotkeys/context-based-templates-data.lua
  lua/ui/game/hotkeys/context-based-templates.lua
  lua/ui/game/hotkeys/copy-queue.lua
  lua/ui/game/hotkeys/distribute-queue.lua
  lua/ui/game/hotkeys/filter-engineers.lua
  lua/ui/game/hotkeys/load-in-transport.lua
  lua/ui/game/hotkeys/ring-extractor.lua
Labels: area: code style, area: ui

#5223 DroneOrders
  units/UEA0001/UEA0001_unit.bp
  units/UEA0003/UEA0003_unit.bp
Labels: area: balance

#5348 Jester: Fix, so it no longer misses low height units
  units/XRA0105/XRA0105_unit.bp
Labels: area: balance

#5259 Tighter formation for the Shard
  units/UAS0102/UAS0102_unit.bp
Labels: area: balance, sync-to-discord

#5367 Add drone build effect for Megalith
  lua/EffectUtilitiesOpti.lua
  lua/cybranunits.lua
  lua/ui/game/commandmode.lua
  units/XRL0403/XRL0403_script.lua
  units/XRL0403/XRL0403_unit.bp
Labels: area: sim, area: graphics

#5295 Stinger and C14 Star Lifter: Fix, so they no longer miss low height units
  projectiles/TDFRiot01/TDFRiot01_proj.bp
  units/UEA0203/UEA0203_unit.bp
Labels: area: balance

#5240 Implement the assembly patch of 4zot on SetStat
  engine/User/UserUnit.lua
  lua/defaultcomponents.lua
  lua/sim/Projectile.lua
  lua/sim/Unit.lua
Labels: type: enhancement, area: code style, area: requires engine patch

#5371 Fix light particles through fog and destroying invulnerable props
  lua/defaultunits.lua
Labels: type: bug, area: sim

#5374 Restore control groups of upgrading structures
  lua/ui/game/selection.lua
Labels: type: bug, area: ui

#5345 Downgrade ps_3_0 shader
  effects/terrain.fx
Labels: area: code style, area: graphics

#5368 Revert the wave texture lod bias
  effects/water2.fx
Labels: area: graphics

#5372 Improve water landing capabilities and graphics of the UEF
  effects/emitters/tt_water_landing01_emit.bp
  effects/emitters/tt_water_takeoff_01_emit.bp
  effects/emitters/water_idle_ripples_gunship_01.bp
  effects/emitters/water_idle_ripples_gunship_02.bp
  engine/Core/Categories.lua
  lua/TerrainTypes.lua
  lua/defaultunits.lua
  lua/sim/Unit.lua
  lua/system/blueprints-units.lua
  textures/particles/water_ripple_alpha_alt_01.dds
  units/UAA0203/UAA0203_unit.bp
  units/UEA0001/UEA0001_unit.bp
  units/UEA0003/UEA0003_unit.bp
  units/UEA0104/UEA0104_unit.bp
  units/UEA0107/UEA0107_unit.bp
  units/UEA0203/UEA0203_unit.bp
  units/UEA0305/UEA0305_unit.bp
  units/URA0203/URA0203_unit.bp
  units/XAA0305/XAA0305_unit.bp
  units/XEA0306/XEA0306_unit.bp
Labels: area: sim, area: graphics

#5041 Remove the dive button while diving
  lua/defaultunits.lua
Labels: type: bug, area: ui

#5375 Always add the destination to the path
  lua/sim/NavUtils.lua
Labels: area: AI, area: nav-mesh

#5286 search and tooltip improvements in Create Unit Dialog
  lua/ui/dialogs/createunit.logic.lua
  lua/ui/dialogs/createunit.lua
Labels: type: enhancement, status: need review, area: ui
