Repository FAForever/fa, pull requests merged in 2023-01, with the labels that each got.

#4510 Allow users to define batching threshold
  lua/options/options.lua
  lua/sim/Prop.lua
  lua/ui/game/reclaim.lua
Labels: area: ui

#4536 Reduce memory footprint of navigational mesh
  lua/sim/NavDebug.lua
  lua/sim/NavGenerator.lua
  lua/sim/NavUtils.lua
Labels: area: AI, area: nav-mesh

#4479 Aeon land factory HQ/Support visual reworks
  units/UAB0101/UAB0101_ASupport.sca
  units/UAB0101/UAB0101_Albedo.dds
  units/UAB0101/UAB0101_NormalsTS.dds
  units/UAB0101/UAB0101_SpecTeam.dds
  units/UAB0101/UAB0101_lod0.scm
  units/UAB0101/UAB0101_lod1_Albedo.dds
  units/UAB0101/UAB0101_lod1_SpecTeam.dds
  units/UAB0101/UAB0101_lod1_normalsTS.dds
  units/UAB0101/UAB0101_unit.bp
  units/UAB0201/UAB0201_LOD0.scm
  units/UAB0201/UAB0201_lod0.scm
  units/UAB0201/UAB0201_unit.bp
  units/UAB0301/UAB0301_LOD0.scm
  units/UAB0301/UAB0301_lod0.scm
  units/UAB0301/UAB0301_unit.bp
  units/ZAB9501/ZAB9501_Albedo.dds
  units/ZAB9501/ZAB9501_Aopen.sca
  units/ZAB9501/ZAB9501_LOD0.scm
  units/ZAB9501/ZAB9501_NormalsTS.dds
  units/ZAB9501/ZAB9501_SpecTeam.dds
  units/ZAB9501/ZAB9501_lod0.scm
  units/ZAB9501/ZAB9501_lod1_Albedo.dds
  units/ZAB9501/ZAB9501_lod1_SpecTeam.dds
  units/ZAB9501/ZAB9501_lod1_normalsTS.dds
  units/ZAB9501/ZAB9501_unit.bp
  units/ZAB9601/ZAB9601_Albedo.dds
  units/ZAB9601/ZAB9601_LOD0.scm
  units/ZAB9601/ZAB9601_NormalsTS.dds
  units/ZAB9601/ZAB9601_SpecTeam.dds
  units/ZAB9601/ZAB9601_lod0.scm
  units/ZAB9601/ZAB9601_lod1_Albedo.dds
  units/ZAB9601/ZAB9601_lod1_SpecTeam.dds
  units/ZAB9601/ZAB9601_lod1_normalsTS.dds
  units/ZAB9601/ZAB9601_unit.bp
Labels: area: pbr

#4555 Improve the retrieval of the (nearest) valid leaf of a position
  lua/shared/NavGenerator.lua
  lua/sim/NavDebug.lua
  lua/sim/NavGenerator.lua
  lua/sim/NavUtils.lua
Labels: area: nav-mesh

#4556 Completely cull amphibious and hover grids on map with no water
  lua/sim/NavGenerator.lua
Labels: area: nav-mesh

#4559 Fix an edge case at the boundary between two areas
  lua/sim/NavUtils.lua
Labels: area: nav-mesh

#4560 Introduces custom classes to initiate the data structures
  lua/sim/NavGenerator.lua
  run_lua_syntax_checker.sh
Labels: area: nav-mesh

#4561 Fix minor issues and introduce access to root
  lua/sim/NavGenerator.lua
Labels: area: nav-mesh

#4580 Fix bad reference
  lua/aeonunits.lua
Labels: type: bug, area: sim

#4581 Temporarily disable always computing the allocated size of navigational mesh
  lua/sim/NavGenerator.lua
Labels: type: bug, area: nav-mesh

#4584 Integrate wonky structures
  lua/EffectUtilitiesAeon.lua
  lua/defaultunits.lua
  lua/sim/TerrainUtils.lua
  units/UAA0104/UAA0104_unit.bp
  units/UAB1102/UAB1102_unit.bp
  units/UAB1103/UAB1103_unit.bp
  units/UAB1202/UAB1202_unit.bp
  units/UAB1302/UAB1302_unit.bp
  units/UEB1102/UEB1102_unit.bp
  units/UEB1103/UEB1103_unit.bp
  units/UEB1202/UEB1202_unit.bp
  units/UEB1302/UEB1302_unit.bp
  units/URB1102/URB1102_unit.bp
  units/URB1103/URB1103_unit.bp
  units/URB1202/URB1202_unit.bp
  units/URB1302/URB1302_unit.bp
  units/XAA0306/XAA0306_unit.bp
  units/XSB0102/XSB0102_unit.bp
  units/XSB0202/XSB0202_unit.bp
  units/XSB0302/XSB0302_unit.bp
  units/XSB1102/XSB1102_unit.bp
  units/XSB1103/XSB1103_unit.bp
  units/XSB1202/XSB1202_unit.bp
  units/XSB1302/XSB1302_unit.bp
  units/ZSB9502/ZSB9502_unit.bp
  units/ZSB9602/ZSB9602_unit.bp
Labels: area: sim

#4593 Lightning tank targeting fix & other minor bp fix
  units/DSLK004/DSLK004_unit.bp
  units/UAL0101/UAL0101_unit.bp
Labels: area: balance

#4521 aeon navy factories
  units/UAB0103/UAB0103_Albedo.dds
  units/UAB0103/UAB0103_Aopen.sca
  units/UAB0103/UAB0103_Aopen_sup.sca
  units/UAB0103/UAB0103_SpecTeam.dds
  units/UAB0103/UAB0103_lod0.scm
  units/UAB0103/UAB0103_lod1_Albedo.dds
  units/UAB0103/UAB0103_lod1_SpecTeam.dds
  units/UAB0103/UAB0103_lod1_normalsTS.dds
  units/UAB0103/UAB0103_normalsTS.dds
  units/UAB0103/UAB0103_unit.bp
  units/UAB0201/UAB0201_unit.bp
  units/UAB0203/UAB0203_LOD0.scm
  units/UAB0203/UAB0203_lod0.scm
  units/UAB0203/UAB0203_lod1.scm
  units/UAB0203/UAB0203_unit.bp
  units/UAB0203/uab0203_aopen.sca
  units/UAB0303/UAB0303_LOD0.scm
  units/UAB0303/UAB0303_lod0.scm
  units/UAB0303/UAB0303_lod1.scm
  units/UAB0303/UAB0303_unit.bp
  units/ZAB9503/ZAB9503_Aopen.sca
  units/ZAB9503/ZAB9503_SpecTeam.dds
  units/ZAB9503/ZAB9503_lod0.scm
  units/ZAB9503/ZAB9503_lod1.scm
  units/ZAB9503/ZAB9503_lod1_Albedo.dds
  units/ZAB9503/ZAB9503_lod1_SpecTeam.dds
  units/ZAB9503/ZAB9503_lod1_normalsTS.dds
  units/ZAB9503/ZAB9503_normalsTS.dds
  units/ZAB9503/ZAB9503_unit.bp
  units/ZAB9603/ZAB9603_Albedo.dds
  units/ZAB9603/ZAB9603_SpecTeam.dds
  units/ZAB9603/ZAB9603_lod0.scm
  units/ZAB9603/ZAB9603_lod1.scm
  units/ZAB9603/ZAB9603_lod1_Albedo.dds
  units/ZAB9603/ZAB9603_lod1_SpecTeam.dds
  units/ZAB9603/ZAB9603_lod1_normalsTS.dds
  units/ZAB9603/ZAB9603_normalsTS.dds
  units/ZAB9603/ZAB9603_unit.bp
Labels: area: pbr

#4596 Reduce unique table instances that hold the same data
  effects/Entities/DebrisBoneAttachChassis01/DebrisBoneAttachChassis01_script.lua
  effects/Entities/DebrisBoneAttachHigh01/DebrisBoneAttachHigh01_script.lua
  effects/Entities/DebrisBoneAttachLow01/DebrisBoneAttachLow01_script.lua
  effects/Entities/DestructionFire01/DestructionFire01_script.lua
  effects/Entities/DestructionFirePlume01/DestructionFirePlume01_script.lua
  effects/Entities/DestructionSpark01/DestructionSpark01_script.lua
  effects/Entities/EffectThrustTransport01/EffectThrustTransport01_script.lua
  effects/Entities/EffectThrustTransport02/EffectThrustTransport02_script.lua
  effects/Entities/SBOZhanaseeBombEffect01/SBOZhanaseeBombEffect01_script.lua
  effects/Entities/SBOZhanaseeBombEffect02/SBOZhanaseeBombEffect02_script.lua
  effects/Entities/UEFNukeFlavorPlume01/UEFNukeFlavorPlume01_script.lua
  lua/EffectTemplates.lua
  lua/aeonprojectiles.lua
  lua/aeonweapons.lua
  lua/cybranprojectiles.lua
  lua/defaultcollisionbeams.lua
  lua/defaultunits.lua
  lua/kirvesbeams.lua
  lua/kirvesweapons.lua
  lua/seraphimprojectiles.lua
  lua/sim/CollisionBeam.lua
  lua/sim/DefaultProjectiles.lua
  lua/sim/Projectile.lua
  lua/sim/defaultweapons.lua
  lua/terranprojectiles.lua
  lua/terranweapons.lua
  projectiles/CIFEMPFluxWarhead01/CIFEMPFluxWarhead01_script.lua
  projectiles/CIFEMPFluxWarhead04/CIFEMPFluxWarhead04_script.lua
  projectiles/SIFInainoStrategicMissile01/SIFInainoStrategicMissile01_script.lua
  projectiles/SIFInainoStrategicMissile02/SIFInainoStrategicMissile02_script.lua
  projectiles/ShellTankTerran01/ShellTankTerran01_script.lua
  projectiles/TAARailgun01/TAARailgun01_script.lua
  projectiles/TAARailgun02/TAARailgun02_script.lua
  projectiles/TAARailgun03/TAARailgun03_script.lua
  projectiles/TestProjectile01/TestProjectile01_script.lua
  units/DSLK004/DSLK004_script.lua
  units/OPE3001/OPE3001_script.lua
  units/XRO4001/XRO4001_script.lua
Labels: area: sim

#4597 Fix initial regen value not showing
  lua/sim/Unit.lua
Labels: type: bug

#4598 Remove various logging that should not have been merged
  lua/shield.lua
  lua/sim/Projectile.lua
  lua/sim/Unit.lua
  lua/ui/lobby/lobby.lua
Labels: type: bug

#4599 Fix order of execution of overcharge projectiles
  projectiles/ADFOverCharge01/ADFOverCharge01_script.lua
  projectiles/CDFCannonMolecularOvercharge01/CDFCannonMolecularOvercharge01_script.lua
  projectiles/SDFChronatronCannon02/SDFChronatronCannon02_script.lua
  projectiles/SDFLightChronatronCannon02/SDFLightChronatronCannon02_script.lua
  projectiles/TDFOverCharge01/TDFOverCharge01_script.lua
Labels: type: bug

#4600 Fix class typo
  units/XRL0302/XRL0302_Script.lua
Labels: type: bug, area: sim

#4605 Fix various issues found during playtesting
  lua/defaultunits.lua
  lua/sim/Unit.lua
  lua/terranunits.lua
  projectiles/CIFEMPFluxWarhead02/CIFEMPFluxWarhead02_script.lua
  units/UAL0401/UAL0401_Script.lua
  units/UEB4203/UEB4203_script.lua
  units/UEL0208/UEL0208_script.lua
Labels: type: bug

#4586 Integrate 'NoShake' UI mod
  lua/options/options.lua
  lua/ui/help/tooltips.lua
Labels: area: ui

#4606 Fix issue with full share
  lua/SimUtils.lua
Labels: type: bug

#4607 Do not adjust orientations of structures on water
  lua/defaultunits.lua
Labels: type: bug

#4577 Introduce assist to upgrade and assist to unpause commands
  engine/User/UserUnit.lua
  lua/options/options.lua
  lua/ui/game/commandmode.lua
  lua/ui/help/tooltips.lua
Labels: area: ui

#4608 Fix issues with torpedoes
  lua/aeonprojectiles.lua
  lua/cybranprojectiles.lua
  lua/terranprojectiles.lua
  projectiles/AANDepthCharge02/AANDepthCharge02_script.lua
  projectiles/CANKrilTorpedo01/CANKrilTorpedo01_script.lua
  projectiles/CANTorpedoNanite03/CANTorpedoNanite03_script.lua
  projectiles/TANAnglerTorpedo04/TANAnglerTorpedo04_script.lua
  projectiles/TANAnglerTorpedo05/TANAnglerTorpedo05_script.lua
  projectiles/TANAnglerTorpedo06/TANAnglerTorpedo06_script.lua
Labels: type: bug

#4587 Introduce selection subgroups functionality
  lua/keymap/keyactions.lua
  lua/keymap/keycategories.lua
  lua/keymap/keydescriptions.lua
  lua/ui/game/selection.lua
Labels: area: ui

#4544 Revert damage change of T1 artilleries
  units/UEL0103/UEL0103_unit.bp
  units/XSL0103/XSL0103_unit.bp
Labels: type: bug, area: balance

#4543 Reduce the death damage of air T4s
  units/UAA0310/UAA0310_unit.bp
  units/URA0401/URA0401_unit.bp
  units/XSA0402/XSA0402_unit.bp
Labels: area: balance

#4562 Adjust titans and loyalists
  units/UEL0303/UEL0303_unit.bp
  units/URL0303/URL0303_Script.lua
  units/URL0303/URL0303_unit.bp
Labels: area: balance

#4564 Normalize Economy stats of T2 PDs
  units/UAB2301/UAB2301_unit.bp
  units/UEB2301/UEB2301_unit.bp
  units/URB2301/URB2301_unit.bp
  units/XSB2301/XSB2301_unit.bp
Labels: area: balance

#4567 Adjust engineers
  units/UAL0208/UAL0208_unit.bp
  units/UAL0309/UAL0309_unit.bp
  units/UEL0208/UEL0208_unit.bp
  units/UEL0309/UEL0309_unit.bp
  units/URL0208/URL0208_unit.bp
  units/URL0309/URL0309_unit.bp
  units/XSL0208/XSL0208_unit.bp
  units/XSL0309/XSL0309_unit.bp
Labels: area: balance

#4568 Adjust T2 static Artillery
  units/UAB2303/UAB2303_unit.bp
  units/UEB2303/UEB2303_unit.bp
  units/URB2303/URB2303_unit.bp
  units/XSB2303/XSB2303_unit.bp
Labels: area: balance

#4542 Soul Ripper mini-rework
  units/URA0401/URA0401_unit.bp
Labels: area: balance

#4545 Bulwark mini-rework
  units/XES0205/XES0205_unit.bp
Labels: area: balance

#4565 Naval adjustments
  units/UAS0103/UAS0103_unit.bp
  units/UAS0201/UAS0201_unit.bp
  units/UAS0401/UAS0401_unit.bp
  units/UES0302/UES0302_unit.bp
  units/URS0103/URS0103_unit.bp
  units/URS0201/URS0201_unit.bp
Labels: area: balance

#4566 T2 land Movement adjustment
  units/DEL0204/DEL0204_unit.bp
  units/DRL0204/DRL0204_unit.bp
  units/UAL0111/UAL0111_unit.bp
  units/UAL0202/UAL0202_unit.bp
  units/UAL0205/UAL0205_unit.bp
  units/UEL0111/UEL0111_unit.bp
  units/UEL0202/UEL0202_unit.bp
  units/UEL0205/UEL0205_unit.bp
  units/URL0111/URL0111_unit.bp
  units/URL0202/URL0202_unit.bp
  units/URL0205/URL0205_unit.bp
  units/XSL0111/XSL0111_unit.bp
  units/XSL0202/XSL0202_unit.bp
  units/XSL0205/XSL0205_unit.bp
Labels: area: balance

#4571 Adjust pathing parameters for engineers
  units/UAL0105/UAL0105_unit.bp
  units/UAL0208/UAL0208_unit.bp
  units/UAL0309/UAL0309_unit.bp
  units/UEL0105/UEL0105_unit.bp
  units/UEL0208/UEL0208_unit.bp
  units/UEL0309/UEL0309_unit.bp
  units/URL0105/URL0105_unit.bp
  units/URL0208/URL0208_unit.bp
  units/URL0309/URL0309_unit.bp
  units/XEL0209/XEL0209_unit.bp
  units/XSL0105/XSL0105_unit.bp
  units/XSL0208/XSL0208_unit.bp
  units/XSL0309/XSL0309_unit.bp
Labels: area: balance

#4611 Remove overwritten instances of `CreateProjectileForWeapon`
  lua/aeonweapons.lua
  lua/cybranweapons.lua
  lua/terranweapons.lua
  projectiles/ADFShieldDisruptor01/ADFShieldDisruptor01_script.lua
  projectiles/AIFFragmentationSensorShell01/AIFFragmentationSensorShell01_script.lua
  projectiles/AIFFragmentationSensorShell02/AIFFragmentationSensorShell02_script.lua
  projectiles/AIFMiasmaShell01/AIFMiasmaShell01_script.lua
  projectiles/CDFTracker01/CDFTracker01_script.lua
Labels: area: sim

#4615 Fix orientation of the mercury pool
  lua/EffectUtilitiesAeon.lua
  units/UAA0203/UAA0203_unit.bp
  units/UAA0204/UAA0204_unit.bp
  units/UAA0303/UAA0303_unit.bp
  units/UAA0304/UAA0304_unit.bp
  units/XAA0202/XAA0202_unit.bp
  units/XAA0305/XAA0305_unit.bp
  units/XAA0306/XAA0306_unit.bp
Labels: type: bug, area: sim

#4613 aeon support land factories lod1
  units/ZAB9501/ZAB9501_lod1.scm
  units/ZAB9601/ZAB9601_lod1.scm
Labels: type: bug

#4616 Fix Cybran Flak MS
  units/URL0205/URL0205_unit.bp
Labels: area: balance

#4617 Fix reset of construction menu when selecting a structure
  lua/ui/game/construction.lua
Labels: type: bug, area: ui

#4612 Fix hooking issues for mods
  lua/AI/AIBuilders/SorianStrategyBuilders.lua
  lua/AI/OpAI/BaseManager.lua
  lua/AI/aibuildstructures.lua
  lua/AI/aiutilities.lua
  lua/ScenarioPlatoonAI.lua
  lua/platoon.lua
Labels: type: bug

#4620 Always pause extractor when upgrading using `OnGuardUpgrade`
  lua/ui/game/commandmode.lua
Labels: area: ui

#4440 Adjust Nukes
  projectiles/AIFQuantumWarhead01/AIFQuantumWarhead01_proj.bp
  projectiles/AIFQuantumWarhead03/AIFQuantumWarhead03_proj.bp
  projectiles/CIFEMPFluxWarhead01/CIFEMPFluxWarhead01_proj.bp
  projectiles/CIFEMPFluxWarhead04/CIFEMPFluxWarhead04_proj.bp
  projectiles/SIFInainoStrategicMissile01/SIFInainoStrategicMissile01_proj.bp
  projectiles/TIFMissileNuke01/TIFMissileNuke01_proj.bp
  projectiles/TIFMissileNuke02/TIFMissileNuke02_proj.bp
  units/UAB2305/UAB2305_unit.bp
  units/UAS0304/UAS0304_unit.bp
  units/UEB2305/UEB2305_unit.bp
  units/UES0304/UES0304_unit.bp
  units/URB2305/URB2305_unit.bp
  units/URS0304/URS0304_unit.bp
  units/XSB2305/XSB2305_unit.bp
Labels: area: balance

#4618 Adjust elevation of strategic bombers to make them easier to hit
  units/UAA0304/UAA0304_unit.bp
  units/UEA0304/UEA0304_unit.bp
  units/URA0304/URA0304_unit.bp
  units/XSA0304/XSA0304_unit.bp
Labels: area: balance

#4441 T3 Arty Adjustment
  units/UAB2302/UAB2302_unit.bp
  units/UEB2302/UEB2302_unit.bp
  units/URB2302/URB2302_unit.bp
  units/XSB2302/XSB2302_unit.bp
Labels: area: balance

#4623 Fix HQ status after removing restrictions in campaign
  lua/ScenarioFramework.lua
  lua/aibrain.lua
Labels: type: bug

#4322 Changes some using files to prevent Intellisense popups
  lua/seraphimunits.lua
  units/DAA0206/DAA0206_script.lua
  units/DAL0310/DAL0310_Script.lua
  units/DALK003/DALK003_Script.lua
  units/DEL0204/DEL0204_Script.lua
  units/DELK002/DELK002_script.lua
  units/DRLK001/DRLK001_Script.lua
  units/DSLK004/DSLK004_script.lua
  units/UAL0001/UAL0001_script.lua
  units/UAL0301/UAL0301_script.lua
  units/UAL0401/UAL0401_Script.lua
  units/UEA0104/UEA0104_Script.lua
  units/UEL0001/UEL0001_script.lua
  units/UEL0301/UEL0301_script.lua
  units/URA0107/URA0107_Script.lua
  units/URA0401/URA0401_script.lua
  units/URB2302/URB2302_Script.lua
  units/URL0001/URL0001_script.lua
  units/URL0301/URL0301_script.lua
  units/XAB1401/XAB1401_script.lua
  units/XEB2306/XEB2306_Script.lua
  units/XRC2201/XRC2201_script.lua
  units/XRL0403/XRL0403_script.lua
  units/XSL0305/XSL0305_script.lua
  units/XSL0401/XSL0401_Script.lua
Labels: type: intellisense

#4631 Fix typo in type class
  projectiles/AIFMiasmaShell01/AIFMiasmaShell01_script.lua
Labels: type: bug, area: sim

#4626 Mass Storage able to be built around underwater mex
  lua/SimCallbacks.lua
  units/UAB1106/UAB1106_unit.bp
  units/UEB1106/UEB1106_unit.bp
  units/URB1106/URB1106_unit.bp
  units/XSB1106/XSB1106_unit.bp
Labels: area: balance, area: unit-blueprint

#4634 Properly apply charge animation of Emissary
  lua/aeonweapons.lua
Labels: area: sim, area: graphics

#4635 Fix direction of adjacency beams
  lua/EffectUtilities.lua
Labels: area: graphics

#4636 Orientate structures to match terrain when created
  lua/defaultunits.lua
Labels: type: bug, area: sim

#4645 Fix/sniper bot being immune to mml
  units/XSL0305/XSL0305_unit.bp
Labels: type: bug, area: sim

#4644 Adjust Hives and Kennels
  units/XEB0104/XEB0104_unit.bp
  units/XEB0204/XEB0204_unit.bp
  units/XRB0104/XRB0104_unit.bp
  units/XRB0204/XRB0204_unit.bp
  units/XRB0304/XRB0304_unit.bp
Labels: area: balance

#4640 Improve memory management of treads
  lua/AI/AIBuilders/AIAirAttackBuilders.lua
  lua/defaultcomponents.lua
  lua/defaultunits.lua
  lua/proptree.lua
  lua/sim/Unit.lua
  units/UEL0401/UEL0401_unit.bp
Labels: area: sim, area: graphics

#4658 Use a stack for `ToBytes`
  lua/sim/NavGenerator.lua
  lua/system/utils.lua
  units/XSL0401/XSL0401_lod0.scm
  units/XSL0401/xsl0401_walkanim_02.sca
Labels: area: nav-mesh

#4639 Dynamic adjacency direction
  lua/EffectUtilities.lua
Labels: area: graphics
