Repository FAForever/fa, pull requests merged in 2023-03, with the labels that each got.

#4756 Fix extractors not aligning to the terrain properly
  units/UAB1103/UAB1103_unit.bp
  units/UAB1202/UAB1202_unit.bp
  units/UAB1302/UAB1302_unit.bp
  units/UEB1103/UEB1103_unit.bp
  units/UEB1202/UEB1202_unit.bp
  units/UEB1302/UEB1302_unit.bp
  units/URB1103/URB1103_unit.bp
  units/URB1202/URB1202_unit.bp
  units/URB1302/URB1302_unit.bp
  units/XSB1103/XSB1103_unit.bp
  units/XSB1202/XSB1202_unit.bp
  units/XSB1302/XSB1302_unit.bp
Labels: type: bug, area: sim, area: graphics

#4743 Fix civilians not being revealed due to intel lagging behind
  lua/sim/ScenarioUtilities.lua
Labels: type: bug

#4752 Auto lobby icon fix for when select random
  textures/ui/random/BUTTON/autobalance/_btn_dis.dds
  textures/ui/random/BUTTON/autobalance/_btn_down.dds
  textures/ui/random/BUTTON/autobalance/_btn_over.dds
  textures/ui/random/BUTTON/autobalance/_btn_up.dds
Labels: area: ui, area: lobby

#4757 Fix hot build being reset upon a build order
  lua/ui/game/commandmode.lua
Labels: type: bug, area: ui

#4759 Prevent beam weapons from continuously restarting when ground firing
  lua/sim/defaultweapons.lua
Labels: type: bug, area: sim

#4761 Prevent culling of labels with resources
  lua/sim/NavGenerator.lua
Labels: type: bug, area: sim, area: nav-mesh

#4762 Introduce an upper limit in distance when searching for neighbors
  lua/sim/NavUtils.lua
  lua/ui/game/NavGenerator.lua
Labels: area: sim, area: nav-mesh

#4763 Change up the order back to the old situation
  lua/sim/Unit.lua
Labels: type: bug, area: sim

#4776 Fix navigational mesh being able to run multiple times
  lua/simInit.lua
Labels: area: nav-mesh

#4777 Fix props with no reclaim values
  lua/sim/Prop.lua
Labels: type: bug, area: sim

#4778 Fix tractor beams being able to make units invulnerable
  lua/aeonweapons.lua
Labels: type: bug, area: sim

#4768 Keep orientation of structure as assigned in the editor
  lua/defaultunits.lua
  lua/shared/quaternions.lua
Labels: type: bug, area: sim

#4780 Fix various issues with the navigational mesh
  lua/SimCallbacks.lua
  lua/defaultunits.lua
  lua/sim/NavDebug.lua
  lua/sim/NavGenerator.lua
  lua/simInit.lua
  lua/ui/game/NavGenerator.lua
Labels: type: bug, area: nav-mesh

#4782 Fix typo with attack move cursor
  lua/ui/game/objectives2.lua
  lua/ui/game/orders.lua
  lua/ui/game/pingGroup.lua
Labels: type: bug, area: ui

#4783 Update build mode
  lua/ui/game/buildmodedata.lua
Labels: area: ui

#4719 Fix weapon mode switching causing firing delay
  lua/sim/Unit.lua
  units/DRLK001/DRLK001_Script.lua
  units/DRLK001/DRLK001_unit.bp
  units/URL0104/URL0104_script.lua
  units/URL0104/URL0104_unit.bp
  units/URS0202/URS0202_script.lua
  units/URS0202/URS0202_unit.bp
Labels: type: bug, area: balance

#4701 Refactor TauntManager
  lua/TauntManager.lua
Labels: area: sim, area: coop

#4784 Fix transferred units receiving full vet
  lua/defaultcomponents.lua
Labels: type: bug, area: sim

#4786 Revert network changes
  changelog.md
  lua/ui/game/gamemain.lua
  lua/ui/lobby/changelogData.lua
  lua/version.lua
  mod_info.lua
Labels: area: sim, area: ui

#4805 Fix bug where orientations are applied multiple times
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/SimUtils.lua
Labels: type: bug, area: sim

#4800 Hide mass fabricator and recall panel as you switch to observer
  lua/UserSync.lua
  lua/ui/game/massfabs.lua
Labels: type: bug, area: ui

#4793 Do not disable tabs when you're in a replay
  lua/ui/game/tabs.lua
Labels: type: bug, area: ui

#4806 Fix lingering bitmap draggers on chat and console window
  lua/maui/window.lua
Labels: type: bug, area: ui

#4807 Add check whether platoon function is available
  lua/AI/OpAI/BaseManagerPlatoonThreads.lua
Labels: area: sim, area: coop

#4770 Cheatspawn menu overhaul
  lua/SimCallbacks.lua
  lua/maui/layouthelpers.lua
  lua/maui/window.lua
  lua/system/Blueprints.lua
  lua/ui/dialogs/createprop.lua
  lua/ui/dialogs/createunit.lua
  lua/ui/dialogs/createunitfilters.lua
  lua/ui/game/commandmode.lua
  meshes/game/nil_lod0.scm
  meshes/game/nil_mesh.bp
  textures/ui/common/dialogs/spawn_menu/slider-back_bmp.dds
Labels: area: ui

#4804 Fix cursor options not listening to preference file
  lua/options/options.lua
  lua/ui/game/casting/mouse.lua
  lua/ui/game/cursor/depth.lua
  lua/ui/game/cursor/hover.lua
  lua/ui/help/tooltips.lua
Labels: area: ui

#4809 Re-order the sync
  lua/UserSync.lua
Labels: area: ui

#4812 Fix overcharge always dealing 15K damage
  projectiles/ADFOverCharge01/ADFOverCharge01_script.lua
  projectiles/CDFCannonMolecularOvercharge01/CDFCannonMolecularOvercharge01_script.lua
  projectiles/SDFChronatronCannon02/SDFChronatronCannon02_script.lua
  projectiles/SDFLightChronatronCannon02/SDFLightChronatronCannon02_script.lua
  projectiles/TDFOverCharge01/TDFOverCharge01_script.lua
Labels: type: bug, area: sim

#4813 Fix options of mouse sharing while observing
  lua/ui/game/casting/mouse.lua
Labels: type: bug, area: ui

#4811 Initial setup for a reclaim tracking system for AIs
  lua/AI/Grid.lua
  lua/AI/GridReclaim.lua
  lua/aibrain.lua
  lua/sim/Prop.lua
  lua/simInit.lua
  lua/wreckage.lua
Labels: area: sim, area: AI

#4801 Refactor `statusbar.lua` to improve performance and readability
  lua/maui/statusbar.lua
Labels: area: ui

#4737 Add PBR shader for czar
  effects/mesh.fx
Labels: area: pbr

#4698 Fix recall wording and UI bugs
  loc/US/strings_db.lua
  lua/EffectUtilities.lua
  lua/ScenarioFramework.lua
  lua/aibrain.lua
  lua/maui/button.lua
  lua/sim/Recall.lua
  lua/sim/Unit.lua
  lua/ui/game/diplomacy.lua
  lua/ui/game/recall.lua
  lua/ui/help/tooltips.lua
  textures/ui/common/game/options-diplomacy-panel/panel-allies.png
  textures/ui/common/game/options-diplomacy-panel/panel-enemy.png
  textures/ui/common/game/options-diplomacy-panel/panel-recall.png
  textures/ui/common/game/recall-panel/icon-recall_bmp.png
  textures/ui/common/game/recall-panel/recall-accept.png
  textures/ui/common/game/recall-panel/recall-veto.png
  textures/ui/common/game/recall-panel/recall-vote.png
Labels: area: sim, area: ui

#4810 Refactoring LazyVars
  lua/lazyvar.lua
  lua/ui/game/worldview.lua
Labels: area: ui

#4824 Take into account teleport delays
  lua/sim/Unit.lua
Labels: type: bug, area: sim

#4826 Improve effects of debris
  effects/Entities/DEBRISMISC010/DebrisMisc010_proj.bp
  effects/Entities/DebrisBoneAttachChassis01/DebrisBoneAttachChassis01_proj.bp
  effects/Entities/DebrisBoneAttachHigh01/DebrisBoneAttachHigh01_proj.bp
  effects/Entities/DebrisBoneAttachLow01/DebrisBoneAttachLow01_proj.bp
  effects/Entities/DebrisMisc01/DebrisMisc01_proj.bp
  effects/Entities/DebrisMisc02/DebrisMisc02_proj.bp
  effects/Entities/DebrisMisc03/DebrisMisc03_proj.bp
  effects/Entities/DebrisMisc04/DebrisMisc04_proj.bp
  effects/Entities/DebrisMisc05/DebrisMisc05_proj.bp
  effects/Entities/DebrisMisc06/DebrisMisc06_proj.bp
  effects/Entities/DebrisMisc07/DebrisMisc07_proj.bp
  effects/Entities/DebrisMisc08/DebrisMisc08_proj.bp
  effects/Entities/DebrisMisc09/DebrisMisc09_proj.bp
  effects/emitters/destruction_explosion_debris_trail_01_emit.bp
  lua/EffectTemplates.lua
  lua/sim/DefaultProjectiles.lua
  lua/sim/Projectile.lua
Labels: area: graphics

#4831 Refactor Shield-Structure/Units to use ShieldEffectsComponent #4628
  units/UEB4301/UEB4301_script.lua
  units/URB4202/URB4202_script.lua
  units/URB4204/URB4204_script.lua
  units/URB4205/URB4205_script.lua
  units/URB4206/URB4206_script.lua
  units/URB4207/URB4207_script.lua
  units/XES0205/XES0205_script.lua
  units/XSB4202/XSB4202_script.lua
  units/XSB4301/XSB4301_script.lua
  units/XSL0307/XSL0307_script.lua
Labels: area: code style, area: sim, area: graphics

#4835 Reduce hash operations in the shield effects component
  lua/defaultcomponents.lua
Labels: area: code style, area: sim

#4825 add factory being built to forcepath limit condition.
  lua/editor/UnitCountBuildConditions.lua
Labels: area: sim, area: AI

#4828 Change default explosions
  effects/emitters/Medium_test_fire.bp
  effects/emitters/Small_test_fire.bp
  effects/emitters/large_test_fire.bp
  lua/EffectTemplates.lua
  textures/particles/fire_flame_05.dds
Labels: area: graphics

#4836 Add support for `Start Location` marker type
  lua/sim/MarkerUtilities.lua
Labels: area: sim, area: AI

#4796 Air Staging build time changes
  units/UAB5202/UAB5202_unit.bp
  units/UEB5202/UEB5202_unit.bp
  units/URB5202/URB5202_unit.bp
  units/XSB5202/XSB5202_unit.bp
Labels: area: balance

#4693 Initial setup with the barebone player brain
  loc/CN/strings_db.lua
  loc/CZ/strings_db.lua
  loc/DE/strings_db.lua
  loc/ES/strings_db.lua
  loc/FR/strings_db.lua
  loc/IT/strings_db.lua
  loc/PL/strings_db.lua
  loc/RU/strings_db.lua
  loc/TW/strings_db.lua
  loc/US/strings_db.lua
  lua/AI/AIBaseTemplates/SorianExpansionAirFull.lua
  lua/AI/AIBaseTemplates/SorianExpansionBalancedFull.lua
  lua/AI/AIBaseTemplates/SorianExpansionBalancedSmall.lua
  lua/AI/AIBaseTemplates/SorianExpansionTurtleFull.lua
  lua/AI/AIBaseTemplates/SorianExpansionWaterFull.lua
  lua/AI/AIBaseTemplates/SorianMainAir.lua
  lua/AI/AIBaseTemplates/SorianMainBalanced.lua
  lua/AI/AIBaseTemplates/SorianMainRush.lua
  lua/AI/AIBaseTemplates/SorianMainTurtle.lua
  lua/AI/AIBaseTemplates/SorianMainWater.lua
  lua/AI/AIBaseTemplates/SorianNavalExpansionLarge.lua
  lua/AI/AIBaseTemplates/SorianNavalExpansionSmall.lua
  lua/AI/AIBehaviors.lua
  lua/AI/AIBuilders/AIEconomicBuilders.lua
  lua/AI/AIBuilders/SorianAirAttackBuilders.lua
  lua/AI/AIBuilders/SorianArtilleryBuilders.lua
  lua/AI/AIBuilders/SorianDefenseBuilders.lua
  lua/AI/AIBuilders/SorianEconomicBuilders.lua
  lua/AI/AIBuilders/SorianEconomyUpgradeBuilders.lua
  lua/AI/AIBuilders/SorianExpansionBuilders.lua
  lua/AI/AIBuilders/SorianExperimentalBuilders.lua
  lua/AI/AIBuilders/SorianFactoryConstructionBuilders.lua
  lua/AI/AIBuilders/SorianIntelBuilders.lua
  lua/AI/AIBuilders/SorianLandAttackBuilders.lua
  lua/AI/AIBuilders/SorianNavalBuilders.lua
  lua/AI/AIBuilders/SorianSeaAttackBuilders.lua
  lua/AI/AIBuilders/SorianStrategyBuilders.lua
  lua/AI/AIBuilders/SorianStrategyPlatoonBuilders.lua
  lua/AI/CustomAIs_v2/SorianAI.lua
  lua/AI/PlatoonTemplates/AirPlatoonTemplatesSorian.lua
  lua/AI/PlatoonTemplates/EngineerPlatoonTemplatesSorian.lua
  lua/AI/PlatoonTemplates/LandPlatoonTemplatesSorian.lua
  lua/AI/PlatoonTemplates/SeaPlatoonTemplatesSorian.lua
  lua/AI/PlatoonTemplates/StructurePlatoonTemplatesSorian.lua
  lua/AI/aiarchetype-managerloader.lua
  lua/AI/aiattackutilities.lua
  lua/AI/aibuildstructures.lua
  lua/AI/aiutilities.lua
  lua/aibrain.lua
  lua/aibrains/base-ai.lua
  lua/aibrains/index.lua
  lua/editor/SorianBuildConditions.lua
  lua/editor/SorianInstantBuildConditions.lua
  lua/editor/UnitCountBuildConditions.lua
  lua/platoon.lua
  lua/sim/BrainConditionsMonitor.lua
  lua/sim/ScenarioUtilities.lua
  lua/simInit.lua
  lua/ui/help/tooltips.lua
Labels: area: AI

#4624 Reduce impact of effect projectiles on simulation
  effects/Entities/ADFTractorFall01/ADFTractorFall01_script.lua
  effects/Entities/AeonBuildEffect/AeonBuildEffect01_script.lua
  effects/Entities/DEBRISMISC010/DebrisMisc010_script.lua
  effects/Entities/DebrisBoneAttachChassis01/DebrisBoneAttachChassis01_script.lua
  effects/Entities/DebrisBoneAttachHigh01/DebrisBoneAttachHigh01_script.lua
  effects/Entities/DebrisBoneAttachLow01/DebrisBoneAttachLow01_script.lua
  effects/Entities/DebrisMisc01/DebrisMisc01_script.lua
  effects/Entities/DebrisMisc02/DebrisMisc02_script.lua
  effects/Entities/DebrisMisc03/DebrisMisc03_script.lua
  effects/Entities/DebrisMisc04/DebrisMisc04_script.lua
  effects/Entities/DebrisMisc05/DebrisMisc05_script.lua
  effects/Entities/DebrisMisc06/DebrisMisc06_script.lua
  effects/Entities/DebrisMisc07/DebrisMisc07_script.lua
  effects/Entities/DebrisMisc08/DebrisMisc08_script.lua
  effects/Entities/DebrisMisc09/DebrisMisc09_script.lua
  effects/Entities/DestructionDust01/DestructionDust01_proj.bp
  effects/Entities/EffectProtonAmbient01/EffectProtonAmbient01_proj.bp
  effects/Entities/EffectThrustTransport01/EffectThrustTransport01_proj.bp
  effects/Entities/EffectThrustTransport02/EffectThrustTransport02_proj.bp
  effects/Entities/InainoEffectController01/InainoEffectController01_proj.bp
  effects/Entities/SBOOhwalliBombEffect01/SBOOhwalliBombEffect01_proj.bp
  effects/Entities/SBOOhwalliBombEffect02/SBOOhwalliBombEffect02_proj.bp
  effects/Entities/SBOOhwalliBombEffect04/SBOOhwalliBombEffect04_proj.bp
  effects/Entities/SBOOhwalliBombEffect05/SBOOhwalliBombEffect05_proj.bp
  effects/Entities/SBOOhwalliBombEffect06/SBOOhwalliBombEffect06_proj.bp
  effects/Entities/SBOOhwalliBombEffectController01/SBOOhwalliBombEffectController01_proj.bp
  effects/Entities/SBOZhanaseeBombEffect01/SBOZhanaseeBombEffect01_proj.bp
  effects/Entities/SBOZhanaseeBombEffect02/SBOZhanaseeBombEffect02_proj.bp
  effects/Entities/SCUDeathShockwave01/SCUDeathShockwave01_proj.bp
  effects/Entities/SIFExperimentalStrategicMissileEffect03/SIFExperimentalStrategicMissileEffect03_proj.bp
  effects/Entities/SIFExperimentalStrategicMissileEffect04/SIFExperimentalStrategicMissileEffect04_proj.bp
  effects/Entities/SIFExperimentalStrategicMissileEffect05/SIFExperimentalStrategicMissileEffect05_proj.bp
  effects/Entities/SIFExperimentalStrategicMissileEffect06/SIFExperimentalStrategicMissileEffect06_proj.bp
  effects/Entities/SIFHuAntiNuke02/SIFHuAntiNuke02_proj.bp
  effects/Entities/SIFInainoStrategicMissileEffect01/SIFInainoStrategicMissileEffect01_proj.bp
  effects/Entities/SIFInainoStrategicMissileEffect02/SIFInainoStrategicMissileEffect02_proj.bp
  effects/Entities/SIFInainoStrategicMissileEffect03/SIFInainoStrategicMissileEffect03_proj.bp
  effects/Entities/SIFInainoStrategicMissileEffect04/SIFInainoStrategicMissileEffect04_proj.bp
  effects/Entities/UEFBuild/UEFBuild01_script.lua
  effects/Entities/UEFBuildEffect/UEFBuildEffect01_script.lua
  effects/Entities/UEFBuildEffect/UEFBuildEffect02_script.lua
  effects/Entities/UEFBuildEffect/UEFBuildEffect03_script.lua
  lua/GenericDebris.lua
  lua/sim/DefaultProjectiles.lua
  lua/sim/Projectile.lua
  lua/system/class.lua
Labels: area: sim

#4848 Replace `table.getsize` and `table.empty` with assembly alternatives
  lua/system/utils.lua
Labels: area: code style, area: sim, area: ui

#4846 Remove dead code from `TerranWeapons.lua`
  lua/terranweapons.lua
Labels: area: code style, area: sim

#4849 fix platoon former for engineers
  lua/AI/PlatoonTemplates/EngineerPlatoonTemplates.lua
  lua/AI/PlatoonTemplates/LandPlatoonTemplates.lua
Labels: area: sim, area: AI
