Repository FAForever/fa, pull requests merged in 2023-05, with the labels that each got.

#4859 AI - Introduce scripted build out for ACU.
  lua/AI/AIBaseTemplates/ACUBaseTemplate.lua
  lua/AI/AIBehaviors.lua
  lua/AI/AIBuilders/AIEconomicBuilders.lua
  lua/AI/AIBuilders/AIFactoryConstructionBuilders.lua
  lua/AI/PlatoonTemplates/EngineerPlatoonTemplates.lua
  lua/AI/aiutilities.lua
  lua/platoon.lua
Labels: area: AI

#4896 Add glowMinimum to fix water refractions
  effects/mesh.fx
Labels: area: pbr

#4898 Improve naming convention of hotkeys for AI debug tools
  lua/keymap/keyactions.lua
  lua/keymap/keycategories.lua
  lua/keymap/keydescriptions.lua
Labels: area: ui, area: AI

#4909 Add `GetTerrainLabel` for label at the given position
  lua/sim/NavUtils.lua
Labels: area: nav-mesh

#4899 Add simplified error messages
  lua/sim/NavUtils.lua
Labels: area: code style, area: AI, area: nav-mesh

#4904 Set the Cybran T1 Land Scout to be excluded from the veterancy system.
  units/URL0101/URL0101_unit.bp
Labels: area: sim

#4912 Fix Cybran T3 Shield Strategic Icons
  units/URB4206/URB4206_unit.bp
  units/URB4207/URB4207_unit.bp
Labels: area: ui

#4914 Introduce a bloom intensity slider
  lua/options/options.lua
  lua/ui/help/tooltips.lua
Labels: area: graphics

#4915 Add experimental approach to reduce decal flickering
  lua/ui/game/gamemain.lua
Labels: area: graphics

#4918 Flatten the air layer instead of compressing it
  lua/sim/NavGenerator.lua
Labels: area: AI, area: nav-mesh

#4922 Minor performance improvements for navigational mesh
  lua/sim/NavDatastructures.lua
  lua/sim/NavUtils.lua
Labels: area: sim, area: nav-mesh

#4923 Factor out the campaign elements of the base AI
  engine/Sim.lua
  engine/Sim/CAiBrain.lua
  lua/aibrain.lua
  lua/aibrains/base-ai.lua
  lua/aibrains/campaign-ai.lua
  lua/aibrains/easy-ai.lua
  lua/aibrains/index.lua
  lua/aipersonality.lua
  lua/simInit.lua
Labels: area: sim, area: AI

#4921 Introduce various transport and carrier callbacks
  lua/aibrains/platoons/platoon-base.lua
  lua/defaultunits.lua
  lua/sim/Unit.lua
Labels: area: code style, area: sim, area: AI

#4919 Take into account playable area for skirmish maps
  lua/sim/NavGenerator.lua
Labels: area: sim, area: AI, area: nav-mesh

#4925 Add functions to query playable and buildable area
  lua/sim/NavUtils.lua
Labels: area: sim, area: AI, area: nav-mesh

#4926 Revert "Remove unused base templates"
  lua/basetemplates.lua
Labels: type: bug, area: sim, area: AI

#4927 Fix bug with campaign pings
  lua/aibrain.lua
  lua/aibrains/base-ai.lua
  lua/sim/NavGenerator.lua
Labels: area: sim

#4877 Fix blocking of innocent sound banks
  init_faf.lua
  init_fafbeta.lua
  init_fafdevelop.lua
  init_shared.lua
Labels: area: sim

#4928 Fix a typo that may cause an error in the veterancy system
  lua/defaultcomponents.lua
Labels: area: sim

#4900 Texture quality experiments
  effects/water2.fx
Labels: area: graphics

#4931 Improve sun reflections
  effects/water2.fx
Labels: area: graphics

#4930 Introduce grid that allows an AI to understand map presence
  engine/Sim/CAiBrain.lua
  lua/AI/GridPresence.lua
  lua/SimCallbacks.lua
  lua/aibrains/easy-ai.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/sim/NavGenerator.lua
  lua/sim/NavUtils.lua
  lua/ui/game/GridPresence.lua
Labels: area: sim, area: AI

#4916 Initial adjustments to self destruct
  lua/keymap/keyactions.lua
  lua/selfdestruct.lua
  lua/ui/game/confirmunitdestroy.lua
Labels: area: code style

#4938 Fix issues with the colossus
  lua/aeonweapons.lua
Labels: type: bug, area: balance

#4902 Add new terrain shaders
  effects/mesh.fx
  effects/terrain.fx
Labels: area: graphics

#4942 Add missing terrain shader changes
  effects/terrain.fx
Labels: area: graphics

#4961 Add support to keep track of assigned scouts
  lua/AI/GridBrain.lua
Labels: area: sim, area: AI

#4901 Alternative approach to loading base templates and builder (groups)
  lua/aibrains/easy-ai.lua
  lua/aibrains/managers/base-manager.lua
  lua/aibrains/managers/builder-manager.lua
  lua/aibrains/managers/engineer-manager.lua
  lua/aibrains/managers/factory-manager.lua
  lua/aibrains/managers/structure-manager.lua
  lua/aibrains/templates/base/base-template.lua
  lua/aibrains/templates/base/easy-main.lua
  lua/aibrains/templates/builder-groups/builder-group-template.lua
  lua/aibrains/templates/builder-groups/builder-groups-easy-structure.lua
  lua/aibrains/templates/builder-groups/builder-template.lua
  lua/aibrains/templates/builder-groups/easy-engineers.lua
  lua/aibrains/templates/builder-groups/easy-extractors.lua
  lua/aibrains/templates/builder-groups/easy-factories.lua
  lua/aibrains/templates/builder-groups/easy-power.lua
  lua/aibrains/templates/builders/builder-template.lua
  lua/aibrains/templates/builders/builder.lua
  lua/aibrains/templates/builders/builders-easy-structure.lua
  lua/simInit.lua
Labels: area: code style, area: AI

#4970 Finalize basic structure manager
  lua/SimCallbacks.lua
  lua/aibrains/managers/base-manager.lua
  lua/aibrains/managers/builder-manager.lua
  lua/aibrains/managers/engineer-manager.lua
  lua/aibrains/managers/factory-manager.lua
  lua/aibrains/managers/structure-manager.lua
  lua/aibrains/platoons/platoon-base.lua
  lua/aibrains/platoons/platoon-engineer.lua
  lua/aibrains/platoons/platoon-silo.lua
  lua/aibrains/platoons/platoon-simple-raid.lua
  lua/aibrains/platoons/platoon-simple-structure.lua
  lua/aibrains/templates/base/easy-main.lua
  lua/aibrains/templates/builder-groups/builder-groups-easy-structure.lua
  lua/aibrains/templates/builders/builder-template.lua
  lua/aibrains/templates/builders/builder.lua
  lua/aibrains/templates/builders/builders-easy-structure.lua
  lua/keymap/keyactions.lua
  lua/keymap/misckeyactions.lua
  units/URB1103/URB1103_unit.bp
Labels: area: sim, area: AI

#4968 Basic intelisenece
  lua/ui/campaign/campaignmovies.lua
  lua/ui/campaign/operationbriefing.lua
  lua/ui/controls/acubutton.lua
  lua/ui/controls/columnlayout.lua
  lua/ui/controls/combo.lua
  lua/ui/controls/filepicker.lua
  lua/ui/controls/ninepatch.lua
  lua/ui/controls/popups/inputdialog.lua
  lua/ui/controls/popups/popup.lua
  lua/ui/controls/radiobutton.lua
  lua/ui/controls/resmappreview.lua
  lua/ui/controls/specialgrid.lua
  lua/ui/controls/textarea.lua
  lua/ui/controls/togglebutton.lua
  lua/ui/controls/worldmesh.lua
  lua/ui/controls/worldview.lua
Labels: area: code style, type: intellisense

#4872 Feat: AI add initial transport file.
  lua/AI/AIBuilders/AIAirAttackBuilders.lua
  lua/AI/AIBuilders/AILandAttackBuilders.lua
  lua/AI/Transportutilities.lua
  lua/AI/aiattackutilities.lua
  lua/AI/aiutilities.lua
  lua/aibrains/base-ai.lua
  lua/editor/MiscBuildConditions.lua
  lua/platoon.lua
  lua/sim/FactoryBuilderManager.lua
Labels: area: sim, area: AI

#4949 Reverting Mass Cost from Previous Patch
  units/UAS0103/UAS0103_unit.bp
  units/URS0103/URS0103_unit.bp
Labels: area: balance

#4951 Range buff
  units/URS0201/URS0201_unit.bp
Labels: area: balance

#4958 Harms Nerf
  units/XRB2309/XRB2309_unit.bp
Labels: area: balance

#4959 Cruiser Adjustment
  units/UAS0202/UAS0202_unit.bp
  units/UES0202/UES0202_unit.bp
  units/URS0202/URS0202_unit.bp
  units/XSS0202/XSS0202_unit.bp
Labels: area: balance

#4974 Atlantis Changes
  units/UES0401/UES0401_unit.bp
Labels: area: balance

#4965 Added the buffs
  units/UAS0303/UAS0303_unit.bp
  units/URS0303/URS0303_unit.bp
  units/XSS0303/XSS0303_unit.bp
Labels: area: balance

#4967 Nerf Torps
  units/UAA0204/UAA0204_unit.bp
  units/UEA0204/UEA0204_unit.bp
  units/URA0204/URA0204_unit.bp
  units/XSA0204/XSA0204_unit.bp
Labels: area: balance

#4991 Correcting Aeon and Cybran Frig BT/E Cost
  units/UAS0103/UAS0103_unit.bp
  units/URS0103/URS0103_unit.bp
Labels: area: balance

#4973 Add hotkeys to store the current camera position in the preference file
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/misckeyactions.lua
Labels: area: ui

#4964 Apply water color to wreckages, props, shield and unit shaders
  effects/mesh.fx
Labels: area: graphics

#4992 Fix a mistake in merging
  effects/mesh.fx
Labels: type: bug

#4993 Improves the code style for key actions
  lua/keymap/debugKeyActions.lua
  lua/keymap/keyactions.lua
  lua/keymap/keycategories.lua
  lua/keymap/keymapper.lua
  lua/system/utils.lua
Labels: area: code style

#4995 Allow Seraphim regeneration effect below water surface
  effects/emitters/seraphim_regenerative_aura_02_emit.bp
Labels: area: graphics

#4997 Add hotkey to select the nearest idle tech 1 engineer
  lua/keymap/alternativeKeyMap.lua
  lua/keymap/defaultKeyMap.lua
  lua/keymap/hotbuildKeyMap.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
Labels: area: ui

#4998 Clean up projectile blueprints
  projectiles/AAAAutocannonQuantum01/AAAAutocannonQuantum01_proj.bp
  projectiles/AAALightDisplacementAutoCannonMissile01/AAALightDisplacementAutoCannonMissile01_proj.bp
  projectiles/AAASonicPulse01/AAASonicPulse01_proj.bp
  projectiles/AAAZealotMissile01/AAAZealotMissile01_proj.bp
  projectiles/AAAZealotMissile02/AAAZealotMissile02_proj.bp
  projectiles/AANDepthCharge03/AANDepthCharge03_proj.bp
  projectiles/AANTorpedo02/AANTorpedo02_proj.bp
  projectiles/AANTorpedoChronoPack01/AANTorpedoChronoPack01_proj.bp
  projectiles/ADFDisruptor01/ADFDisruptor01_proj.bp
  projectiles/ADFGraviton01/ADFGraviton01_proj.bp
  projectiles/ADFLaserHeavy01/ADFLaserHeavy01_proj.bp
  projectiles/ADFLaserHighIntensity01/ADFLaserHighIntensity01_proj.bp
  projectiles/ADFLaserLight01/ADFLaserLight01_proj.bp
  projectiles/ADFLaserLight02/ADFLaserLight02_proj.bp
  projectiles/ADFOblivionCannon01/ADFOblivionCannon01_proj.bp
  projectiles/ADFOblivionCannon02/ADFOblivionCannon02_proj.bp
  projectiles/ADFOblivionCannon03/ADFOblivionCannon03_proj.bp
  projectiles/ADFOblivionCannon04/ADFOblivionCannon04_proj.bp
  projectiles/ADFOblivionCannon05/ADFOblivionCannon05_proj.bp
  projectiles/ADFQuadLaserLight01/ADFQuadLaserLight01_proj.bp
  projectiles/ADFQuantumCannon01/ADFQuantumCannon01_proj.bp
  projectiles/ADFQuantumCannon02/ADFQuantumCannon02_proj.bp
  projectiles/ADFReactonCannon01/ADFReactonCannon01_proj.bp
  projectiles/ADFReactonCannon02/ADFReactonCannon02_proj.bp
  projectiles/ADFRocket01/ADFRocket01_proj.bp
  projectiles/ADFShieldDisruptor01/ADFShieldDisruptor01_proj.bp
  projectiles/ADFSonicPulsar01/ADFSonicPulsar01_proj.bp
  projectiles/AIFBombGraviton01/AIFBombGraviton01_proj.bp
  projectiles/AIFBombQuark01/AIFBombQuark01_proj.bp
  projectiles/AIFFragmentationSensorShell03/AIFFragmentationSensorShell03_proj.bp
  projectiles/AIFGuidedMissile01/AIFGuidedMissile01_proj.bp
  projectiles/AIFGuidedMissile02/AIFGuidedMissile02_proj.bp
  projectiles/AIFMiasmaShell01/AIFMiasmaShell01_proj.bp
  projectiles/AIFMiasmaShell02/AIFMiasmaShell02_proj.bp
  projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_proj.bp
  projectiles/AIFMortar01/AIFMortar01_proj.bp
  projectiles/AIFMortar02/AIFMortar02_proj.bp
  projectiles/AIFQuanticCluster03/AIFQuanticCluster03_proj.bp
  projectiles/AIFQuantumWarhead01/AIFQuantumWarhead01_proj.bp
  projectiles/AIFQuantumWarhead03/AIFQuantumWarhead03_proj.bp
  projectiles/AIMFactoryBlob01/AIMFactoryBlob01_proj.bp
  projectiles/AIMFlare01/AIMFlare01_proj.bp
  projectiles/CAAAutocannon01/CAAAutocannon01_proj.bp
  projectiles/CAAAutocannon02/CAAAutocannon02_proj.bp
  projectiles/CAAAutocannon03/CAAAutocannon03_proj.bp
  projectiles/CAABurstCloud01/CAABurstCloud01_proj.bp
  projectiles/CAAMissileNanite01/CAAMissileNanite01_proj.bp
  projectiles/CAAMissileNanite02/CAAMissileNanite02_proj.bp
  projectiles/CAAMissileNanite03/CAAMissileNanite03_proj.bp
  projectiles/aaserpentine/AASerpentine_proj.bp
Labels: area: code style

#4994 Clean up key actions
  lua/SimCallbacks.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/misckeyactions.lua
Labels: area: ui
