Repository FAForever/fa, pull requests merged in 2023-09, with the labels that each got.

#5312 Change depth preview to better show unpathable water
  lua/ui/game/cursor/depth.lua
Labels: sync-to-discord

#5172 Enable switching between linear and exponential water absorption
  effects/mesh.fx
Labels: area: graphics

#5385 Implement alternative of `IssueBuildMobile`
  engine/Sim.lua
  lua/SimHooks.lua
  lua/sim/commands/copy-queue.lua
  lua/sim/commands/ring-extractor.lua
  lua/sim/commands/shared.lua
Labels: feature: distribute orders

#5384 fixed unit scripts if blueprints are missing values
  units/URL0303/URL0303_Script.lua
  units/URS0201/URS0201_script.lua
  units/XRL0403/XRL0403_script.lua
  units/XSB3202/XSB3202_script.lua
Labels: status: need review, area: sim, area: unit-blueprint

#5386 Implement the ringing behavior for fabricators
  engine/Sim.lua
  lua/SimCallbacks.lua
  lua/options/options.lua
  lua/sim/commands/ring-with-fabricators.lua
  lua/sim/commands/ring-with-storages.lua
  lua/sim/commands/shared.lua
  lua/ui/game/hotkeys/ring-extractor.lua
Labels: feature: ringing of extractors

#5387 Sort the build orders by distance
  lua/sim/commands/ring-with-fabricators.lua
  lua/sim/commands/ring-with-storages.lua
  lua/sim/commands/shared.lua
Labels: area: sim, feature: ringing of extractors

#5389 Reduce memory allocations when ringing structures
  engine/Sim/CAiBrain.lua
  lua/sim/commands/ring-with-fabricators.lua
  lua/sim/commands/ring-with-storages.lua
  lua/sim/commands/shared.lua
Labels: feature: ringing of extractors

#5390 Abstract the ringing feature to make it easier to use
  lua/SimCallbacks.lua
  lua/sim/commands/ring-with-storages.lua
  lua/sim/commands/ringing/ring-with-fabricators.lua
  lua/sim/commands/ringing/ring-with-storages.lua
  lua/sim/commands/ringing/shared.lua
  lua/sim/commands/shared.lua
Labels: area: code style, feature: ringing of extractors

#5391 Add ringing of radar and artillery
  lua/SimCallbacks.lua
  lua/options/options.lua
  lua/sim/commands/ringing/ring-with-power.lua
  lua/ui/game/hotkeys/ring-extractor.lua
Labels: feature: ringing of extractors

#5392 Ring end game artillery with power generators
  engine/Sim/CAiBrain.lua
  lua/SimCallbacks.lua
  lua/options/options.lua
  lua/sim/commands/ringing/ring-with-power-tech1.lua
  lua/sim/commands/ringing/ring-with-power-tech3.lua
  lua/sim/commands/ringing/shared.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/hotkeys/ringing.lua
Labels: feature: ringing of extractors

#5393 Add tooltips to options related to capping
  lua/options/options.lua
  lua/ui/game/hotkeys/ringing.lua
  lua/ui/help/tooltips.lua
Labels: feature: ringing of extractors

#5394 Abstract to allow a hotkey to perform the capping behavior too
  engine/User/UserUnit.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/options/options.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/hotkeys/capping.lua
Labels: feature: ringing of extractors

#5397 add hotkey to select all units that are consuming resources
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/misckeyactions.lua
Labels: area: ui, feature: hotkeys

#5398 Hotkey to upgrade unit you're hovering over
  engine/Core.lua
  engine/User.lua
  engine/User/UserUnit.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/hotkeys/upgrade-structure.lua
  lua/userInit.lua
Labels: area: ui, feature: hotkeys

#5403 Fix water color above water
  effects/terrain.fx
Labels: area: graphics

#5408 Add more game options and improve the hotkey
  engine/User.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/options/options.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/hotkeys/capping.lua
  lua/ui/help/tooltips.lua
Labels: feature: capping of structures

#5405 fixed layout in mods manager and links dialog
  lua/maui/grid.lua
  lua/system/utils.links.lua
  lua/ui/lobby/ModsManager.lua
  lua/userInit.lua
Labels: status: need review, area: ui, area: mod-manager

#5407 Add `GetPositionsInRadius` and generate naval markers
  lua/SimCallbacks.lua
  lua/aibrains/base-ai.lua
  lua/aibrains/easy-ai.lua
  lua/keymap/debugKeyActions.lua
  lua/sim/MarkerGenerator.lua
  lua/sim/MarkerUtilities.lua
  lua/sim/MarkerUtilities/NavalAreas.lua
  lua/sim/NavDebug/GetPositionsInRadius.lua
  lua/sim/NavGenerator.lua
  lua/sim/NavUtils.lua
  lua/ui/game/NavDebug/GetPositionsInRadius.lua
Labels: area: sim, area: nav-mesh

#5425 TurnRate-engine-reference-fix
  engine/Sim/Projectile.lua
Labels: area: code style

#5427 Add performance metric debug window
  lua/keymap/debugKeyActions.lua
  lua/keymap/keyactions.lua
  lua/keymap/misckeyactions.lua
  lua/system/performance.lua
  lua/ui/game/tooltip.lua
  lua/ui/lobby/ModsManager.lua
  lua/ui/lobby/pong-ping.lua
  lua/ui/lobby/sim-performance-popup.lua
Labels: area: ui

#5423 Decrease the MaxAirspeed of all T2 Transports from 14.3 to 13.5
  units/UAA0104/UAA0104_unit.bp
  units/UEA0104/UEA0104_unit.bp
  units/URA0104/URA0104_unit.bp
  units/XSA0104/XSA0104_unit.bp
Labels: area: balance

#5422 Resource deposit grid for AIs
  lua/AI/GridDeposits.lua
  lua/AI/GridPresence.lua
  lua/aibrains/base-ai.lua
  lua/sim/NavGenerator.lua
  lua/sim/NavUtils.lua
Labels: area: AI

#5445 Fix beams being able to miss the Colossus
  units/UAL0401/UAL0401_unit.bp
Labels: area: balance, area: sim

#5444 Fix small details of the Seraphim frigate
  units/XSS0103/XSS0103_unit.bp
Labels: area: balance, area: sim

#5443 Fix small details of the Thunderhead Class
  lua/EffectTemplates.lua
  lua/terranprojectiles.lua
  units/UES0103/UES0103_unit.bp
Labels: area: sim

#5440 All spawn locations are now populated with spawn markers
  lua/sim/MarkerUtilities.lua
Labels: area: AI

#5442 Fix small details of the Trident Class
  lua/EffectTemplates.lua
  lua/cybranprojectiles.lua
  units/URS0103/URS0103_unit.bp
Labels: area: sim, area: graphics

#5447 Fix various issues with beam weapons in naval engagements
  lua/sim/Projectile.lua
  units/UAS0203/UAS0203_unit.bp
  units/UES0201/UES0201_unit.bp
  units/UES0203/UES0203_unit.bp
  units/URS0203/URS0203_unit.bp
  units/XAS0204/XAS0204_unit.bp
  units/XRS0204/XRS0204_unit.bp
  units/XSS0203/XSS0203_unit.bp
Labels: type: bug, area: balance, area: sim

#5441 Fix small details of the Beacon Class
  lua/EffectTemplates.lua
  lua/aeonprojectiles.lua
  units/UAS0103/UAS0103_LOD0.scm
  units/UAS0103/UAS0103_unit.bp
Labels: area: sim, area: graphics

#5448 Drat version to generate spawns like expansion markers
  lua/sim/MarkerUtilities.lua
  lua/sim/MarkerUtilities/Expansions.lua
Labels: area: AI

#5433 Tactical missile component rework
  engine/Sim/Projectile.lua
  lua/sim/DefaultProjectiles.lua
  lua/sim/components-projectile/SemiBallisticComponent.lua
  lua/sim/components-projectile/TacticalMissileComponent.lua
  projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
  projectiles/AIFMissileSerpentine02/AIFMissileSerpentine02_script.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
  projectiles/AIFMissileTactical01/AIFMissileTactical01_Script.lua
  projectiles/AIFMissileTactical02/AIFMissileTactical02_Script.lua
  projectiles/CIFMissileTactical01/CIFMissileTactical01_Script.lua
  projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua
  projectiles/CIFMissileTactical03/CIFMissileTactical03_Script.lua
  projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_Script.lua
  projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_Script.lua
  projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_Script.lua
  projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_script.lua
  projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_script.lua
  projectiles/TIFMissileCruise01/TIFMissileCruise01_Script.lua
  projectiles/TIFMissileCruise02/TIFMissileCruise02_script.lua
  projectiles/TIFMissileCruise03/TIFMissileCruise03_Script.lua
  projectiles/TIFMissileCruise04/TIFMissileCruise04_Script.lua
  projectiles/TIFMissileCruise05/TIFMissileCruise05_Script.lua
  projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_Script.lua
  units/UAL0111/UAL0111_unit.bp
  units/UEL0111/UEL0111_unit.bp
  units/URL0111/URL0111_unit.bp
  units/XSL0111/XSL0111_unit.bp
Labels: area: balance, area: sim, feature: tactical missiles

#5369 Add a fuzziness factor to where tactical missiles end up when firing on a unit
  engine/Core/Blueprints/ProjectileBlueprint.lua
  lua/aeonprojectiles.lua
  lua/sim/Projectile.lua
  lua/sim/components-projectile/TacticalMissileComponent.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_proj.bp
  units/XAS0306/XAS0306_unit.bp
Labels: area: balance, feature: tactical missiles

#5254 Allow monkeylord to walk backwards
  units/URL0402/URL0402_script.lua
  units/URL0402/URL0402_unit.bp
Labels: area: balance, sync-to-discord

#5370 Multiple pod orders
  lua/ui/game/orders.lua
Labels: area: ui

#5256 Change default enemyIndex for GetBestThreatTarget
  lua/AI/aiattackutilities.lua
Labels: area: AI

#5125 Right click appends to selection set
  lua/ui/game/controlgroups.lua
Labels: area: ui, sync-to-discord

#5436 Table allocation free versions of sim commands
  engine/Sim.lua
  lua/AI/AIBehaviors.lua
  lua/AI/OpAI/BaseManager.lua
  lua/AI/OpAI/BaseManagerPlatoonThreads.lua
  lua/AI/OpAI/OpBehaviors.lua
  lua/AI/Transportutilities.lua
  lua/AI/aibuildstructures.lua
  lua/AI/aiutilities.lua
  lua/ScenarioFramework.lua
  lua/ScenarioPlatoonAI.lua
  lua/SimCallbacks.lua
  lua/SimHooks.lua
  lua/aeonweapons.lua
  lua/aibrain.lua
  lua/aibrains/campaign-ai.lua
  lua/defaultcomponents.lua
  lua/defaultunits.lua
  lua/platoon.lua
  lua/seraphimunits.lua
  lua/sim/Unit.lua
  units/UAA0310/UAA0310_script.lua
  units/UAS0303/UAS0303_script.lua
  units/UAS0401/UAS0401_script.lua
  units/UES0401/UES0401_script.lua
  units/URA0001/URA0001_script.lua
  units/URS0303/URS0303_script.lua
  units/XEB2402/XEB2402_Script.lua
  units/XSS0303/XSS0303_script.lua
Labels: area: sim

#5454 Fix various issues with SMLs and TMLs
  changelog.md
  engine/Core/Blueprints/WeaponBlueprint.lua
  lua/sim/defaultweapons.lua
  lua/ui/lobby/changelogData.lua
  lua/ui/lobby/lobby.lua
  lua/ui/notify/notify.lua
  lua/version.lua
  mod_info.lua
  units/UAS0304/UAS0304_unit.bp
  units/UES0304/UES0304_unit.bp
  units/URB2108/URB2108_unit.bp
  units/URS0304/URS0304_unit.bp
  units/XSL0111/XSL0111_unit.bp
  units/XSS0302/XSS0302_unit.bp
Labels: type: bug, area: sim

#5474 Separate files for each type of projectile
  engine/Sim.lua
  lua/DefaultProjectiles/Debris.lua
  lua/DefaultProjectiles/Emitter.lua
  lua/DefaultProjectiles/MultiBeam.lua
  lua/DefaultProjectiles/MultiCompositeEmitter.lua
  lua/DefaultProjectiles/MultiPolyTrail.lua
  lua/DefaultProjectiles/Nuke.lua
  lua/DefaultProjectiles/Null.lua
  lua/DefaultProjectiles/OnWaterEntryEmitter.lua
  lua/DefaultProjectiles/Overcharge.lua
  lua/DefaultProjectiles/SingleBeam.lua
  lua/DefaultProjectiles/SingleCompositeEmitter.lua
  lua/DefaultProjectiles/SinglePolyTrail.lua
  lua/sim/DefaultProjectiles.lua
Labels: area: code style

#5479 Projectiles that retarget autonomously
  engine/Core/Blueprints/ProjectileBlueprint.lua
  engine/Sim/Projectile.lua
  lua/sim/Projectile.lua
  lua/sim/weapon.lua
  units/UAB2204/UAB2204_unit.bp
  units/UAS0202/UAS0202_unit.bp
  units/UEB2204/UEB2204_unit.bp
  units/UES0202/UES0202_unit.bp
  units/URB2204/URB2204_unit.bp
  units/URS0202/URS0202_unit.bp
  units/XSB2204/XSB2204_unit.bp
Labels: area: balance

#5483 LOG left in Cybran ACU enhancement script
  units/URL0001/URL0001_script.lua
Labels: type: bug

#5482 AI - State Machine fixes
  lua/AI/AIBuilders/AIEconomicBuilders.lua
  lua/AI/AIBuilders/AIIntelBuilders.lua
  lua/AI/AIBuilders/AILandAttackBuilders.lua
  lua/AI/PlatoonTemplates/LandPlatoonTemplates.lua
  lua/AI/aiutilities.lua
  lua/aibrains/adaptive-ai.lua
  lua/aibrains/platoons/platoon-adaptive-attack.lua
  lua/aibrains/platoons/platoon-adaptive-guard.lua
  lua/aibrains/platoons/platoon-adaptive-raid.lua
  lua/aibrains/platoons/platoon-adaptive-reclaim.lua
  lua/aibrains/platoons/platoon-adaptive-returntobase.lua
  lua/aibrains/platoons/platoon-base.lua
  lua/aibrains/platoons/platoon-simple-raid.lua
  lua/editor/MiscBuildConditions.lua
  lua/platoon.lua
Labels: area: AI

#5481 AI - Add transport return to base functionality on low fuel/health
  lua/AI/Transportutilities.lua
Labels: area: AI

#5487 Raised Platform visualisation for cheat spawn menu
  lua/SimCallbacks.lua
  lua/ui/dialogs/createunit.lua
  lua/ui/game/commandmode.lua
Labels: area: sim

#5477 Separate files for default unit classes
  lua/DefaultUnitComponents/Transport.lua
  lua/DefaultUnits/ACU.lua
  lua/DefaultUnits/Air.lua
  lua/DefaultUnits/AirFactory.lua
  lua/DefaultUnits/AirStagingPlatform.lua
  lua/DefaultUnits/AirTransport.lua
  lua/DefaultUnits/AircraftCarrier.lua
  lua/DefaultUnits/AmphibiousLand.lua
  lua/DefaultUnits/Command.lua
  lua/DefaultUnits/ConcreteStructure.lua
  lua/DefaultUnits/Construction.lua
  lua/DefaultUnits/EnergyCreation.lua
  lua/DefaultUnits/EnergyStorage.lua
  lua/DefaultUnits/ExternalFactory.lua
  lua/DefaultUnits/Factory.lua
  lua/DefaultUnits/HoverLand.lua
  lua/DefaultUnits/Land.lua
  lua/DefaultUnits/LandFactory.lua
  lua/DefaultUnits/MassCollection.lua
  lua/DefaultUnits/MassFabrication.lua
  lua/DefaultUnits/MassStorage.lua
  lua/DefaultUnits/Mobile.lua
  lua/DefaultUnits/QuantumGate.lua
  lua/DefaultUnits/Radar.lua
  lua/DefaultUnits/RadarJammer.lua
  lua/DefaultUnits/Sea.lua
  lua/DefaultUnits/SeaFactory.lua
  lua/DefaultUnits/ShieldHoverLand.lua
  lua/DefaultUnits/ShieldLand.lua
  lua/DefaultUnits/ShieldSea.lua
  lua/DefaultUnits/ShieldStructure.lua
  lua/DefaultUnits/SlowAmphibiousLand.lua
  lua/DefaultUnits/SlowHoverLand.lua
  lua/DefaultUnits/Sonar.lua
  lua/DefaultUnits/Structure.lua
  lua/DefaultUnits/Sub.lua
  lua/DefaultUnits/TransportBeacon.lua
  lua/DefaultUnits/WalkingLand.lua
  lua/DefaultUnits/WallStructure.lua
  lua/defaultunits.lua
  lua/sim/Unit.lua
Labels: area: code style
