Repository FAForever/fa, pull requests merged in 2023-07, with the labels that each got.

#5173 Fix errors that originate from formatting
  lua/sim/MapUtilities.lua
  units/ZXA0001/ZXA0001_unit.bp
Labels: type: bug

#5170 Fixed Advanced Regen Aura
  units/XSL0001/XSL0001_unit.bp
Labels: area: balance

#5192 Mercy Tweeks
  units/DAA0206/DAA0206_unit.bp
Labels: area: balance

#5196 Fix sniper bot weapon abuse
  units/XSL0305/XSL0305_script.lua
  units/XSL0305/XSL0305_unit.bp
Labels: area: balance

#5203 Fix splash damage being able to destroy certain projectiles
  engine/Core/Categories.lua
  projectiles/AANTorpedo01/AANTorpedo01_proj.bp
  projectiles/AANTorpedoChronoPack01/AANTorpedoChronoPack01_proj.bp
  projectiles/AANTorpedoCluster01/AANTorpedoCluster01_proj.bp
  projectiles/AANTorpedoClusterSplit01/AANTorpedoClusterSplit01_proj.bp
  projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_proj.bp
  projectiles/AIFMissileSerpentine02/AIFMissileSerpentine02_proj.bp
  projectiles/AIFMissileTactical01/AIFMissileTactical01_proj.bp
  projectiles/CANTorpedoNanite01/CANTorpedoNanite01_proj.bp
  projectiles/CANTorpedoNanite02/CANTorpedoNanite02_proj.bp
  projectiles/CANTorpedoNanite03/CANTorpedoNanite03_proj.bp
  projectiles/CIFMissileTactical01/CIFMissileTactical01_proj.bp
  projectiles/CIFMissileTactical02/CIFMissileTactical02_proj.bp
  projectiles/CIFMissileTactical03/CIFMissileTactical03_proj.bp
  projectiles/SANHeavyCavitationTorpedo01/SANHeavyCavitationTorpedo01_proj.bp
  projectiles/SANHeavyCavitationTorpedo02/SANHeavyCavitationTorpedo02_proj.bp
  projectiles/SANHeavyCavitationTorpedo03/SANHeavyCavitationTorpedo03_proj.bp
  projectiles/SANHeavyCavitationTorpedo04/SANHeavyCavitationTorpedo04_proj.bp
  projectiles/SANUallCavitationTorpedo01/SANUallCavitationTorpedo01_proj.bp
  projectiles/SANUallCavitationTorpedo02/SANUallCavitationTorpedo02_proj.bp
  projectiles/SANUallCavitationTorpedo03/SANUallCavitationTorpedo03_proj.bp
  projectiles/SANUallCavitationTorpedo04/SANUallCavitationTorpedo04_proj.bp
  projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_proj.bp
  projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_proj.bp
  projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_proj.bp
  projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_proj.bp
  projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_proj.bp
  projectiles/TANAnglerTorpedo01/TANAnglerTorpedo01_proj.bp
  projectiles/TANAnglerTorpedo02/TANAnglerTorpedo02_proj.bp
  projectiles/TANAnglerTorpedo03/TANAnglerTorpedo03_proj.bp
  projectiles/TIFMissileCruise01/TIFMissileCruise01_proj.bp
  projectiles/TIFMissileCruise02/TIFMissileCruise02_proj.bp
  projectiles/TIFMissileCruise03/TIFMissileCruise03_proj.bp
  projectiles/TIFMissileCruise04/TIFMissileCruise04_proj.bp
  projectiles/TIFMissileCruise05/TIFMissileCruise05_proj.bp
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_proj.bp
Labels: type: bug

#5214 Drone Uniformity
  units/UEA0001/UEA0001_unit.bp
  units/UEA0003/UEA0003_unit.bp
Labels: area: balance

#5221 Fix a bug where the Cybran extractors would not turn off their animation
  lua/cybranunits.lua
Labels: type: bug

#5222 Fix a bug that allows you to get a refund
  lua/cybranunits.lua
Labels: type: bug

#5162 Fix shield visibility on land maps
  effects/mesh.fx
Labels: area: graphics

#5234 AI - Fix no threat being assigning to mobile indirect fire units
  lua/system/blueprints-ai.lua
Labels: area: AI

#5245 Stop idle animation when upgrading
  units/XSB1202/XSB1202_script.lua
Labels: type: bug

#5246 Wait 10 seconds before killing remaining units after recall
  lua/aibrain.lua
Labels: area: sim

#5247 Re-introduce a hotkey that people were using a lot
  lua/SimCallbacks.lua
  lua/keymap/keyactions.lua
  lua/keymap/keycategories.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/misckeyactions.lua
Labels: area: ui

#5228 Re-implementation of spread attack
  engine/Sim/Unit.lua
  lua/SimCallbacks.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/misckeyactions.lua
  lua/seraphimunits.lua
  lua/sim/Unit.lua
Labels: area: sim

#5237 Fix issues with the Mercy
  effects/emitters/X1Mercy_cloud_emit.bp
  projectiles/AIFGuidedMissile01/AIFGuidedMissile01_Script.lua
  projectiles/AIFGuidedMissile01/AIFGuidedMissile01_proj.bp
  projectiles/AIFGuidedMissile02/AIFGuidedMissile02_Script.lua
  projectiles/AIFGuidedMissile02/AIFGuidedMissile02_proj.bp
  units/DAA0206/DAA0206_unit.bp
Labels: type: bug, area: balance

#5262 add capping for T3/T4 arty and T4 air factory
  lua/SimCallbacks.lua
  lua/ui/game/commandmode.lua
Labels: type: enhancement, area: sim, area: ui

#5266 Fix wrecks being removed when constructing on top of them
  README.md
  engine/Core/Blueprints/PropBlueprint.lua
  lua/system/blueprints-props.lua
  props/DefaultWreckage/DefaultWreckage_prop.bp
Labels: type: bug, area: sim

#5265 Fix UI scaling of unit cheat menu
  lua/ui/dialogs/createunit.lua
Labels: area: ui

#5276 Add hotkeys to dive or surface all units
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/misckeyactions.lua
  lua/ui/game/orders.lua
Labels: area: ui

#5277 Prevent intel from hijacking the progress bar during an enhancement
  lua/defaultcomponents.lua
Labels: area: ui

#5282 Fix tech 3 mobile anti air being at the front of a formation
  lua/formations.lua
  units/DRLK001/DRLK001_unit.bp
  units/DSLK004/DSLK004_unit.bp
Labels: area: sim

#5283 Add platoon form callbacks for conditional builds
  lua/AI/OpAI/BaseManagerPlatoonThreads.lua
Labels: type: enhancement, area: sim, area: coop

#5269 add unit count input, fix army selector in debug/cheat window
  lua/SimCallbacks.lua
  lua/ui/dialogs/createunit.lua
Labels: type: enhancement, status: need review, area: ui

#5285 Remove ability to cap air factories
  lua/ui/game/commandmode.lua
Labels: area: ui

#5288 Check whether the target is at least an entity
  lua/sim/Unit.lua
Labels: type: bug

#5289 Add annotations for the command queue
  engine/Sim/Entity.lua
  lua/SimCallbacks.lua
  lua/sim/Unit.lua
Labels: area: code style

#5290 Fix the save-load sequence
  lua/sim/NavDebug.lua
  lua/sim/NavGenerator.lua
  lua/sim/NavUtils.lua
Labels: type: bug, area: nav-mesh

#5291 Fix the Ythotha storm ignoring allies and empty space
  lua/defaultcollisionbeams.lua
  units/XSL0402/XSL0402_script.lua
Labels: type: bug

#5294 Fix orientation of a unit after being gifted
  lua/SimUtils.lua
Labels: type: bug
