Repository FAForever/fa, pull requests merged in 2023-12, with the labels that each got.

#5715 Fix Deceiver Range Buff
  units/URL0306/URL0306_unit.bp
Labels: area: balance

#5719 Fix AA formations for directfire-capable land AA
  units/DRLK001/DRLK001_unit.bp
  units/DSLK004/DSLK004_unit.bp
  units/URL0104/URL0104_unit.bp
Labels: feature: formations

#5686 Process changes to the Torrent
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_proj.bp
  units/XAS0306/XAS0306_unit.bp
Labels: area: balance

#5729 Fix presets giving double veterancy
  lua/sim/Unit.lua
Labels: type: bug

#5679 Move UEF Teleport to Left Arm
  lua/ui/game/orders.lua
  units/UEL0001/UEL0001_unit.bp
Labels: area: balance, area: ui

#5740 Let Suthanus fire backwards
  units/XSL0304/XSL0304_unit.bp
Labels: type: bug

#5732 Don't remove unit buildrate after processing external factory
  lua/system/blueprints-units.lua
Labels: feature: mobile factories

#5726 Terrain bugfixes and small improvements
  effects/terrain.fx
Labels: area: graphics

#5734 Water reflection
  effects/water2.fx
Labels: area: graphics

#5672 Move Cybran Unit Bases Classes to separate files
  .vscode/settings.json
  engine/Sim/Unit.lua
  lua/SimHooks.lua
  lua/cybranunits.lua
  lua/sim/Unit.lua
  lua/sim/units/cybran/CAirFactoryUnit.lua
  lua/sim/units/cybran/CAirStagingPlatformUnit.lua
  lua/sim/units/cybran/CAirUnit.lua
  lua/sim/units/cybran/CBuildBotUnit.lua
  lua/sim/units/cybran/CCivilianStructureUnit.lua
  lua/sim/units/cybran/CCommandUnit.lua
  lua/sim/units/cybran/CConcreteStructureUnit.lua
  lua/sim/units/cybran/CConstructionEggUnit.lua
  lua/sim/units/cybran/CConstructionStructureUnit.lua
  lua/sim/units/cybran/CConstructionTemplate.lua
  lua/sim/units/cybran/CConstructionUnit.lua
  lua/sim/units/cybran/CEnergyCreationUnit.lua
  lua/sim/units/cybran/CEnergyStorageUnit.lua
  lua/sim/units/cybran/CLandFactoryUnit.lua
  lua/sim/units/cybran/CLandUnit.lua
  lua/sim/units/cybran/CMassCollectionUnit.lua
  lua/sim/units/cybran/CMassFabricationUnit.lua
  lua/sim/units/cybran/CMassStorageUnit.lua
  lua/sim/units/cybran/CQuantumGateUnit.lua
  lua/sim/units/cybran/CRadarJammerUnit.lua
  lua/sim/units/cybran/CRadarUnit.lua
  lua/sim/units/cybran/CSeaFactoryUnit.lua
  lua/sim/units/cybran/CSeaUnit.lua
  lua/sim/units/cybran/CShieldLandUnit.lua
  lua/sim/units/cybran/CShieldStructureUnit.lua
  lua/sim/units/cybran/CSonarUnit.lua
  lua/sim/units/cybran/CStructureUnit.lua
  lua/sim/units/cybran/CSubUnit.lua
  lua/sim/units/cybran/CTransportBeaconUnit.lua
  lua/sim/units/cybran/CWalkingLandUnit.lua
  lua/sim/units/cybran/CWallStructureUnit.lua
  units/URA0001O/URA0001O_script.lua
  units/URA0002O/URA0002O_script.lua
  units/URA0003O/URA0003O_script.lua
Labels: area: code style

#5745 Improve the build animation of Cybran naval factories
  engine/Sim.lua
  lua/sim/units/components/Cybran1BuildArmComponent.lua
  lua/sim/units/components/Cybran2BuildArmComponent.lua
  lua/sim/units/components/Cybran3BuildArmComponent.lua
  lua/sim/units/cybran/CSeaFactoryUnit.lua
  units/URB0103/URB0103_Abuild.sca
  units/URB0103/URB0103_script.lua
  units/URB0103/URB0103_unit.bp
  units/URB0203/URB0203_Abuild.sca
  units/URB0203/URB0203_script.lua
  units/URB0203/URB0203_unit.bp
  units/URB0303/URB0303_Abuild.sca
  units/URB0303/URB0303_script.lua
  units/URB0303/URB0303_unit.bp
  units/ZRB9503/ZRB9503_script.lua
  units/ZRB9503/ZRB9503_unit.bp
  units/ZRB9603/ZRB9603_script.lua
  units/ZRB9603/ZRB9603_unit.bp
Labels: area: graphics

#5731 actually fix double veterancy and make wrecks copy enhancement costs
  lua/sim/Unit.lua
Labels: area: balance

#5748 Toggle repeat build for external factories
  lua/keymap/misckeyactions.lua
Labels: area: ui, feature: mobile factories, feature: hotkeys

#5746 Adjust SACU preset selectionpriority for combat
  lua/system/Blueprints.lua
  units/UAL0301/UAL0301_script.lua
  units/UAL0301/UAL0301_unit.bp
  units/UEL0301/UEL0301_unit.bp
  units/URL0301/URL0301_unit.bp
  units/XSL0301/XSL0301_unit.bp
Labels: area: ui

#5741 Fix Janus and Scorcher tracking bombs
  lua/sim/defaultweapons.lua
  lua/sim/weapons/uef/TIFCarpetBombWeapon.lua
Labels: area: sim

#5739 Reduce Scathis selection priority to structure level
  units/URL0401/URL0401_unit.bp
Labels: feature: selection behavior

#5737 Improve Bulwark UI and give it a dummy weapon
  units/XES0205/XES0205_script.lua
  units/XES0205/XES0205_unit.bp
Labels: feature: target pointers for mobile shields

#5730 Make veterancy requirements equal for presets and SACUs
  lua/system/Blueprints.lua
  lua/ui/game/unitview.lua
Labels: area: balance

#5757 Fix crash when cybran build bots assist a silo
  lua/sim/units/cybran/CBuildBotUnit.lua
Labels: type: bug, area: engine

#5756 Fix shields warping across the map
  lua/shield.lua
Labels: type: bug

#5725 Perfect the reload time calculations
  lua/ui/game/unitviewDetail.lua
  projectiles/AANTorpedoCluster01/AANTorpedoCluster01_proj.bp
  projectiles/AANTorpedoCluster01/AANTorpedoCluster01_script.lua
  projectiles/AIFQuanticCluster01/AIFQuanticCluster01_proj.bp
  projectiles/AIFQuanticCluster01/AIFQuanticCluster01_script.lua
  projectiles/AIFQuanticCluster02/AIFQuanticCluster02_proj.bp
  projectiles/AIFQuanticCluster02/AIFQuanticCluster02_script.lua
Labels: area: ui, feature: weapon firing cycle

#5761 Fix bug that can make build queue unresponsive
  engine/User.lua
  lua/ui/game/gamemain.lua
  lua/ui/game/unitview.lua
  lua/userInit.lua
Labels: type: bug, area: ui

#5738 Double the exponential absorption rate of water
  effects/mesh.fx
  effects/terrain.fx
Labels: area: graphics

#5628 Override navigator behavior of the Beetle
  effects/Entities/BeetleDebris01/BeetleDebris01_proj.bp
  effects/Entities/BeetleDebris01/BeetleDebris01_script.lua
  lua/EffectTemplates.lua
  units/XRL0302/XRL0302_Script.lua
  units/XRL0302/XRL0302_unit.bp
Labels: area: sim

#5750 Re-implementation of the AI - Part 2
  lua/aibrains/easy-ai.lua
  lua/aibrains/index.lua
  lua/aibrains/managers/base-manager.lua
  lua/aibrains/managers/builder-manager.lua
  lua/aibrains/managers/engineer-manager.lua
  lua/aibrains/managers/factory-manager.lua
  lua/aibrains/managers/structure-manager.lua
  lua/aibrains/platoons/platoon-base.lua
  lua/aibrains/platoons/platoon-simple-engineer.lua
  lua/aibrains/platoons/platoon-simple-factory.lua
  lua/aibrains/platoons/platoon-simple-structure.lua
  lua/aibrains/tasks/brain/simple-energy.lua
  lua/aibrains/tasks/brain/simple-factories.lua
  lua/aibrains/tasks/brain/simple-mass.lua
  lua/aibrains/tasks/brain/simple-mobile-antiair.lua
  lua/aibrains/tasks/brain/simple-mobile-directfire.lua
  lua/aibrains/tasks/brain/simple-mobile-shield.lua
  lua/aibrains/tasks/brain/simple-mobile-stealth.lua
  lua/aibrains/tasks/brain/simple-radar.lua
  lua/aibrains/tasks/brain/simple-sonar.lua
  lua/aibrains/tasks/task.lua
Labels: area: AI

#5633 Initial setup for the new chunk template concept
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/keymap/debugKeyActions.lua
  lua/shared/aichunktemplates.lua
  lua/ui/game/aichunktemplates.lua
Labels: area: AI

#5772 Fix rapid fire ground to air flak
  units/UAB2204/UAB2204_unit.bp
  units/XEA0306/XEA0306_unit.bp
  units/XSB2204/XSB2204_unit.bp
Labels: type: bug, feature: weapon firing cycle

#5775 Pass unit events to the brain
  lua/aibrain.lua
  lua/aibrains/base-ai.lua
  lua/aibrains/easy-ai.lua
  lua/aibrains/managers/base-manager.lua
  lua/aibrains/managers/engineer-manager.lua
  lua/aibrains/managers/factory-manager.lua
  lua/aibrains/managers/structure-manager.lua
  lua/aibrains/platoons/platoon-adaptive-silo.lua
  lua/aibrains/platoons/platoon-base.lua
  lua/aibrains/platoons/platoon-simple-engineer.lua
  lua/aibrains/platoons/platoon-simple-structure.lua
  lua/sim/BuilderManager.lua
  lua/sim/Unit.lua
  lua/simInit.lua
Labels: area: AI

#5780 Experimental changes for the Fatboy
  units/UEL0401/UEL0401_unit.bp
Labels: area: balance, area: balance idea

#5783 UEF ACU: Revert the option to have the teleporter and nuke upgrades simultaneously
  units/UEL0001/UEL0001_unit.bp
Labels: area: balance

#5782 Fix issues with Aeon tactical missile defenses
  engine/Sim.lua
  lua/defaultantiprojectile.lua
  lua/sim/projectiles/aeon/AIMFlareProjectile.lua
  lua/system/blueprints-weapons.lua
  projectiles/AIMAntiMissile01/AIMAntiMissile01_script.lua
  units/UAB4201/UAB4201_unit.bp
  units/UAS0202/UAS0202_unit.bp
  units/UAS0302/UAS0302_unit.bp
  units/UAS0303/UAS0303_unit.bp
Labels: type: bug, feature: tactical missiles
