Repository FAForever/fa, pull requests merged in 2023-06, with the labels that each got.

#5004 Revert to ps_2_a
  effects/mesh.fx
Labels: area: graphics, area: pbr

#4972 Pbr terrain improvement
  effects/terrain.fx
Labels: area: graphics

#5002 Navy TMD Changes
  units/UES0202/UES0202_unit.bp
  units/UES0302/UES0302_unit.bp
  units/URS0202/URS0202_unit.bp
  units/URS0302/URS0302_unit.bp
  units/URS0303/URS0303_unit.bp
  units/XES0307/XES0307_unit.bp
  units/XSS0202/XSS0202_unit.bp
  units/XSS0302/XSS0302_unit.bp
Labels: area: balance

#4987 T1 Sub Hp Buff
  units/UAS0203/UAS0203_unit.bp
  units/UES0203/UES0203_unit.bp
  units/URS0203/URS0203_unit.bp
  units/XSS0203/XSS0203_unit.bp
Labels: area: balance

#4988 Cooper Adjustments
  units/XES0102/XES0102_unit.bp
Labels: area: balance

#5008 Add generated threat of structures of a base to the structure manager
  lua/aibrains/conditions/structure-manager-conditions.lua
  lua/aibrains/managers/structure-manager.lua
Labels: area: AI

#5009 Add draft of debugging interface for the (base) managers of the AI
  lua/aibrains/easy-ai.lua
  lua/aibrains/managers/base-manager.lua
  lua/aibrains/managers/engineer-manager.lua
  lua/aibrains/managers/factory-manager.lua
  lua/aibrains/managers/structure-manager.lua
  lua/keymap/debugKeyActions.lua
  lua/ui/game/AIBaseInfo.lua
Labels: area: code style, area: AI

#4570 Adjust pathing parameters of transports to improve (un)loading
  lua/sim/Unit.lua
  units/UAA0104/UAA0104_unit.bp
  units/UAA0107/UAA0107_unit.bp
  units/UEA0104/UEA0104_unit.bp
  units/UEA0107/UEA0107_unit.bp
  units/URA0104/URA0104_unit.bp
  units/URA0107/URA0107_unit.bp
  units/XEA0306/XEA0306_unit.bp
  units/XSA0104/XSA0104_unit.bp
  units/XSA0107/XSA0107_unit.bp
Labels: area: balance

#4852 Spirit speed nerf
  units/UAL0101/UAL0101_unit.bp
Labels: area: balance

#4975 Scathis accuracy fix
  units/URL0401/URL0401_unit.bp
Labels: area: balance

#4996 Sonar Changes
  units/UAB3102/UAB3102_unit.bp
  units/UAB3202/UAB3202_unit.bp
  units/UEB3102/UEB3102_unit.bp
  units/UEB3202/UEB3202_unit.bp
  units/URB3102/URB3102_unit.bp
  units/URB3202/URB3202_unit.bp
  units/XSB3102/XSB3102_unit.bp
  units/XSB3202/XSB3202_unit.bp
Labels: area: balance

#4989 Shard Adjustment
  units/UAS0102/UAS0102_unit.bp
Labels: area: balance

#4957 T1 & T2 Torp Defence Changes
  units/UAB2109/UAB2109_unit.bp
  units/UAB2205/UAB2205_unit.bp
  units/UEB2109/UEB2109_unit.bp
  units/UEB2205/UEB2205_unit.bp
  units/URB2109/URB2109_unit.bp
  units/URB2205/URB2205_unit.bp
  units/XSB2109/XSB2109_unit.bp
  units/XSB2205/XSB2205_unit.bp
Labels: area: balance

#4799 Modify air elevations
  units/UAA0101/UAA0101_unit.bp
  units/UAA0102/UAA0102_unit.bp
  units/UAA0103/UAA0103_unit.bp
  units/UAA0302/UAA0302_unit.bp
  units/UAA0303/UAA0303_unit.bp
  units/UAA0304/UAA0304_unit.bp
  units/UAA0310/UAA0310_unit.bp
  units/UEA0101/UEA0101_unit.bp
  units/UEA0102/UEA0102_unit.bp
  units/UEA0103/UEA0103_unit.bp
  units/UEA0302/UEA0302_unit.bp
  units/UEA0303/UEA0303_unit.bp
  units/UEA0304/UEA0304_unit.bp
  units/URA0101/URA0101_unit.bp
  units/URA0102/URA0102_unit.bp
  units/URA0103/URA0103_unit.bp
  units/URA0302/URA0302_unit.bp
  units/URA0303/URA0303_unit.bp
  units/URA0304/URA0304_unit.bp
  units/XAA0202/XAA0202_unit.bp
  units/XAA0306/XAA0306_unit.bp
  units/XSA0101/XSA0101_unit.bp
  units/XSA0102/XSA0102_unit.bp
  units/XSA0103/XSA0103_unit.bp
  units/XSA0302/XSA0302_unit.bp
  units/XSA0303/XSA0303_unit.bp
  units/XSA0304/XSA0304_unit.bp
Labels: area: balance

#4705 Adjust reclaim values of mobile units based on tech tier
  lua/sim/Unit.lua
  lua/wreckage.lua
  units/URL0402/URL0402_script.lua
  units/URS0201/URS0201_script.lua
  units/XRL0403/XRL0403_script.lua
Labels: area: balance

#5018 Fix Sonar E Cost Typo
  units/UEB3202/UEB3202_unit.bp
Labels: area: balance

#5007 Mercy Adjustment
  effects/emitters/X1Mercy_cloud_emit.bp
  projectiles/X1Mercy_proj/AIFMiasmaShell01_Albedo.dds
  projectiles/X1Mercy_proj/AIFMiasmaShell01_SpecTeam.dds
  projectiles/X1Mercy_proj/AIFMiasmaShell01_lod0.scm
  projectiles/X1Mercy_proj/AIFMiasmaShell01_normalsTS.dds
  projectiles/X1Mercy_proj/X1Mercy_proj.bp
  projectiles/X1Mercy_proj/X1Mercy_script.lua
  units/DAA0206/DAA0206_unit.bp
Labels: area: balance

#5021 Sanitize LODs of units, props and tarmacs
  lua/defaultunits.lua
  lua/sim/BuilderManager.lua
  lua/sim/PrefetchTemplates.lua
  lua/sim/PrefetchUtilities.lua
  lua/simInit.lua
  lua/system/blueprints-lod.lua
Labels: area: graphics

#4977 Improve the death threads of various experimental units
  engine/Sim.lua
  lua/defaultexplosions.lua
  units/UAL0401/UAL0401_Script.lua
  units/UEL0401/UEL0401_script.lua
  units/URL0402/URL0402_script.lua
  units/XRL0403/XRL0403_script.lua
Labels: area: graphics

#5020 Split Aeon Gun Range Upgrade
  units/UAL0001/UAL0001_script.lua
  units/UAL0001/UAL0001_unit.bp
Labels: area: balance

#5023 No longer disable rendering the navigational mesh as you close the UI
  lua/ui/game/NavGenerator.lua
Labels: area: AI

#5026 Fix air units being stuck on the air staging platform
  lua/aibrains/platoons/platoon-base.lua
  lua/defaultunits.lua
  lua/sim/Unit.lua
Labels: type: bug

#5027 Fix the Quantum Optics of being self conscious
  lua/RemoteViewing.lua
  units/XAB3301/XAB3301_unit.bp
Labels: type: bug

#5022 adds tmd to sera carrier
  units/XSS0303/XSS0303_lod0.scm
  units/XSS0303/XSS0303_script.lua
  units/XSS0303/XSS0303_unit.bp
Labels: area: balance

#5028 Fix Rover drones being untargetable
  lua/terranunits.lua
Labels: type: bug

#5031 Further improve the performance of the navigational mesh
  lua/sim/NavGenerator.lua
Labels: area: AI, area: nav-mesh

#5032 Further improve the performance of the navigational mesh
  lua/sim/NavGenerator.lua
Labels: area: nav-mesh

#5019 Intel Reactivate Time
  units/UAB3101/UAB3101_unit.bp
  units/UAB3102/UAB3102_unit.bp
  units/UAB3104/UAB3104_unit.bp
  units/UAB3201/UAB3201_unit.bp
  units/UAB3202/UAB3202_unit.bp
  units/UAS0305/UAS0305_unit.bp
  units/UEB3101/UEB3101_unit.bp
  units/UEB3102/UEB3102_unit.bp
  units/UEB3104/UEB3104_unit.bp
  units/UEB3201/UEB3201_unit.bp
  units/UEB3202/UEB3202_unit.bp
  units/UES0305/UES0305_unit.bp
  units/URB3101/URB3101_unit.bp
  units/URB3102/URB3102_unit.bp
  units/URB3104/URB3104_unit.bp
  units/URB3201/URB3201_unit.bp
  units/URB3202/URB3202_unit.bp
  units/URS0305/URS0305_unit.bp
  units/XSB3101/XSB3101_unit.bp
  units/XSB3102/XSB3102_unit.bp
  units/XSB3104/XSB3104_unit.bp
  units/XSB3201/XSB3201_unit.bp
  units/XSB3202/XSB3202_unit.bp
Labels: area: balance

#5001 Adds TMD to Aeon Carrier
  units/UAS0303/UAS0303_Albedo.dds
  units/UAS0303/UAS0303_lod0.scm
  units/UAS0303/UAS0303_script.lua
  units/UAS0303/UAS0303_unit.bp
Labels: area: balance

#5034 Apply adjacency buffs to missile being built
  lua/defaultunits.lua
  lua/sim/Unit.lua
Labels: area: sim

#5033 Allow death weapons to knock over trees
  lua/defaultunits.lua
  lua/sim/Unit.lua
  units/UAA0310/UAA0310_script.lua
  units/XSA0402/XSA0402_script.lua
Labels: area: graphics

#5042 Make interceptors and swift winds more flexible
  units/UAA0102/UAA0102_unit.bp
  units/UEA0102/UEA0102_unit.bp
  units/URA0102/URA0102_unit.bp
  units/XAA0202/XAA0202_unit.bp
  units/XSA0102/XSA0102_unit.bp
Labels: area: balance

#5040 Prevent weapon scanning of picking up docked shoulder drones
  units/UEL0001/UEL0001_script.lua
Labels: area: sim

#5037 Strat Bomber Nerf
  units/UAA0304/UAA0304_unit.bp
  units/UEA0304/UEA0304_unit.bp
  units/URA0304/URA0304_unit.bp
  units/XSA0304/XSA0304_unit.bp
Labels: area: balance

#5057 Strat changes
  units/UAA0304/UAA0304_unit.bp
  units/UEA0304/UEA0304_unit.bp
  units/URA0304/URA0304_unit.bp
  units/XSA0304/XSA0304_unit.bp
Labels: area: balance

#5036 Revert Torp Dmg Nerf
  units/UAA0204/UAA0204_unit.bp
  units/UEA0204/UEA0204_unit.bp
  units/URA0204/URA0204_unit.bp
  units/XSA0204/XSA0204_unit.bp
Labels: area: balance

#5059 Sub Hp Buff
  units/UAS0203/UAS0203_unit.bp
  units/UES0203/UES0203_unit.bp
  units/URS0203/URS0203_unit.bp
Labels: area: balance

#4766 Range bot improvements
  units/DEL0204/DEL0204_unit.bp
  units/DRL0204/DRL0204_unit.bp
Labels: area: balance

#4854 Improve the handling of the Tempest
  units/UAS0401/UAS0401_unit.bp
Labels: area: balance

#4434 Uef bubble shield Rework
  units/UEL0001/UEL0001_unit.bp
Labels: area: balance

#5065 Update URA0304_unit.bp
  units/URA0304/URA0304_unit.bp
Labels: area: balance

#5063 Update XRB2309_unit.bp
  units/XRB2309/XRB2309_unit.bp
Labels: area: balance

#5066 Add missing impact effect for Wasp projectiles
  lua/terranprojectiles.lua
Labels: area: graphics

#5074 Cybran T3 sonar buff
  units/URS0305/URS0305_unit.bp
Labels: area: balance

#5068 update IsPlattonDelay logic to work correctly in BuilderManager
  lua/sim/BuilderManager.lua
Labels: area: AI

#5071 disable AI logs and add debug checks for transport logs.
  lua/AI/AIBehaviors.lua
  lua/AI/Transportutilities.lua
  lua/platoon.lua
Labels: area: AI

#5075 Buff Amphib Torps
  units/URL0203/URL0203_unit.bp
  units/XRL0305/XRL0305_unit.bp
  units/XSL0303/XSL0303_unit.bp
Labels: area: balance

#5073 Cybran Acu Changes
  lua/aeonweapons.lua
  lua/sim/weapon.lua
  units/URL0001/URL0001_script.lua
  units/URL0001/URL0001_unit.bp
Labels: area: balance

#5076 fix new aeon upgrade to be removed
  units/UAL0001/UAL0001_unit.bp
Labels: area: balance

#5079 Use alternative unit effect for projectiles of the Wasp
  lua/terranprojectiles.lua
Labels: area: graphics

#4960 Update mod information for FAF
  lua/MODS.LUA
  lua/system/Blueprints.lua
Labels: area: code style

#5077 Update URL0001_unit.bp
  units/URL0001/URL0001_unit.bp
Labels: area: balance

#5084 Add new TransportRequested flag for 3rd party AI compatiblity support.
  lua/AI/AIBaseTemplates/ChallengeMain.lua
  lua/AI/AIBaseTemplates/NormalMain.lua
  lua/AI/AIBuilders/AIAirAttackBuilders.lua
  lua/AI/AIBuilders/AIEconomicBuilders.lua
  lua/AI/AIBuilders/AIFactoryConstructionBuilders.lua
  lua/AI/Transportutilities.lua
  lua/AI/aiattackutilities.lua
  lua/AI/aiutilities.lua
  lua/aibrains/base-ai.lua
  lua/editor/MiscBuildConditions.lua
  lua/platoon.lua
  lua/sim/FactoryBuilderManager.lua
Labels: area: sim, area: AI

#5024 Add various cheat guards for introduced debug functionality
  lua/AI/GridPresence.lua
  lua/AI/GridReclaim.lua
  lua/AI/GridRecon.lua
  lua/SimCallbacks.lua
  lua/aibrains/components/economy.lua
  lua/sim/MapUtilities.lua
  lua/sim/MarkerUtilities.lua
  lua/sim/Profiler.lua
Labels: area: code style, area: AI

#5104 Economy Structures HP Tweaks
  units/UAB1101/UAB1101_unit.bp
  units/UAB1103/UAB1103_unit.bp
  units/UAB1106/UAB1106_unit.bp
  units/UAB1201/UAB1201_unit.bp
  units/UAB1302/UAB1302_unit.bp
  units/UEB1101/UEB1101_unit.bp
  units/UEB1103/UEB1103_unit.bp
  units/UEB1106/UEB1106_unit.bp
  units/UEB1202/UEB1202_unit.bp
  units/UEB1302/UEB1302_unit.bp
  units/URB1103/URB1103_unit.bp
  units/URB1106/URB1106_unit.bp
  units/URB1201/URB1201_unit.bp
  units/URB1302/URB1302_unit.bp
  units/XSB1101/XSB1101_unit.bp
  units/XSB1103/XSB1103_unit.bp
  units/XSB1106/XSB1106_unit.bp
  units/XSB1201/XSB1201_unit.bp
  units/XSB1202/XSB1202_unit.bp
  units/XSB1302/XSB1302_unit.bp
Labels: area: balance

#5107 Fix bug with build drones becoming immobile
  lua/defaultunits.lua
  lua/sim/Unit.lua
  units/UEL0301/UEL0301_script.lua
Labels: type: bug

#5092 Fix an alliance bug with revealing civilians
  lua/sim/ScenarioUtilities.lua
  lua/sim/VizMarker.lua
  units/URS0201/URS0201_script.lua
Labels: type: bug

#5109 Cybran ACU Tweeks
  units/URL0001/URL0001_unit.bp
Labels: area: balance

#5110 Update Naval reclaim
  lua/sim/Unit.lua
Labels: area: balance

#5086 Fix queueing for new Cybran enhancements
  lua/ui/game/construction.lua
  lua/ui/game/layouts/construction_mini.lua
  units/URL0001/URL0001_script.lua
  units/URL0001/URL0001_unit.bp
Labels: area: balance

#5123 Re-introduce the 'OnUnitKilled' callback
  lua/aibrains/base-ai.lua
  lua/defaultcomponents.lua
  lua/sim/ScenarioUtilities.lua
  lua/sim/Unit.lua
Labels: type: bug

#5101 change FactoryFinishBuilding callback to use transportpool flag
  lua/sim/FactoryBuilderManager.lua
Labels: area: AI

#5099 Update base-ai callbacks to reference engineer manager correctly.
  lua/aibrains/base-ai.lua
Labels: area: AI

#5082 Set Salvo Size to 3 across the board
  units/UAA0204/UAA0204_unit.bp
  units/UEA0204/UEA0204_unit.bp
  units/URA0204/URA0204_unit.bp
  units/XAA0306/XAA0306_unit.bp
  units/XSA0204/XSA0204_unit.bp
Labels: area: balance

#5130 Fix a bug with alliances
  lua/aibrains/easy-ai.lua
  lua/sim/ScenarioUtilities.lua
  lua/simInit.lua
Labels: type: bug

#5126 Prevent UI mods from being able to make network changes
  lua/ui/game/gamemain.lua
  lua/ui/override/readme.md
  lua/userInit.lua
Labels: area: ui

#4879 Migrating pathing for default AI to navmesh
  lua/AI/AIBehaviors.lua
  lua/AI/Transportutilities.lua
  lua/AI/aiattackutilities.lua
  lua/AI/aiutilities.lua
  lua/platoon.lua
Labels: area: sim, area: AI

#5131 Fix child projectiles having no launcher
  lua/sim/Projectile.lua
  lua/sim/Unit.lua
Labels: type: bug

#5134 Adjust recall to require the last three players of a team to agree
  lua/shared/RecallParams.lua
Labels: area: sim, area: ui

#5135 Fix a minor security issue
  lua/userInit.lua
Labels: type: bug

#5136 Take into account terrain height for vision markers
  lua/sim/VizMarker.lua
Labels: type: bug

#5141 Fix a bug with expansion markers and marker field names
  lua/sim/MarkerUtilities.lua
  lua/sim/MarkerUtilities/Expansions.lua
Labels: type: bug, area: AI

#5148 Fix a bug with the file picker being case sensitive
  engine/User.lua
  lua/ui/controls/filepicker.lua
Labels: type: bug, area: ui

#5155 Fix various bugs with the release
  lua/aibrain.lua
  lua/aibrains/base-ai.lua
  lua/aibrains/campaign-ai.lua
  lua/simInit.lua
  lua/ui/lobby/lobbyOptions.lua
Labels: type: bug, area: sim

#5158 Properly discard land walking animation of Cybran destroyer
  units/URS0201/URS0201_script.lua
Labels: type: bug

#5159 Disable the rehost functionality
  lua/ui/dialogs/score.lua
  lua/ui/game/tabs.lua
Labels: type: bug

#5154 Cybran and Aeon Upgrades
  lua/ui/help/unitdescription.lua
  textures/ui/common/game/aeon-enhancements/ecba_btn_down.dds
  textures/ui/common/game/aeon-enhancements/ecba_btn_over.dds
  textures/ui/common/game/aeon-enhancements/ecba_btn_sel.dds
  textures/ui/common/game/aeon-enhancements/ecba_btn_up.dds
  units/UAL0001/UAL0001_unit.bp
  units/URL0001/URL0001_unit.bp
Labels: area: balance, area: ui

#5156 Setup for a separate debug window for functions of NavUtils
  lua/SimCallbacks.lua
  lua/keymap/debugKeyActions.lua
  lua/keymap/keydescriptions.lua
  lua/sim/NavDebug.lua
  lua/sim/NavDebug/DirectionsFrom.lua
  lua/sim/NavUtils.lua
  lua/ui/game/NavDebug/DirectionsFrom.lua
Labels: area: ui, area: nav-mesh

#5127 Allow UEF drones reclaim during patrol/attack-move
  units/UEA0001/UEA0001_unit.bp
  units/UEA0003/UEA0003_unit.bp
  units/XEA3204/XEA3204_unit.bp
Labels: area: balance
