Repository FAForever/fa, pull requests merged in 2023-11, with the labels that each got.

#5614 Always store the mapwide albedo texture in the albedo slot
  effects/terrain.fx
Labels: area: code style, area: graphics

#5613 Define GC tractor claw damage in blueprint
  lua/aeonweapons.lua
  units/UAL0401/UAL0401_unit.bp
Labels: area: code style, area: unit-blueprint

#5616 Re-introduce the Seraphim-specific scorch splats
  engine/Core/Blueprints/ProjectileBlueprint.lua
  lua/sim/Projectile.lua
  projectiles/SBOOhwalliStrategicBomb01/SBOOhwalliStrategicBomb01_proj.bp
  projectiles/SBOZhanaseeBomb01/SBOZhanaseeBomb01_proj.bp
  projectiles/SBOZhanaseeBomb01/SBOZhanaseeBomb01_script.lua
Labels: area: graphics

#5617 Add an exception to the roll off point of engineers
  lua/sim/units/FactoryUnit.lua
Labels: feature: roll off behavior

#5615 Show the Backpack on SCU BubbleShield
  units/UEL0301/UEL0301_unit.bp
Labels: area: graphics

#5618 Fix the energy requirements of Overcharge
  units/UAL0001/UAL0001_unit.bp
  units/UEL0001/UEL0001_unit.bp
  units/URL0001/URL0001_unit.bp
  units/XSL0001/XSL0001_unit.bp
Labels: type: bug

#5619 Add missing trail on the AA guns of the Cybran carrier
  projectiles/CAAAutocannon03/CAAAutocannon03_script.lua
Labels: area: graphics

#5620 Mobile factories can now be selected while being constructed again
  units/UAA0310/UAA0310_unit.bp
  units/UAS0401/UAS0401_unit.bp
  units/UEL0401/UEL0401_unit.bp
Labels: area: ui

#5621 Process requests of Relent0r for nav mesh utils
  lua/sim/NavDebug.lua
  lua/sim/NavDebug/DirectionsFrom.lua
  lua/sim/NavUtils.lua
Labels: area: nav-mesh

#5606 Hide collapse buttons on UI hide
  lua/ui/game/massfabs.lua
  lua/ui/game/recall.lua
Labels: type: bug, area: ui

#5626 Fix a bug with the navigational mesh
  lua/sim/NavUtils.lua
Labels: type: bug, area: nav-mesh

#5634 Remove pathing parameters that should not have been merged in
  lua/simInit.lua
Labels: type: bug

#5636 Fix various small bugs
  lua/EffectUtilitiesSeraphim.lua
  lua/EffectUtilitiesUEF.lua
  lua/aeonunits.lua
  lua/sim/Unit.lua
  lua/sim/units/components/TransportUnitComponent.lua
Labels: type: bug

#5635 Fix various issues with tactical missiles
  lua/sim/projectiles/components/TacticalMissileComponent.lua
  units/UAB2108/UAB2108_unit.bp
  units/UEB2108/UEB2108_unit.bp
  units/UES0202/UES0202_unit.bp
  units/URB2108/URB2108_unit.bp
  units/XAS0306/XAS0306_unit.bp
  units/XSB2108/XSB2108_unit.bp
  units/XSS0202/XSS0202_unit.bp
  units/XSS0303/XSS0303_unit.bp
Labels: type: bug, feature: tactical missiles

#5646 Improve code style and add license to basic projectile files
  engine/Sim.lua
  projectiles/AANTorpedoClusterSplit01/AANTorpedoClusterSplit01_script.lua
  projectiles/ADFDisruptor01/ADFDisruptor01_script.lua
  projectiles/ADFGraviton01/ADFGraviton01_script.lua
  projectiles/ADFLaserHeavy01/ADFLaserHeavy01_script.lua
  projectiles/ADFLaserHighIntensity01/ADFLaserHighIntensity01_script.lua
  projectiles/ADFLaserLight01/ADFLaserLight01_script.lua
  projectiles/ADFLaserLight02/ADFLaserLight02_script.lua
  projectiles/ADFOblivionCannon01/ADFOblivionCannon01_script.lua
  projectiles/ADFOblivionCannon02/ADFOblivionCannon02_script.lua
  projectiles/ADFOblivionCannon03/ADFOblivionCannon03_script.lua
  projectiles/ADFOblivionCannon04/ADFOblivionCannon04_script.lua
  projectiles/ADFOblivionCannon05/ADFOblivionCannon05_script.lua
  projectiles/ADFOverCharge01/ADFOverCharge01_script.lua
  projectiles/ADFQuadLaserLight01/ADFQuadLaserLight01_script.lua
  projectiles/ADFQuantumCannon01/ADFQuantumCannon01_script.lua
  projectiles/ADFQuantumDisruptor01/ADFQuantumDisruptor01_script.lua
  projectiles/ADFQuatumAutoGun01/ADFQuatumAutoGun01_script.lua
  projectiles/ADFReactonCannon01/ADFReactonCannon01_script.lua
  projectiles/ADFReactonCannon02/ADFReactonCannon02_script.lua
  projectiles/ADFRocket01/ADFRocket01_Script.lua
  projectiles/ADFShieldDisruptor01/ADFShieldDisruptor01_script.lua
  projectiles/ADFSonicPulsar01/ADFSonicPulsar01_script.lua
  projectiles/AIFBombGraviton01/AIFBombGraviton01_script.lua
  projectiles/AIFBombQuark01/AIFBombQuark01_script.lua
  projectiles/aaphalanx01/AAPhalanx01_script.lua
  projectiles/aaserpentine/AASerpentine_script.lua
Labels: area: code style

#5624 T2 MML Buff
  units/UAL0111/UAL0111_unit.bp
  units/UEL0111/UEL0111_unit.bp
  units/URL0111/URL0111_unit.bp
  units/XSL0111/XSL0111_unit.bp
Labels: area: balance

#5652 Separate aeon projectile classes into separate files
  lua/aeonprojectiles.lua
  lua/sim/projectiles/aeon/AAALightDisplacementAutocannonMissileProjectile.lua
  lua/sim/projectiles/aeon/AAAQuantumDisplacementCannonProjectile.lua
  lua/sim/projectiles/aeon/AArtilleryFragmentationSensorShellProjectile.lua
  lua/sim/projectiles/aeon/AArtilleryFragmentationSensorShellProjectile02.lua
  lua/sim/projectiles/aeon/AArtilleryFragmentationSensorShellProjectile03.lua
  lua/sim/projectiles/aeon/AArtilleryProjectile.lua
  lua/sim/projectiles/aeon/ABaseTempProjectile.lua
  lua/sim/projectiles/aeon/ABeamProjectile.lua
  lua/sim/projectiles/aeon/ACannonSeaProjectile.lua
  lua/sim/projectiles/aeon/ACannonTankProjectile.lua
  lua/sim/projectiles/aeon/ADepthChargeProjectile.lua
  lua/sim/projectiles/aeon/ADisruptorProjectile.lua
  lua/sim/projectiles/aeon/AGravitonBombProjectile.lua
  lua/sim/projectiles/aeon/AGravitonProjectile.lua
  lua/sim/projectiles/aeon/AGuidedMissileProjectile.lua
  lua/sim/projectiles/aeon/AHeavyDisruptorCannonShell.lua
  lua/sim/projectiles/aeon/AHighIntensityLaserProjectile.lua
  lua/sim/projectiles/aeon/AIFBallisticMortarProjectile.lua
  lua/sim/projectiles/aeon/AIFBallisticMortarProjectile02.lua
  lua/sim/projectiles/aeon/AIMFlareProjectile.lua
  lua/sim/projectiles/aeon/ALaserBotProjectile.lua
  lua/sim/projectiles/aeon/ALaserProjectile.lua
  lua/sim/projectiles/aeon/ALightLaserProjectile.lua
  lua/sim/projectiles/aeon/AMiasmaProjectile.lua
  lua/sim/projectiles/aeon/AMiasmaProjectile02.lua
  lua/sim/projectiles/aeon/AMissileAAProjectile.lua
  lua/sim/projectiles/aeon/AMissileCruiseSubProjectile.lua
  lua/sim/projectiles/aeon/AMissileSerpentineProjectile.lua
  lua/sim/projectiles/aeon/AOblivionCannonProjectile.lua
  lua/sim/projectiles/aeon/AOblivionCannonProjectile02.lua
  lua/sim/projectiles/aeon/AOblivionCannonProjectile03.lua
  lua/sim/projectiles/aeon/AQuadLightLaserProjectile.lua
  lua/sim/projectiles/aeon/AQuantumAutogun.lua
  lua/sim/projectiles/aeon/AQuantumCannonProjectile.lua
  lua/sim/projectiles/aeon/AQuantumCluster.lua
  lua/sim/projectiles/aeon/AQuantumDisruptorProjectile.lua
  lua/sim/projectiles/aeon/AQuantumWarheadProjectile.lua
  lua/sim/projectiles/aeon/AQuarkBombProjectile.lua
  lua/sim/projectiles/aeon/ARailGunProjectile.lua
  lua/sim/projectiles/aeon/AReactonCannonAOEProjectile.lua
  lua/sim/projectiles/aeon/AReactonCannonProjectile.lua
  lua/sim/projectiles/aeon/ARocketProjectile.lua
  lua/sim/projectiles/aeon/ASaintAntiNukeProjectile.lua
  lua/sim/projectiles/aeon/AShieldDisruptorProjectile.lua
  lua/sim/projectiles/aeon/ASonicPulsarProjectile.lua
  lua/sim/projectiles/aeon/ASonicPulseProjectile.lua
  lua/sim/projectiles/aeon/ASonicPulseProjectile02.lua
  lua/sim/projectiles/aeon/ATemporalFizzAAProjectile.lua
  lua/sim/projectiles/aeon/ATorpedoCluster.lua
  lua/sim/projectiles/aeon/ATorpedoShipProjectile.lua
  lua/sim/projectiles/aeon/ATorpedoSubProjectile.lua
  lua/sim/projectiles/aeon/AZealot02AAMissileProjectile.lua
  lua/sim/projectiles/aeon/QuasarAntiTorpedoChargeSubProjectile.lua
Labels: area: code style

#5632 Top bombers Drops more projectiles
  units/UAA0204/UAA0204_unit.bp
  units/UEA0204/UEA0204_unit.bp
  units/URA0204/URA0204_unit.bp
  units/XSA0204/XSA0204_unit.bp
Labels: area: balance

#5654 Water improvement
  effects/mesh.fx
  effects/terrain.fx
  effects/water2.fx
Labels: area: graphics

#5650 Rebalance UEF Bubble shield
  units/UEL0001/UEL0001_unit.bp
Labels: area: balance

#5653 Transport Quick Drop
  lua/sim/units/AirTransportUnit.lua
  units/UAA0104/UAA0104_unit.bp
  units/UAA0107/UAA0107_unit.bp
  units/UEA0104/UEA0104_unit.bp
  units/UEA0107/UEA0107_unit.bp
  units/URA0104/URA0104_unit.bp
  units/URA0107/URA0107_unit.bp
  units/XEA0306/XEA0306_unit.bp
  units/XSA0104/XSA0104_unit.bp
  units/XSA0107/XSA0107_unit.bp
Labels: feature: transports, feature: unit navigator

#5655 Add the ability to abort the navigation of engineers
  lua/SimCallbacks.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  lua/keymap/misckeyactions.lua
  lua/sim/commands/abort-navigation.lua
Labels: feature: hotkeys, feature: interrupt pathfinding

#5660 Fix various bugs
  lua/aeonunits.lua
  lua/defaultcomponents.lua
  lua/sim/NavUtils.lua
  lua/sim/Projectile.lua
  lua/sim/Unit.lua
  lua/sim/weapon.lua
  lua/terranunits.lua
  units/ZEB9602/ZEB9602_script.lua
Labels: type: bug

#5651 Move UEF Tellie Upgrade
  units/UEL0001/UEL0001_unit.bp
Labels: area: balance

#5661 Increase Mercy damage
  units/DAA0206/DAA0206_unit.bp
Labels: area: balance

#5631 Naval BT Changes
  units/UAB0203/UAB0203_unit.bp
  units/UAB0303/UAB0303_unit.bp
  units/UEB0203/UEB0203_unit.bp
  units/UEB0303/UEB0303_unit.bp
  units/URB0203/URB0203_unit.bp
  units/URB0303/URB0303_unit.bp
  units/XSB0203/XSB0203_unit.bp
  units/XSB0303/XSB0303_unit.bp
  units/ZAB9503/ZAB9503_unit.bp
  units/ZAB9603/ZAB9603_unit.bp
  units/ZEB9503/ZEB9503_unit.bp
  units/ZEB9603/ZEB9603_unit.bp
  units/ZRB9503/ZRB9503_unit.bp
  units/ZRB9603/ZRB9603_unit.bp
  units/ZSB9503/ZSB9503_unit.bp
  units/ZSB9603/ZSB9603_unit.bp
Labels: area: balance

#5630 Adjust the build times of air factories
  units/UAB0302/UAB0302_unit.bp
  units/UEB0302/UEB0302_unit.bp
  units/URB0302/URB0302_unit.bp
  units/XSB0302/XSB0302_unit.bp
  units/ZAB9502/ZAB9502_unit.bp
  units/ZAB9602/ZAB9602_unit.bp
  units/ZEB9502/ZEB9502_unit.bp
  units/ZEB9602/ZEB9602_unit.bp
  units/ZRB9502/ZRB9502_unit.bp
  units/ZRB9602/ZRB9602_unit.bp
  units/ZSB9502/ZSB9502_unit.bp
  units/ZSB9602/ZSB9602_unit.bp
Labels: area: balance

#5629 Land Factory BT Changes (Balance) / Fix BP Formating
  units/UAB0301/UAB0301_unit.bp
  units/UEB0301/UEB0301_unit.bp
  units/URB0301/URB0301_unit.bp
  units/XSB0301/XSB0301_unit.bp
  units/ZAB9501/ZAB9501_unit.bp
  units/ZAB9601/ZAB9601_unit.bp
  units/ZEB9501/ZEB9501_unit.bp
  units/ZEB9601/ZEB9601_unit.bp
  units/ZRB9501/ZRB9501_unit.bp
  units/ZRB9601/ZRB9601_unit.bp
  units/ZSB9501/ZSB9501_unit.bp
  units/ZSB9601/ZSB9601_unit.bp
Labels: area: balance, area: code style

#5662 Reduce the T3 pgen adjacency
  lua/sim/AdjacencyBuffs.lua
Labels: area: balance

#5649 More Code Annotation Fixes
  lua/AIChatSorian.lua
  lua/EffectUtilities.lua
  lua/EffectUtilitiesAeon.lua
  lua/EffectUtilitiesGeneric.lua
  lua/aeonprojectiles.lua
  lua/aeonunits.lua
  lua/aeonweapons.lua
  lua/aibrain.lua
  lua/cybranprojectiles.lua
  lua/cybranunits.lua
  lua/cybranweapons.lua
  lua/defaultcollisionbeams.lua
  lua/defaultcomponents.lua
  lua/defaultexplosions.lua
  lua/sim/Unit.lua
  lua/sim/units/StructureUnit.lua
Labels: area: code style

#5623 UnitBluprintAnnotation Work
  engine/Core/Blueprints/UnitBlueprint.lua
Labels: area: code style

#5665 Move classes of UEF weapons to separate files
  lua/sim/defaultweapons.lua
  lua/sim/weapons/uef/TAAFlakArtilleryCannon.lua
  lua/sim/weapons/uef/TAAGinsuRapidPulseWeapon.lua
  lua/sim/weapons/uef/TAALinkedRailgun.lua
  lua/sim/weapons/uef/TAMInterceptorWeapon.lua
  lua/sim/weapons/uef/TAMPhalanxWeapon.lua
  lua/sim/weapons/uef/TANTorpedoAngler.lua
  lua/sim/weapons/uef/TANTorpedoLandWeapon.lua
  lua/sim/weapons/uef/TAirToAirLinkedRailgun.lua
  lua/sim/weapons/uef/TDFFragmentationGrenadeLauncherWeapon.lua
  lua/sim/weapons/uef/TDFGaussCannonWeapon.lua
  lua/sim/weapons/uef/TDFHeavyPlasmaCannonWeapon.lua
  lua/sim/weapons/uef/TDFHeavyPlasmaGatlingCannonWeapon.lua
  lua/sim/weapons/uef/TDFHeavyPlasmaGatlingWeapon.lua
  lua/sim/weapons/uef/TDFHiroPlasmaCannon.lua
  lua/sim/weapons/uef/TDFIonizedPlasmaCannon.lua
  lua/sim/weapons/uef/TDFLandGaussCannonWeapon.lua
  lua/sim/weapons/uef/TDFLightPlasmaCannonWeapon.lua
  lua/sim/weapons/uef/TDFMachineGunWeapon.lua
  lua/sim/weapons/uef/TDFOverchargeWeapon.lua
  lua/sim/weapons/uef/TDFPlasmaCannonWeapon.lua
  lua/sim/weapons/uef/TDFRiotWeapon.lua
  lua/sim/weapons/uef/TDFShipGaussCannonWeapon.lua
  lua/sim/weapons/uef/TDFZephyrCannonWeapon.lua
  lua/sim/weapons/uef/TIFArtilleryWeapon.lua
  lua/sim/weapons/uef/TIFCarpetBombWeapon.lua
  lua/sim/weapons/uef/TIFCruiseMissileLauncher.lua
  lua/sim/weapons/uef/TIFCruiseMissileLauncherSub.lua
  lua/sim/weapons/uef/TIFCruiseMissileUnpackingLauncher.lua
  lua/sim/weapons/uef/TIFFragLauncherWeapon.lua
  lua/sim/weapons/uef/TIFHighBallisticMortarWeapon.lua
  lua/sim/weapons/uef/TIFSmallYieldNuclearBombWeapon.lua
  lua/sim/weapons/uef/TIFSmartCharge.lua
  lua/sim/weapons/uef/TIFStrategicMissileWeapon.lua
  lua/sim/weapons/uef/TOrbitalDeathLaserBeamWeapon.lua
  lua/sim/weapons/uef/TSAMLauncher.lua
  lua/terranweapons.lua
Labels: area: code style

#5673 Create Individual Unit Files for UEF Unit Classes
  lua/sim/Unit.lua
  lua/sim/units/ConstructionUnit.lua
  lua/sim/units/StructureUnit.lua
  lua/sim/units/uef/TAirFactoryUnit.lua
  lua/sim/units/uef/TAirStagingPlatformUnit.lua
  lua/sim/units/uef/TAirUnit.lua
  lua/sim/units/uef/TCivilianStructureUnit.lua
  lua/sim/units/uef/TConcreteStructureUnit.lua
  lua/sim/units/uef/TConstructionUnit.lua
  lua/sim/units/uef/TEnergyCreationUnit.lua
  lua/sim/units/uef/TEnergyStorageUnit.lua
  lua/sim/units/uef/THoverLandUnit.lua
  lua/sim/units/uef/TLandFactoryUnit.lua
  lua/sim/units/uef/TLandUnit.lua
  lua/sim/units/uef/TMassCollectionUnit.lua
  lua/sim/units/uef/TMassFabricationUnit.lua
  lua/sim/units/uef/TMassStorageUnit.lua
  lua/sim/units/uef/TMobileFactoryUnit.lua
  lua/sim/units/uef/TPodTowerUnit.lua
  lua/sim/units/uef/TQuantumGateUnit.lua
  lua/sim/units/uef/TRadarJammerUnit.lua
  lua/sim/units/uef/TRadarUnit.lua
  lua/sim/units/uef/TSeaFactoryUnit.lua
  lua/sim/units/uef/TSeaUnit.lua
  lua/sim/units/uef/TShieldLandUnit.lua
  lua/sim/units/uef/TShieldSeaUnit.lua
  lua/sim/units/uef/TShieldStructureUnit.lua
  lua/sim/units/uef/TSonarUnit.lua
  lua/sim/units/uef/TStructureUnit.lua
  lua/sim/units/uef/TSubUnit.lua
  lua/sim/units/uef/TTransportBeaconUnit.lua
  lua/sim/units/uef/TWalkingLandUnit.lua
  lua/sim/units/uef/TWallStructureUnit.lua
  lua/terranunits.lua
Labels: area: code style

#5678 Small Revert of the UEF Teleport
  units/UEL0001/UEL0001_unit.bp
Labels: area: balance

#5682 Apply primary damage of the Ahwassa after 2.5 seconds
  effects/Entities/SBOOhwalliBombEffectController01/SBOOhwalliBombEffectController01_proj.bp
  projectiles/SBOOhwalliStrategicBomb01/SBOOhwalliStrategicBomb01_proj.bp
  projectiles/SBOOhwalliStrategicBomb01/SBOOhwalliStrategicBomb01_script.lua
Labels: area: balance

#5684 Category fix for Sera cruiser and carrier
  units/XSS0202/XSS0202_unit.bp
  units/XSS0303/XSS0303_unit.bp
Labels: area: AI

#5681 Improve upon the Mercy effects
  effects/emitters/_Mercy_Circle_1.bp
  effects/emitters/_Mercy_Circle_2.bp
  effects/emitters/_Mercy_Fog.bp
  effects/emitters/_Mercy_distort.bp
  effects/emitters/_Mercy_sparkle.bp
  effects/emitters/_Mercy_sparkle_2.bp
  effects/emitters/_Mercy_spin_1.bp
  effects/emitters/_Mercy_spin_2.4.bp
  effects/emitters/_Mercy_spin_3.4.bp
  effects/emitters/_Mercy_spin_4.4.bp
  effects/emitters/_Mercy_tower_1.bp
  projectiles/AIFGuidedMissile01/AIFGuidedMissile01_Script.lua
  projectiles/AIFGuidedMissile02/AIFGuidedMissile02_Script.lua
  projectiles/AIFGuidedMissile02/AIFGuidedMissile02_proj.bp
Labels: area: graphics

#5674 Introduce separate files for Seraphim unit classes
  lua/EffectUtilitiesSeraphim.lua
  lua/seraphimunits.lua
  lua/sim/Unit.lua
  lua/sim/units/ConstructionUnit.lua
  lua/sim/units/FactoryUnit.lua
  lua/sim/units/seraphim/SAirFactoryUnit.lua
  lua/sim/units/seraphim/SAirStagingPlatformUnit.lua
  lua/sim/units/seraphim/SAirUnit.lua
  lua/sim/units/seraphim/SCivilianStructureUnit.lua
  lua/sim/units/seraphim/SConcreteStructureUnit.lua
  lua/sim/units/seraphim/SConstructionUnit.lua
  lua/sim/units/seraphim/SEnergyBallUnit.lua
  lua/sim/units/seraphim/SEnergyCreationUnit.lua
  lua/sim/units/seraphim/SEnergyStorageUnit.lua
  lua/sim/units/seraphim/SFactoryUnit.lua
  lua/sim/units/seraphim/SHoverLandUnit.lua
  lua/sim/units/seraphim/SLandFactoryUnit.lua
  lua/sim/units/seraphim/SLandUnit.lua
  lua/sim/units/seraphim/SMassCollectionUnit.lua
  lua/sim/units/seraphim/SMassFabricationUnit.lua
  lua/sim/units/seraphim/SMassStorageUnit.lua
  lua/sim/units/seraphim/SQuantumGateUnit.lua
  lua/sim/units/seraphim/SRadarJammerUnit.lua
  lua/sim/units/seraphim/SRadarUnit.lua
  lua/sim/units/seraphim/SSeaFactoryUnit.lua
  lua/sim/units/seraphim/SSeaUnit.lua
  lua/sim/units/seraphim/SShieldHoverLandUnit.lua
  lua/sim/units/seraphim/SShieldLandUnit.lua
  lua/sim/units/seraphim/SShieldStructureUnit.lua
  lua/sim/units/seraphim/SSonarUnit.lua
  lua/sim/units/seraphim/SStructureUnit.lua
  lua/sim/units/seraphim/SSubUnit.lua
  lua/sim/units/seraphim/STransportBeaconUnit.lua
  lua/sim/units/seraphim/SWalkingLandUnit.lua
  lua/sim/units/seraphim/SWallStructureUnit.lua
Labels: area: code style

#5689 Improve performance of the FactoryUnit class
  lua/aibrain.lua
  lua/sim/Unit.lua
  lua/sim/units/FactoryUnit.lua
  lua/sim/units/StructureUnit.lua
  units/URB0101/URB0101_unit.bp
Labels: area: code style

#5693 Sera MML Range Fix
  units/XSL0111/XSL0111_unit.bp
Labels: type: bug

#5700 UI Pulse rework - make it resilient to low framerate.
  lua/maui/effecthelpers.lua
Labels: area: ui

#5698 Score graph start end fix
  lua/sim/score.lua
  lua/ui/dialogs/hotstats.lua
Labels: area: ui

#5695 Unit rework - Janus DEA0202
  units/DEA0202/DEA0202_Script.lua
  units/DEA0202/DEA0202_SpecTeam.dds
  units/DEA0202/DEA0202_lod0.scm
  units/DEA0202/DEA0202_normalsTS.dds
  units/DEA0202/DEA0202_unit.bp
Labels: area: unit-blueprint, area: graphics, area: pbr

#5705 Fix bugs and improve effects of Aeon TMDs
  effects/emitters/aeon_volcano_beam_01.bp
  effects/emitters/aeon_volcano_beam_02.bp
  effects/emitters/aeon_volcano_beam_03.bp
  engine/Core.lua
  lua/EffectTemplates.lua
  lua/defaultantiprojectile.lua
  lua/sim/Projectile.lua
  lua/sim/projectiles/aeon/AIMFlareProjectile.lua
  projectiles/AIMAntiMissile01/AIMAntiMissile01_proj.bp
  projectiles/AIMAntiMissile01/AIMAntiMissile01_script.lua
  units/UAA0107/UAA0107_unit.bp
  units/UAB4201/UAB4201_unit.bp
  units/UAS0202/UAS0202_unit.bp
  units/UAS0302/UAS0302_unit.bp
  units/UAS0303/UAS0303_unit.bp
Labels: area: graphics, feature: tactical missiles, feature: anti projectile weaponry

#5704 Increase the Chariot's hitbox to fix interceptors missing it
  units/UAA0107/UAA0107_unit.bp
Labels: feature: target bones

#5706 Fix various bugs
  effects/emitters/riot_gun_polytrail_01_emit.bp
  effects/emitters/riot_gun_polytrail_02_emit.bp
  effects/emitters/riot_gun_polytrail_03_emit.bp
  lua/sim/units/AirTransportUnit.lua
  lua/system/Blueprints.lua
  projectiles/SBOOhwalliStrategicBomb01/SBOOhwalliStrategicBomb01_script.lua
  units/UAA0203/UAA0203_unit.bp
  units/UAB1103/UAB1103_unit.bp
  units/UAB1202/UAB1202_unit.bp
  units/UAB1302/UAB1302_unit.bp
  units/UEA0104/UEA0104_unit.bp
  units/UEA0203/UEA0203_unit.bp
  units/UEA0305/UEA0305_unit.bp
  units/UEB1103/UEB1103_unit.bp
  units/UEB1202/UEB1202_unit.bp
  units/UEB1302/UEB1302_unit.bp
  units/UEL0203/UEL0203_unit.bp
  units/UEL0401/UEL0401_unit.bp
  units/URA0203/URA0203_unit.bp
  units/URA0401/URA0401_unit.bp
  units/URB1103/URB1103_unit.bp
  units/URB1202/URB1202_unit.bp
  units/URB1302/URB1302_unit.bp
  units/XAA0305/XAA0305_unit.bp
  units/XEL0209/XEL0209_unit.bp
  units/XRA0105/XRA0105_unit.bp
  units/XRA0305/XRA0305_unit.bp
  units/XSA0203/XSA0203_unit.bp
  units/XSB1103/XSB1103_unit.bp
  units/XSB1202/XSB1202_unit.bp
  units/XSB1302/XSB1302_unit.bp
Labels: type: bug

#5703 UI - score graph player highlight, try #2
  lua/sim/score.lua
  lua/ui/dialogs/hotstats.lua
Labels: area: ui

#5640 Normalize air factory roll off times
  lua/seraphimunits.lua
  lua/sim/units/seraphim/SAirFactoryUnit.lua
  units/UAB0102/UAB0102_unit.bp
  units/UAB0202/UAB0202_unit.bp
  units/UAB0302/UAB0302_unit.bp
  units/XSB0102/XSB0102_unit.bp
  units/XSB0202/XSB0202_unit.bp
  units/XSB0302/XSB0302_unit.bp
  units/ZAB9502/ZAB9502_unit.bp
  units/ZAB9602/ZAB9602_unit.bp
  units/ZEB9502/ZEB9502_unit.bp
  units/ZEB9602/ZEB9602_unit.bp
  units/ZRB9502/ZRB9502_unit.bp
  units/ZRB9602/ZRB9602_unit.bp
  units/ZSB9502/ZSB9502_unit.bp
  units/ZSB9602/ZSB9602_unit.bp
Labels: area: balance

#5709 Fix anti-projectile weapons being disabled forever
  lua/sim/Projectile.lua
  lua/sim/defaultweapons.lua
Labels: feature: anti projectile weaponry
