Repository FAForever/fa, pull requests merged in 2024-04, with the labels that each got.

#6040 Re-Open "Make veterancy requirements equal for presets and SACUs
  changelog/3807.md
  lua/system/Blueprints.lua
  lua/ui/game/unitview.lua
Labels: area: balance

#6044 Fix custom data in game.prefs breaking Notify management window
  changelog/3807.md
  lua/ui/notify/customiser.lua
Labels: area: ui

#6036 Improve the 'tread texture'of the Ythotha
  changelog/3807.md
  engine/Sim/Unit.lua
  env/Common/splats/ythotha_tread_left_01.dds
  env/Common/splats/ythotha_tread_right_01.dds
  lua/sim/Unit.lua
  units/UAL0401/UAL0401_unit.bp
  units/URL0401/URL0401_unit.bp
  units/XSL0401/XSL0401_unit.bp
Labels: area: graphics

#6049 Implement a basic area reclaim command
  engine/Sim.lua
  lua/SimCallbacks.lua
  lua/proptree.lua
  lua/sim/commands/area-reclaim-order.lua
  lua/ui/game/commandmode.lua
Labels: area: sim

#6025 Reduce overhead of unit base classes
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/sim/TerrainUtils.lua
  lua/sim/Unit.lua
  lua/sim/units/AirUnit.lua
  lua/sim/units/ConstructionUnit.lua
  lua/sim/units/MassCollectionUnit.lua
  lua/sim/units/MassFabricationUnit.lua
  lua/sim/units/RadarUnit.lua
  lua/sim/units/SeaFactoryUnit.lua
  lua/sim/units/SeaUnit.lua
  lua/sim/units/SlowAmphibiousLandUnit.lua
  lua/sim/units/StructureUnit.lua
  lua/sim/units/SubUnit.lua
Labels: area: sim

#6046 AI-Fix add t2 static artillery threat fix
  changelog/3807.md
  changelog/3809.md
  lua/system/blueprints-ai.lua
Labels: area: AI

#5895 Nerf the Sera T3 Subhunter and make larger formations of it less oppressive
  units/XSS0304/XSS0304_unit.bp
Labels: area: balance, DO NOT MERGE

#5668 Move classes of Seraphim weapons to separate files
  lua/seraphimweapons.lua
  lua/sim/weapons/seraphim/SAALosaareAutoCannonWeapon.lua
  lua/sim/weapons/seraphim/SAALosaareAutoCannonWeaponAirUnit.lua
  lua/sim/weapons/seraphim/SAALosaareAutoCannonWeaponSeaUnit.lua
  lua/sim/weapons/seraphim/SAAOlarisCannonWeapon.lua
  lua/sim/weapons/seraphim/SAAShleoCannonWeapon.lua
  lua/sim/weapons/seraphim/SAMElectrumMissileDefense.lua
  lua/sim/weapons/seraphim/SANAnaitTorpedo.lua
  lua/sim/weapons/seraphim/SANHeavyCavitationTorpedo.lua
  lua/sim/weapons/seraphim/SANHeavyCavitationTorpedo02.lua
  lua/sim/weapons/seraphim/SANUallCavitationTorpedo.lua
  lua/sim/weapons/seraphim/SB0OhwalliExperimentalStrategicBombWeapon.lua
  lua/sim/weapons/seraphim/SDFAireauBolterWeapon.lua
  lua/sim/weapons/seraphim/SDFAireauBolterWeapon02.lua
  lua/sim/weapons/seraphim/SDFAireauWeapon.lua
  lua/sim/weapons/seraphim/SDFAjelluAntiTorpedoDefense.lua
  lua/sim/weapons/seraphim/SDFBombOtheWeapon.lua
  lua/sim/weapons/seraphim/SDFChronotronCannonOverChargeWeapon.lua
  lua/sim/weapons/seraphim/SDFChronotronCannonWeapon.lua
  lua/sim/weapons/seraphim/SDFExperimentalPhasonLaser.lua
  lua/sim/weapons/seraphim/SDFExperimentalPhasonProj.lua
  lua/sim/weapons/seraphim/SDFHeavyPhasicAutoGunTankWeapon.lua
  lua/sim/weapons/seraphim/SDFHeavyPhasicAutoGunWeapon.lua
  lua/sim/weapons/seraphim/SDFHeavyQuarnonCannon.lua
  lua/sim/weapons/seraphim/SDFLightChronotronCannonOverchargeWeapon.lua
  lua/sim/weapons/seraphim/SDFLightChronotronCannonWeapon.lua
  lua/sim/weapons/seraphim/SDFOhCannon.lua
  lua/sim/weapons/seraphim/SDFOhCannon02.lua
  lua/sim/weapons/seraphim/SDFPhasicAutoGunWeapon.lua
  lua/sim/weapons/seraphim/SDFShriekerCannon.lua
  lua/sim/weapons/seraphim/SDFSinnuntheWeapon.lua
  lua/sim/weapons/seraphim/SDFSniperShotNormalMode.lua
  lua/sim/weapons/seraphim/SDFSniperShotSniperMode.lua
  lua/sim/weapons/seraphim/SDFThauCannon.lua
  lua/sim/weapons/seraphim/SDFUltraChromaticBeamGenerator.lua
  lua/sim/weapons/seraphim/SDFUltraChromaticBeamGenerator02.lua
  lua/sim/weapons/seraphim/SDFUnstablePhasonBeam.lua
  lua/sim/weapons/seraphim/SExperimentalStrategicMissileWeapon.lua
  lua/sim/weapons/seraphim/SIFBombZhanaseeWeapon.lua
  lua/sim/weapons/seraphim/SIFExperimentalStrategicMissile.lua
  lua/sim/weapons/seraphim/SIFHuAntiNukeWeapon.lua
  lua/sim/weapons/seraphim/SIFInainoWeapon.lua
  lua/sim/weapons/seraphim/SIFLaanseTacticalMissileLauncher.lua
  lua/sim/weapons/seraphim/SIFSuthanusArtilleryCannon.lua
  lua/sim/weapons/seraphim/SIFSuthanusMobileArtilleryCannon.lua
  lua/sim/weapons/seraphim/SIFThunthoCannonWeapon.lua
  lua/sim/weapons/seraphim/SIFZthuthaamArtilleryCannon.lua
  lua/sim/weapons/seraphim/SLaanseMissileWeapon.lua
Labels: area: code style

#5874 Various navy tweaks to make the Tech 2 stage more interesting
  units/URS0201/URS0201_unit.bp
  units/XES0102/XES0102_unit.bp
  units/XSS0201/XSS0201_unit.bp
Labels: area: balance, DO NOT MERGE

#6067 Remove usage of `repr` in production code
  changelog/3809.md
  lua/AI/AIAddBuilderTable.lua
  lua/AI/AttackManager.lua
  lua/AI/OpAI/BaseManager.lua
  lua/AI/OpAI/OpBehaviors.lua
  lua/AI/Transportutilities.lua
  lua/AI/aiarchetype-managerloader.lua
  lua/AI/aibuildstructures.lua
  lua/AI/aibuildunits.lua
  lua/ScenarioPlatoonAI.lua
  lua/SimCallbacks.lua
  lua/SimCamera.lua
  lua/SimDialogue.lua
  lua/SinglePlayerLaunch.lua
  lua/UserMusic.lua
  lua/aibrain.lua
  lua/aibrains/adaptive-ai.lua
  lua/aibrains/base-ai.lua
  lua/aibrains/campaign-ai.lua
  lua/aibrains/medium-ai.lua
  lua/aibrains/platoons/platoon-adaptive-raid.lua
  lua/aibrains/platoons/platoon-adaptive-reclaim.lua
  lua/aibrains/platoons/platoon-simple-engineer.lua
  lua/aibrains/rush-ai.lua
  lua/aibrains/tech-ai.lua
  lua/aibrains/turtle-ai.lua
  lua/debug/EngineStats.lua
  lua/editor/UnitCountBuildConditions.lua
  lua/formations.lua
  lua/platoon.lua
  lua/shared/aichunktemplates.lua
  lua/shield.lua
  lua/sim/BuilderManager.lua
  lua/sim/ScenarioUtilities.lua
  lua/system/repr.lua
  lua/weather.lua
  units/UEL0307/UEL0307_script.lua
Labels: area: sim, area: AI

#6066 Document classes and remove unused snippets of code
  changelog/3809.md
  lua/sim/weapons/seraphim/SAALosaareAutoCannonWeapon.lua
  lua/sim/weapons/seraphim/SAALosaareAutoCannonWeaponAirUnit.lua
  lua/sim/weapons/seraphim/SAALosaareAutoCannonWeaponSeaUnit.lua
  lua/sim/weapons/seraphim/SAAOlarisCannonWeapon.lua
  lua/sim/weapons/seraphim/SAAShleoCannonWeapon.lua
  lua/sim/weapons/seraphim/SAMElectrumMissileDefense.lua
  lua/sim/weapons/seraphim/SANAnaitTorpedo.lua
  lua/sim/weapons/seraphim/SANHeavyCavitationTorpedo.lua
  lua/sim/weapons/seraphim/SANHeavyCavitationTorpedo02.lua
  lua/sim/weapons/seraphim/SANUallCavitationTorpedo.lua
  lua/sim/weapons/seraphim/SB0OhwalliExperimentalStrategicBombWeapon.lua
  lua/sim/weapons/seraphim/SDFAireauBolterWeapon.lua
  lua/sim/weapons/seraphim/SDFAireauBolterWeapon02.lua
  lua/sim/weapons/seraphim/SDFAireauWeapon.lua
  lua/sim/weapons/seraphim/SDFAjelluAntiTorpedoDefense.lua
  lua/sim/weapons/seraphim/SDFBombOtheWeapon.lua
  lua/sim/weapons/seraphim/SDFChronotronCannonOverChargeWeapon.lua
  lua/sim/weapons/seraphim/SDFChronotronCannonWeapon.lua
  lua/sim/weapons/seraphim/SDFExperimentalPhasonLaser.lua
  lua/sim/weapons/seraphim/SDFExperimentalPhasonProj.lua
  lua/sim/weapons/seraphim/SDFHeavyPhasicAutoGunTankWeapon.lua
  lua/sim/weapons/seraphim/SDFHeavyPhasicAutoGunWeapon.lua
  lua/sim/weapons/seraphim/SDFHeavyQuarnonCannon.lua
  lua/sim/weapons/seraphim/SDFLightChronotronCannonOverchargeWeapon.lua
  lua/sim/weapons/seraphim/SDFOhCannon.lua
  lua/sim/weapons/seraphim/SDFOhCannon02.lua
  lua/sim/weapons/seraphim/SDFPhasicAutoGunWeapon.lua
  lua/sim/weapons/seraphim/SDFShriekerCannon.lua
  lua/sim/weapons/seraphim/SDFSinnuntheWeapon.lua
  lua/sim/weapons/seraphim/SDFSniperShotNormalMode.lua
  lua/sim/weapons/seraphim/SDFSniperShotSniperMode.lua
  lua/sim/weapons/seraphim/SDFThauCannon.lua
  lua/sim/weapons/seraphim/SDFUltraChromaticBeamGenerator.lua
  lua/sim/weapons/seraphim/SDFUnstablePhasonBeam.lua
  lua/sim/weapons/seraphim/SExperimentalStrategicMissileWeapon.lua
  lua/sim/weapons/seraphim/SIFBombZhanaseeWeapon.lua
  lua/sim/weapons/seraphim/SIFExperimentalStrategicMissile.lua
  lua/sim/weapons/seraphim/SIFHuAntiNukeWeapon.lua
  lua/sim/weapons/seraphim/SIFInainoWeapon.lua
  lua/sim/weapons/seraphim/SIFLaanseTacticalMissileLauncher.lua
  lua/sim/weapons/seraphim/SIFSuthanusArtilleryCannon.lua
  lua/sim/weapons/seraphim/SIFSuthanusMobileArtilleryCannon.lua
  lua/sim/weapons/seraphim/SIFThunthoCannonWeapon.lua
  lua/sim/weapons/seraphim/SIFZthuthaamArtilleryCannon.lua
  lua/sim/weapons/seraphim/SLaanseMissileWeapon.lua
Labels: area: code style

#5901 Buff UEF T3 MAA
  changelog/3809.md
  units/DALK003/DALK003_unit.bp
  units/DELK002/DELK002_unit.bp
Labels: area: balance, DO NOT MERGE

#6043 Evaluate the economy values of all Radars and Sonars
  changelog/3809.md
  units/UAB3101/UAB3101_unit.bp
  units/UAB3102/UAB3102_unit.bp
  units/UAB3104/UAB3104_unit.bp
  units/UAB3201/UAB3201_unit.bp
  units/UAB3202/UAB3202_unit.bp
  units/UAS0305/UAS0305_unit.bp
  units/UEB3101/UEB3101_unit.bp
  units/UEB3102/UEB3102_unit.bp
  units/UEB3104/UEB3104_unit.bp
  units/UEB3201/UEB3201_unit.bp
  units/UEB3202/UEB3202_unit.bp
  units/UES0305/UES0305_unit.bp
  units/URB3101/URB3101_unit.bp
  units/URB3102/URB3102_unit.bp
  units/URB3104/URB3104_unit.bp
  units/URB3201/URB3201_unit.bp
  units/URB3202/URB3202_unit.bp
  units/URS0305/URS0305_unit.bp
  units/XSB3101/XSB3101_unit.bp
  units/XSB3102/XSB3102_unit.bp
  units/XSB3104/XSB3104_unit.bp
  units/XSB3201/XSB3201_unit.bp
  units/XSB3202/XSB3202_unit.bp
Labels: area: balance, DO NOT MERGE

#6042 Improve annotations of `OnMotionHorzEventChange` and `OnMotionVertEventChange`
  changelog/3809.md
  engine/Enums.lua
  lua/sim/Unit.lua
  lua/sim/units/AirTransportUnit.lua
  lua/sim/units/AirUnit.lua
  lua/sim/units/SubUnit.lua
  lua/sim/units/WalkingLandUnit.lua
  lua/sim/weapon.lua
  lua/sim/weapons/DefaultProjectileWeapon.lua
  lua/ui/game/unitviewDetail.lua
  units/UAS0401/UAS0401_script.lua
  units/UEA0104/UEA0104_Script.lua
  units/UEA0107/UEA0107_Script.lua
  units/URA0104/URA0104_script.lua
  units/URA0107/URA0107_Script.lua
  units/URA0203/URA0203_script.lua
  units/URA0401/URA0401_script.lua
  units/URL0402/URL0402_script.lua
  units/URS0201/URS0201_script.lua
  units/XEA0306/XEA0306_Script.lua
  units/XRA0105/XRA0105_script.lua
  units/XRL0403/XRL0403_script.lua
  units/XSB3202/XSB3202_script.lua
  units/XSL0101/XSL0101_script.lua
  units/XSS0201/XSS0201_script.lua
Labels: area: code style

#6073 Allow Mongoose and Hoplite to fire from transports
  changelog/3809.md
  units/DEL0204/DEL0204_unit.bp
  units/DRL0204/DRL0204_lod0.scm
  units/DRL0204/DRL0204_unit.bp
Labels: area: balance idea, DO NOT MERGE

#6082 Rationalize the economy stats of various Shield Generators
  changelog/3809.md
  units/UAB4202/UAB4202_unit.bp
  units/UEB4202/UEB4202_unit.bp
  units/UEB4301/UEB4301_unit.bp
  units/XSB4202/XSB4202_unit.bp
  units/XSB4301/XSB4301_unit.bp
Labels: area: balance, DO NOT MERGE

#5905 Increase teleport effect scale by 25%
  lua/EffectUtilities.lua
Labels: area: balance, area: graphics, DO NOT MERGE, feature: teleportation

#6086 Ensure that the Cooper's hitbox aligns with its model
  changelog/3809.md
  units/XES0102/XES0102_unit.bp
Labels: feature: collision shapes

#6094 Revert hoplite firing from transports
  changelog/3809.md
  units/DRL0204/DRL0204_lod0.scm
  units/DRL0204/DRL0204_unit.bp
Labels: area: balance, DO NOT MERGE

#6093 Add entity + dummy Unit in between ExFac and ExFacUnit
  lua/defaultcomponents.lua
  units/ZXA0003/ZXA0003_script.lua
  units/ZXA0003/ZXA0003_unit.bp
Labels: type: bug, area: sim, feature: mobile factories

#6099 Introduce basic anti-spam protection from taunts
  changelog/3809.md
  changelog/3810.md
  lua/ui/game/taunt.lua
  lua/ui/lobby/changelogData.lua
  lua/ui/lobby/lobby.lua
  lua/version.lua
  mod_info.lua
  units/URB2108/URB2108_unit.bp
Labels: area: ui

#5088 Quicken inevitable voting results
  lua/aibrain.lua
  lua/sim/Recall.lua
  lua/ui/game/recall.lua
  lua/ui/help/tooltips.lua
Labels: area: sim, area: ui

#6065 Refactor collision beams
  changelog/3810.md
  engine/Sim.lua
  lua/EffectTemplates.lua
  lua/defaultcollisionbeams.lua
  lua/sim/CollisionBeam.lua
  lua/sim/DefaultProjectiles.lua
  lua/sim/collisionBeams/DisruptorBeamCollisionBeam.lua
  lua/sim/collisionBeams/ExperimentalPhasonLaserCollisionBeam.lua
  lua/sim/collisionBeams/GinsuCollisionBeam.lua
  lua/sim/collisionBeams/MicrowaveLaserCollisionBeam01.lua
  lua/sim/collisionBeams/MicrowaveLaserCollisionBeam02.lua
  lua/sim/collisionBeams/OrbitalDeathLaserCollisionBeam.lua
  lua/sim/collisionBeams/ParticleCannonCollisionBeam.lua
  lua/sim/collisionBeams/PhasonLaserCollisionBeam.lua
  lua/sim/collisionBeams/QuantumBeamGeneratorCollisionBeam.lua
  lua/sim/collisionBeams/SCCollisionBeam.lua
  lua/sim/collisionBeams/TDFHiroCollisionBeam.lua
  lua/sim/collisionBeams/TractorClawCollisionBeam.lua
  lua/sim/collisionBeams/UltraChromaticBeamGeneratorCollisionBeam.lua
  lua/sim/collisionBeams/UltraChromaticBeamGeneratorCollisionBeam02.lua
  lua/sim/collisionBeams/UnstablePhasonLaserCollisionBeam.lua
  lua/sim/collisionBeams/ZapperCollisionBeam.lua
Labels: area: code style

#6102 Inherit all damage data in Ahwassa bomb script
  changelog/3810.md
  projectiles/SBOOhwalliStrategicBomb01/SBOOhwalliStrategicBomb01_script.lua
Labels: type: bug

#6091 Simplify and robustify transport cargo killing and veterancy
  changelog/3810.md
  engine/Sim/Entity.lua
  lua/armordefinition.lua
  lua/defaultcomponents.lua
  lua/sim/Unit.lua
  lua/sim/units/AirTransportUnit.lua
  lua/sim/units/AirUnit.lua
  lua/sim/units/AircraftCarrierUnit.lua
  lua/sim/units/MobileUnit.lua
  lua/sim/units/components/TransportUnitComponent.lua
Labels: area: balance, area: sim, feature: transports, DO NOT MERGE

#6104 Balance : TML Hp Reduction & Adds Death Weapon
  changelog/3810.md
  units/UAB2108/UAB2108_unit.bp
  units/UEB2108/UEB2108_unit.bp
  units/URB2108/URB2108_unit.bp
  units/XSB2108/XSB2108_unit.bp
Labels: area: balance, DO NOT MERGE

#6077 Improve/fix the Tempest's anti-torpedo weapon
  changelog/3810.md
  units/UAS0401/UAS0401_script.lua
  units/UAS0401/UAS0401_unit.bp
Labels: area: balance, DO NOT MERGE

#6124 Remove caching of the preference file
  lua/user/prefs.lua
Labels: type: bug, area: ui

#6095 Improve area attack and reclaim orders
  engine/User.lua
  lua/SimCallbacks.lua
  lua/maui/dragger.lua
  lua/options/options.lua
  lua/shared/commands/area-attack-order.lua
  lua/shared/commands/area-reclaim-order.lua
  lua/sim/commands/area-attack-ground-order.lua
  lua/sim/commands/area-reclaim-order.lua
  lua/system/repr.lua
  lua/ui/controls/draggers/radial.lua
  lua/ui/controls/draggers/rectangle.lua
  lua/ui/controls/worldview.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/hotkeys/area-attack-order.lua
  lua/ui/game/hotkeys/area-reclaim-order.lua
  lua/ui/game/renderable/circle.lua
  lua/ui/game/renderable/square.lua
  lua/ui/game/worldview.lua
  lua/ui/help/tooltips.lua
Labels: area: balance, area: sim, area: ui

#6090 Reduce the amount of logging performed by the game
  changelog/3810.md
  lua/system/import.lua
Labels: area: sim, area: lobby

#6089 Reduce the lifetime for water trail emitters
  effects/emitters/water_move_trail_back_03_emit.bp
  effects/emitters/water_move_trail_back_04_emit.bp
  effects/emitters/water_move_wake_front_l_01_emit.bp
  effects/emitters/water_move_wake_front_r_01_emit.bp
  lua/defaultcomponents.lua
  units/XSL0303/XSL0303_unit.bp
Labels: area: graphics

#6127 Buff the Selen (Seraphim Tech 1 Combat Scout)
  changelog/3810.md
  units/XSL0101/XSL0101_script.lua
  units/XSL0101/XSL0101_unit.bp
Labels: area: balance, DO NOT MERGE

#6118 fix incorrect table being inserted into AI marker function
  changelog/snippets/ai.6118.md
  lua/AI/aiutilities.lua
Labels: area: AI
