Repository FAForever/fa, pull requests merged in 2024-02, with the labels that each got.

#5846 Draft implementation of the new projectile functions
  engine/Sim/Projectile.lua
  lua/sim/Projectile.lua
Labels: area: engine

#5866 fix submarines surfacing at start of navalforceai
  lua/platoon.lua
Labels: type: bug, area: AI

#5872 Ai rating trueskill
  lua/ui/lobby/lobby.lua
Labels: area: lobby, area: AI

#5873 Reduce the scorch mark lifetime of burnt trees down to two minutes
  lua/defaultexplosions.lua
Labels: type: bug, area: graphics

#5864 Fix the status of the minimap's pin feature not being saved into the game.prefs file
  lua/ui/game/minimap.lua
Labels: type: bug, area: ui

#5871 Tackle performance issues when accessing the preference file
  engine/User.lua
  lua/keymap/hotbuild.lua
  lua/ui/controls/worldview.lua
  lua/ui/game/chat.lua
  lua/ui/game/commandmode.lua
  lua/ui/game/construction.lua
  lua/ui/game/score.lua
  lua/ui/game/unitview.lua
  lua/ui/lobby/lobby.lua
  lua/ui/lobby/lobbyComm.lua
  lua/ui/notify/notify.lua
  lua/ui/notify/notifyoverlay.lua
  lua/ui/override/SessionClients.lua
  lua/user/prefs.lua
Labels: area: ui

#5875 Enable the Tech 3 Kennel to be dragged when spawning it via the Alt + F2 menu
  units/XEB0204/XEB0204_unit.bp
Labels: area: ui

#5858 Improve the descriptions of various UEF units
  loc/US/strings_db.lua
Labels: area: ui

#5475 Variable teleport cost
  engine/Core/Blueprints/UnitBlueprint.lua
  engine/User.lua
  engine/User/UserUnit.lua
  lua/maui/cursor.lua
  lua/shared/teleport.lua
  lua/sim/Unit.lua
  lua/ui/controls/reticle.lua
  lua/ui/controls/reticles/teleport.lua
  lua/ui/controls/worldview.lua
  lua/ui/uiutil.lua
  units/UAL0001/UAL0001_unit.bp
  units/UAL0301/UAL0301_unit.bp
  units/UEL0001/UEL0001_unit.bp
  units/URL0001/URL0001_unit.bp
  units/XSL0001/XSL0001_unit.bp
  units/XSL0301/XSL0301_unit.bp
Labels: area: balance, area: sim

#5877 Add a connection matrix dialog
  lua/keymap/debugKeyActions.lua
  lua/shared/Subject.lua
  lua/ui/dialogs/connection/ConnectionDialog.lua
  lua/ui/dialogs/connection/ConnectionDialogData.lua
  lua/ui/dialogs/connection/ConnectionDialogDot.lua
  lua/ui/game/gamemain.lua
  lua/ui/override/SessionClients.lua
Labels: area: ui

#5878 Fix Volcano being able to redirect a strategic missile
  lua/defaultantiprojectile.lua
Labels: feature: tactical missiles

#5879 Fix collision box of tech 1 air scouts when landed
  units/UAA0101/UAA0101_unit.bp
  units/UEA0101/UEA0101_unit.bp
  units/URA0101/URA0101_unit.bp
  units/XSA0101/XSA0101_unit.bp
Labels: type: bug, feature: collision shapes

#5880 Fix losing progress on strategic missile launchers
  lua/sim/units/StructureUnit.lua
Labels: type: bug, area: sim, feature: tactical missiles

#5849 Salvation nerf
  lua/EffectTemplates.lua
  lua/sim/weapons/aeon/AIFQuanticArtillery.lua
  units/XAB2307/XAB2307_unit.bp
Labels: area: balance

#5887 Significantly improve the albedo, normal and spec channels of the Mongoose
  units/DEL0204/DEL0204_normalsTS.dds
  units/DEL0204/del0204_albedo.dds
  units/DEL0204/del0204_specteam.dds
Labels: area: graphics

#5888 Fix/veterancy from allied units
  lua/defaultcomponents.lua
Labels: type: bug, area: sim

#5860 Cycle through templates based on highlighted command
  engine/Core/Categories.lua
  engine/User.lua
  lua/ui/game/hotkeys/context-based-templates-data.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendAirGrid.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendExtractorWithFabs.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendExtractorWithStorages.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendOpticsWithPower.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToEnergyStorage.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToEye.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToSalvation.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToSoothsayer.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToT2Artillery.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToT3Artillery.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToTML.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendRadarWithPower.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendSalvationWithPower.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendT2ArtilleryWithPower.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendT3ArtilleryWithPower.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendT3FabricatorWithStorages.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendWallsToPointDefense.lua
  lua/ui/game/hotkeys/context-based-templates-data/CapExtractorWithStorages.lua
  lua/ui/game/hotkeys/context-based-templates-data/CapRadarWithPower.lua
  lua/ui/game/hotkeys/context-based-templates-data/CapT3ArtilleryWithPower.lua
  lua/ui/game/hotkeys/context-based-templates.lua
Labels: feature: context-based templates

#5896 Fix Corona and Swiftwind having a tough time aiming at landed units
  units/UAA0303/UAA0303_unit.bp
  units/XAA0202/XAA0202_unit.bp
Labels: type: bug, area: sim

#5890 Improve scripted events of the Thunderhead Class
  lua/sim/units/SeaUnit.lua
  units/UES0103/UES0103_script.lua
  units/UES0103/UES0103_unit.bp
Labels: area: graphics

#5892 Improve scripted events of the Valiant class
  effects/emitters/sparks_11_emit.bp
  units/UES0201/UES0201_script.lua
Labels: area: graphics

#5884 Allow Chrono Dampener to fire underwater
  units/UAL0001/UAL0001_unit.bp
Labels: area: balance

#5897 Fix wrecks of sinking units ending up below the terrain
  engine/Core.lua
  lua/ScenarioFramework.lua
  lua/sim/Unit.lua
  lua/wreckage.lua
Labels: type: bug, area: sim

#5899 Remove the dive button for units that do no not need it
  lua/sim/units/SubUnit.lua
  units/UAS0203/UAS0203_unit.bp
  units/UAS0304/UAS0304_unit.bp
  units/UES0304/UES0304_unit.bp
  units/URS0304/URS0304_unit.bp
  units/XAS0204/XAS0204_unit.bp
  units/XRS0204/XRS0204_unit.bp
Labels: area: sim

#5900 Improve Teleport Reticle Cost Display
  lua/shared/teleport.lua
  lua/ui/controls/reticles/teleport.lua
Labels: area: ui

#5904 Fix teleport effects not appearing at short ranges with variable cost
  lua/shared/teleport.lua
Labels: area: graphics, feature: teleportation

#5910 Improve path finding of the Blaze and Zthuee
  units/XAL0203/XAL0203_lod0.scm
  units/XAL0203/XAL0203_normalsTS.dds
  units/XAL0203/XAL0203_unit.bp
  units/XSL0103/XSL0103_unit.bp
Labels: feature: pathfinding

#5907 Adjust the variable teleport costs
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/shared/teleport.lua
  units/UAL0001/UAL0001_unit.bp
  units/UAL0301/UAL0301_unit.bp
  units/UEL0001/UEL0001_unit.bp
  units/URL0001/URL0001_unit.bp
  units/XSL0001/XSL0001_unit.bp
  units/XSL0301/XSL0301_unit.bp
Labels: feature: teleportation

#5911 Refactor Seraphim torpedo's and improve aesthetics and performance
  lua/sim/DefaultProjectiles.lua
  lua/sim/Projectile.lua
  lua/sim/projectiles/components/SplitComponent.lua
  projectiles/SANHeavyCavitationTorpedo01/SANHeavyCavitationTorpedo01_script.lua
  projectiles/SANHeavyCavitationTorpedo02/SANHeavyCavitationTorpedo02_proj.bp
  projectiles/SANHeavyCavitationTorpedo02/SANHeavyCavitationTorpedo02_script.lua
  projectiles/SANHeavyCavitationTorpedo03/SANHeavyCavitationTorpedo03_proj.bp
  projectiles/SANHeavyCavitationTorpedo03/SANHeavyCavitationTorpedo03_script.lua
  projectiles/SANHeavyCavitationTorpedo04/SANHeavyCavitationTorpedo04_proj.bp
  projectiles/SANHeavyCavitationTorpedo04/SANHeavyCavitationTorpedo04_script.lua
  projectiles/SANUallCavitationTorpedo01/SANUallCavitationTorpedo01_script.lua
  projectiles/SANUallCavitationTorpedo02/SANUallCavitationTorpedo02_script.lua
  projectiles/SANUallCavitationTorpedo03/SANUallCavitationTorpedo03_script.lua
  projectiles/SANUallCavitationTorpedo04/SANUallCavitationTorpedo04_script.lua
  units/XSB2205/XSB2205_unit.bp
Labels: area: graphics

#5898 Rework the Solace and the projectile count of all Torpedo Bombers
  units/UAA0204/UAA0204_unit.bp
  units/UEA0204/UEA0204_unit.bp
  units/URA0204/URA0204_unit.bp
  units/XAA0306/XAA0306_unit.bp
  units/XSA0204/XSA0204_unit.bp
Labels: feature: anti projectile weaponry

#5923 Add the ability to load into transports by right clicking the transport button
  engine/User/CMauiEdit.lua
  loc/US/strings_db.lua
  lua/ui/game/orders.lua
  lua/ui/help/tooltips.lua
Labels: area: ui, feature: transports

#5920 Adding the use of Code Spell Checker plugin
  .vscode/settings.json
  README.md
  blender/howto.md
  changelog/3636.md
  changelog/3639.md
  changelog/3641.md
  changelog/3652.md
  changelog/3658.md
  changelog/3660.md
  changelog/3676.md
  changelog/3680.md
  changelog/3681.md
  changelog/3684.md
  changelog/3686.md
  changelog/3688.md
  changelog/3696.md
  changelog/3697.md
  changelog/3704.md
  changelog/3705.md
  changelog/3710.md
  changelog/3712.md
  changelog/3715.md
  changelog/3718.md
  changelog/3721.md
  changelog/3726.md
  changelog/3728.md
  changelog/3732.md
  changelog/3738.md
  changelog/3740.md
  changelog/3741.md
  changelog/3745.md
  changelog/3746.md
  changelog/3750.md
  changelog/3751.md
  changelog/3754.md
  loc/US/strings_db.lua
  setup/setup-english.md
Labels: area: code style

#5921 Continental fix target priorities
  units/XEA0306/XEA0306_unit.bp
Labels: area: balance, feature: target priorities

#5915 Prevent tactical missiles from hitting TMD
  lua/sim/Projectile.lua
  lua/sim/projectiles/aeon/AMissileSerpentineProjectile.lua
  lua/sim/projectiles/components/TacticalMissileComponent.lua
  projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_proj.bp
  projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
  projectiles/AIFMissileSerpentine02/AIFMissileSerpentine02_script.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_proj.bp
  projectiles/AIFMissileTactical01/AIFMissileTactical01_Script.lua
  projectiles/AIFMissileTactical01/AIFMissileTactical01_proj.bp
  projectiles/AIFMissileTactical02/AIFMissileTactical02_Script.lua
  projectiles/AIFMissileTactical02/AIFMissileTactical02_proj.bp
  projectiles/CIFMissileTactical01/CIFMissileTactical01_Script.lua
  projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua
  projectiles/CIFMissileTactical03/CIFMissileTactical03_Script.lua
  projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_Script.lua
  projectiles/SIFLaanseTacticalMissile01/SIFLaanseTacticalMissile01_proj.bp
  projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_Script.lua
  projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_proj.bp
  projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_Script.lua
  projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_proj.bp
  projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_Script.lua
  projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_proj.bp
  projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_script.lua
  projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_proj.bp
  projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_script.lua
  projectiles/TIFMissileCruise01/TIFMissileCruise01_proj.bp
  projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_proj.bp
  units/UES0202/UES0202_unit.bp
  units/XSB2108/XSB2108_unit.bp
  units/XSL0001/XSL0001_unit.bp
  units/XSL0301/XSL0301_unit.bp
  units/XSS0202/XSS0202_unit.bp
  units/XSS0303/XSS0303_unit.bp
Labels: feature: tactical missiles

#5932 Refactor how the reclaim costs are computed
  lua/sim/Unit.lua
Labels: area: sim

#5916 Improve Ythotha targeting
  units/XSL0401/XSL0401_unit.bp
Labels: area: unit-blueprint, feature: target priorities

#5764 Change the reverse behavior for various units
  units/DAL0310/DAL0310_unit.bp
  units/DALK003/DALK003_unit.bp
  units/DELK002/DELK002_unit.bp
  units/DRLK001/DRLK001_unit.bp
  units/DSLK004/DSLK004_unit.bp
  units/UAL0101/UAL0101_unit.bp
  units/UAL0103/UAL0103_unit.bp
  units/UAL0104/UAL0104_unit.bp
  units/UAL0111/UAL0111_unit.bp
  units/UAL0201/UAL0201_unit.bp
  units/UAL0202/UAL0202_unit.bp
  units/UAL0205/UAL0205_unit.bp
  units/UAL0304/UAL0304_unit.bp
  units/UAL0307/UAL0307_unit.bp
  units/UEL0101/UEL0101_unit.bp
  units/UEL0103/UEL0103_unit.bp
  units/UEL0104/UEL0104_unit.bp
  units/UEL0111/UEL0111_unit.bp
  units/UEL0201/UEL0201_unit.bp
  units/UEL0202/UEL0202_unit.bp
  units/UEL0203/UEL0203_unit.bp
  units/UEL0205/UEL0205_unit.bp
  units/UEL0304/UEL0304_unit.bp
  units/UEL0307/UEL0307_unit.bp
  units/URL0103/URL0103_unit.bp
  units/URL0104/URL0104_unit.bp
  units/URL0111/URL0111_unit.bp
  units/URL0202/URL0202_unit.bp
  units/URL0203/URL0203_unit.bp
  units/URL0205/URL0205_unit.bp
  units/URL0304/URL0304_unit.bp
  units/URL0306/URL0306_unit.bp
  units/URL0401/URL0401_unit.bp
  units/XAL0203/XAL0203_unit.bp
  units/XEL0306/XEL0306_unit.bp
  units/XRL0403/XRL0403_unit.bp
  units/XSL0103/XSL0103_unit.bp
  units/XSL0111/XSL0111_unit.bp
  units/XSL0201/XSL0201_unit.bp
  units/XSL0203/XSL0203_unit.bp
  units/XSL0205/XSL0205_unit.bp
  units/XSL0303/XSL0303_unit.bp
  units/XSL0304/XSL0304_unit.bp
  units/XSL0307/XSL0307_unit.bp
Labels: area: balance

#5933 Fix the collision boxes of various miscellaneous units to prevent the game from creating warnings for them at the start of the game
  units/OPC1002/OPC1002_unit.bp
  units/OPE6003/OPE6003_unit.bp
  units/UEC0001/UEC0001_unit.bp
  units/URC0001/URC0001_unit.bp
  units/UXL0021/UXL0021_unit.bp
  units/ope2003/OPE2003_unit.bp
Labels: feature: collision shapes

#5943 Remove Novax from air restrictions
  lua/ui/lobby/UnitsRestrictions.lua
Labels: area: unit-restrictions
