Repository FAForever/fa, pull requests merged in 2024-08, with the labels that each got.

#6386 Add a custom color scheme to the docs
  docs/_config.yml
  docs/_sass/color_schemes/faf.scss
Labels: area: documentation

#6390 Fix the navigational mesh not culling labels
  docs/_posts/2024-08-03-3811.md
  lua/sim/NavGenerator.lua
  lua/ui/lobby/changelogData.lua
Labels: type: bug, area: AI, area: nav-mesh

#6399 Update annotations of engine projectile methods
  changelog/snippets/other.6399.md
  engine/Sim/Projectile.lua
Labels: area: documentation

#6398 Fix being able to pass through invalid ballistic values
  changelog/snippets/fix.6398.md
  lua/sim/Projectile.lua
Labels: type: bug

#6400 Prevent simultaneous deployments across all branches
  .github/workflows/deploy-faf.yaml
  .github/workflows/deploy-fafbeta.yaml
  .github/workflows/deploy-fafdevelop.yaml
Labels: area: documentation

#6404 Filter out upgrade units from being rebuilt on transfer
  changelog/snippets/fix.6404.md
  lua/SimUtils.lua
Labels: type: bug, area: sim

#6407 Fix links in deployment.md
  docs/deployment.md
Labels: area: documentation

#6308 Fix sats being able to trigger nuke explosions
  changelog/snippets/other.6308.md
  lua/sim/units/AirUnit.lua
Labels: area: balance, DO NOT MERGE

#6410 Mercy cost buff
  changelog/snippets/balance.6365.md
  units/DAA0206/DAA0206_unit.bp
Labels: area: balance

#6375 Nerf Blaze speed 4.3 -> 4.0
  changelog/snippets/balance.6375.md
  units/XAL0203/XAL0203_unit.bp
Labels: area: balance

#6389 Improve T2 Static Artillery's ability to shoot up cliffs
  changelog/snippets/fix.6389.md
  units/UAB2303/UAB2303_unit.bp
  units/UEB2303/UEB2303_unit.bp
  units/URB2303/URB2303_unit.bp
  units/XSB2303/XSB2303_unit.bp
Labels: area: balance

#6417 Reduce T2 amphibious tank vision
  changelog/snippets/balance.6417.md
  units/URL0203/URL0203_unit.bp
  units/XAL0203/XAL0203_unit.bp
  units/XSL0203/XSL0203_unit.bp
Labels: area: balance
