Repository FAForever/fa, pull requests merged in 2024-01, with the labels that each got.

#5791 Clean up the billy revamp and revert damage behavior changes
  lua/terranprojectiles.lua
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua
  units/UEL0001/UEL0001_unit.bp
Labels: feature: tactical missiles

#5790 Re-implement the missile redirect of the Loyalist
  engine/Sim/Projectile.lua
  engine/Sim/UnitWeapon.lua
  lua/sim/Projectile.lua
  lua/sim/projectiles/components/SplitComponent.lua
  lua/sim/projectiles/components/TacticalMissileComponent.lua
  lua/sim/weapon.lua
  lua/sim/weapons/cybran/CDFMissileRedirectWeapon01.lua
  projectiles/CIFMissileTacticalSplit01/CIFMissileTacticalSplit01_Script.lua
  units/URL0303/URL0303_Script.lua
  units/URL0303/URL0303_unit.bp
Labels: area: balance, feature: tactical missiles

#5792 Buff Sera SACU turn rate and turret yaw speed
  units/XSL0301/XSL0301_unit.bp
Labels: area: balance

#5765 Remove unused cost stats from Seraphim naval TML
  projectiles/SIFLaanseTacticalMissile02/SIFLaanseTacticalMissile02_proj.bp
  projectiles/SIFLaanseTacticalMissile03/SIFLaanseTacticalMissile03_proj.bp
Labels: feature: tactical missiles

#5193 Lod1 fixes cybran
  units/DRLK001/DRLK001_lod1.scm
  units/DRLK001/DRLK001_lod1_Albedo.dds
  units/DRLK001/DRLK001_lod1_SpecTeam.dds
  units/DRLK001/DRLK001_unit.bp
  units/URL0111/URL0111_lod1.scm
  units/URL0111/URL0111_lod1_Albedo.dds
  units/URL0111/URL0111_lod1_SpecTeam.dds
  units/URL0111/URL0111_lod1_normalsTS.dds
  units/URL0111/URL0111_unit.bp
  units/URL0202/URL0202_lod1.scm
  units/URL0202/URL0202_lod1_Albedo.dds
  units/URL0202/URL0202_lod1_SpecTeam.dds
  units/URL0202/URL0202_unit.bp
  units/URL0205/URL0205_lod1.scm
  units/URL0205/URL0205_lod1_Albedo.dds
  units/URL0205/URL0205_lod1_SpecTeam.dds
  units/URL0205/URL0205_unit.bp
Labels: area: graphics

#5794 Add missile redirect behavior for Cybran cruiser and aircraft carrier
  effects/Entities/CybranPhalanxSphere01/CybranPhalanxSphere01_Albedo.dds
  effects/Entities/CybranPhalanxSphere01/CybranPhalanxSphere01_Normals.dds
  effects/Entities/CybranPhalanxSphere01/CybranPhalanxSphere02_Albedo.dds
  effects/Entities/CybranPhalanxSphere01/CybranPhalanxSphere03_Albedo.dds
  effects/Entities/CybranPhalanxSphere01/CybranPhalanxSphere03_mesh.bp
  effects/emitters/zapper_electricity_03_emit.bp
  lua/sim/weapons/cybran/CDFMissileRedirectWeapon01.lua
  lua/sim/weapons/cybran/CDFMissileRedirectWeapon02.lua
  units/URL0303/URL0303_unit.bp
  units/URS0202/URS0202_script.lua
  units/URS0202/URS0202_unit.bp
  units/URS0303/URS0303_script.lua
  units/URS0303/URS0303_unit.bp
Labels: feature: tactical missiles

#5798 Further tweaks to weapon details
  lua/ui/game/unitviewDetail.lua
Labels: area: ui

#5800 Fix strategic icon scale not applying correctly
  engine/User.lua
  lua/options/options.lua
Labels: feature: strategic icons

#5801 Add new engine functions annotations
  engine/User.lua
  engine/User/CUIWorldView.lua
  engine/User/UserUnit.lua
  lua/ui/controls/worldview.lua
Labels: area: code style, area: tooling, type: intellisense

#5723 Fix score graph scaling
  lua/ui/dialogs/hotstats.lua
Labels: area: ui

#5671 Move Aeon Unit Classes to separate Files
  lua/aeonunits.lua
  lua/sim/units/aeon/AAirFactoryUnit.lua
  lua/sim/units/aeon/AAirStagingPlatformUnit.lua
  lua/sim/units/aeon/AAirUnit.lua
  lua/sim/units/aeon/ACivilianStructureUnit.lua
  lua/sim/units/aeon/AConcreteStructureUnit.lua
  lua/sim/units/aeon/AConstructionUnit.lua
  lua/sim/units/aeon/AEnergyCreationUnit.lua
  lua/sim/units/aeon/AEnergyStorageUnit.lua
  lua/sim/units/aeon/AFactoryUnit.lua
  lua/sim/units/aeon/AHoverLandUnit.lua
  lua/sim/units/aeon/ALandFactoryUnit.lua
  lua/sim/units/aeon/ALandUnit.lua
  lua/sim/units/aeon/AMassCollectionUnit.lua
  lua/sim/units/aeon/AMassFabricationUnit.lua
  lua/sim/units/aeon/AMassStorageUnit.lua
  lua/sim/units/aeon/AQuantumGateUnit.lua
  lua/sim/units/aeon/ARadarJammerUnit.lua
  lua/sim/units/aeon/ARadarUnit.lua
  lua/sim/units/aeon/ASeaFactoryUnit.lua
  lua/sim/units/aeon/ASeaUnit.lua
  lua/sim/units/aeon/AShieldHoverLandUnit.lua
  lua/sim/units/aeon/AShieldLandUnit.lua
  lua/sim/units/aeon/AShieldStructureUnit.lua
  lua/sim/units/aeon/ASonarUnit.lua
  lua/sim/units/aeon/AStructureUnit.lua
  lua/sim/units/aeon/ASubUnit.lua
  lua/sim/units/aeon/ATransportBeaconUnit.lua
  lua/sim/units/aeon/AWalkingLandUnit.lua
  lua/sim/units/aeon/AWallStructureUnit.lua
  units/UAB0102/UAB0102_script.lua
  units/UAB0202/UAB0202_script.lua
  units/UAB0302/UAB0302_script.lua
  units/ZAB9502/ZAB9502_script.lua
  units/ZAB9602/ZAB9602_script.lua
Labels: area: code style

#5802 Add UEF ACU silo hatch animation
  units/UEL0001/UEL0001_script.lua
  units/UEL0001/UEL0001_unit.bp
Labels: area: graphics

#5795 Adjust collision size of air units when they are landed
  lua/sim/Unit.lua
  lua/sim/units/AirUnit.lua
  units/DEA0202/DEA0202_unit.bp
  units/DRA0202/DRA0202_unit.bp
  units/UAA0304/UAA0304_unit.bp
  units/UEA0203/UEA0203_unit.bp
  units/UEA0304/UEA0304_unit.bp
  units/UEA0305/UEA0305_unit.bp
  units/URA0302/URA0302_unit.bp
  units/URA0304/URA0304_unit.bp
  units/XAA0305/XAA0305_unit.bp
  units/XRA0305/XRA0305_unit.bp
Labels: feature: collision shapes

#5804 Fix the Shard being able to evade beam weapons
  units/UAS0102/UAS0102_unit.bp
Labels: feature: target bones, feature: collision shapes

#5805 Seraphim SACU Base Economy Buff
  units/XSL0301/XSL0301_unit.bp
Labels: area: balance

#5667 Automate Sera sniper mode micro
  units/XSL0305/XSL0305_script.lua
Labels: area: balance

#5659 Move classes of Aeon weapons to separate files
  lua/aeonweapons.lua
  lua/sim/weapons/aeon/AAAAutocannonQuantumWeapon.lua
  lua/sim/weapons/aeon/AAALightDisplacementAutocannonMissileWeapon.lua
  lua/sim/weapons/aeon/AAASonicPulseBatteryWeapon.lua
  lua/sim/weapons/aeon/AAATemporalFizzWeapon.lua
  lua/sim/weapons/aeon/AAAZealot02MissileWeapon.lua
  lua/sim/weapons/aeon/AAAZealotMissileWeapon.lua
  lua/sim/weapons/aeon/AAMSaintWeapon.lua
  lua/sim/weapons/aeon/AAMWillOWisp.lua
  lua/sim/weapons/aeon/AANChronoTorpedoWeapon.lua
  lua/sim/weapons/aeon/AANDepthChargeBombWeapon.lua
  lua/sim/weapons/aeon/AANDepthChargeBombWeapon02.lua
  lua/sim/weapons/aeon/AANTorpedoCluster.lua
  lua/sim/weapons/aeon/ACruiseMissileWeapon.lua
  lua/sim/weapons/aeon/ADFCannonOblivionNaval.lua
  lua/sim/weapons/aeon/ADFCannonOblivionWeapon.lua
  lua/sim/weapons/aeon/ADFCannonOblivionWeapon02.lua
  lua/sim/weapons/aeon/ADFCannonOblivionWeapon03.lua
  lua/sim/weapons/aeon/ADFCannonQuantumWeapon.lua
  lua/sim/weapons/aeon/ADFChronoDampener.lua
  lua/sim/weapons/aeon/ADFDisruptorCannonWeapon.lua
  lua/sim/weapons/aeon/ADFDisruptorWeapon.lua
  lua/sim/weapons/aeon/ADFGravitonProjectorWeapon.lua
  lua/sim/weapons/aeon/ADFHeavyDisruptorCannonWeapon.lua
  lua/sim/weapons/aeon/ADFLaserHeavyWeapon.lua
  lua/sim/weapons/aeon/ADFLaserHighIntensityWeapon.lua
  lua/sim/weapons/aeon/ADFLaserLightWeapon.lua
  lua/sim/weapons/aeon/ADFOverchargeWeapon.lua
  lua/sim/weapons/aeon/ADFPhasonLaser.lua
  lua/sim/weapons/aeon/ADFQuadLaserLightWeapon.lua
  lua/sim/weapons/aeon/ADFQuantumAutogunWeapon.lua
  lua/sim/weapons/aeon/ADFReactonCannon.lua
  lua/sim/weapons/aeon/ADFSonicPulsarWeapon.lua
  lua/sim/weapons/aeon/ADFTractorClaw.lua
  lua/sim/weapons/aeon/ADFTractorClawStructure.lua
  lua/sim/weapons/aeon/AIFArtilleryMiasmaShellWeapon.lua
  lua/sim/weapons/aeon/AIFArtillerySonanceShellWeapon.lua
  lua/sim/weapons/aeon/AIFBallisticMortarWeapon.lua
  lua/sim/weapons/aeon/AIFBombGravitonWeapon.lua
  lua/sim/weapons/aeon/AIFBombQuarkWeapon.lua
  lua/sim/weapons/aeon/AIFMissileTacticalSerpentine02Weapon.lua
  lua/sim/weapons/aeon/AIFMissileTacticalSerpentineWeapon.lua
  lua/sim/weapons/aeon/AIFMortarWeapon.lua
  lua/sim/weapons/aeon/AIFQuanticArtillery.lua
  lua/sim/weapons/aeon/AIFQuantumWarhead.lua
  lua/sim/weapons/aeon/AIFQuasarAntiTorpedoWeapon.lua
  lua/sim/weapons/aeon/AIFSmartCharge.lua
  lua/sim/weapons/aeon/AKamikazeWeapon.lua
  lua/sim/weapons/aeon/AQuantumBeamGenerator.lua
Labels: area: code style

#5735 Small UI Fixes for Cybran Stealth
  lua/ui/game/orders.lua
  units/URL0001/URL0001_script.lua
  units/URL0001/URL0001_unit.bp
  units/URL0301/URL0301_script.lua
  units/URL0301/URL0301_unit.bp
Labels: area: ui

#5736 Fix toggle intel hotkey label not appearing for toggle scry
  lua/keymap/hotkeylabels.lua
Labels: area: ui

#5806 Eye of R-word target location cost rework
  lua/RemoteViewing.lua
Labels: area: balance

#5807 Improve hit ratio of missiles that zig zag
  lua/sim/projectiles/aeon/AMissileSerpentineProjectile.lua
  lua/sim/projectiles/components/TacticalMissileComponent.lua
  projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
  projectiles/AIFMissileSerpentine02/AIFMissileSerpentine02_script.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
Labels: feature: tactical missiles

#5809 Fix incorrect property being set on BaseTypes
  lua/aibrains/adaptive-ai.lua
  lua/aibrains/medium-ai.lua
  lua/aibrains/rush-ai.lua
  lua/aibrains/tech-ai.lua
  lua/aibrains/turtle-ai.lua
Labels: area: AI

#5812 Add new track target ground logic
  engine/Core.lua
  lua/sim/Projectile.lua
Labels: area: balance, feature: tactical missiles

#5815 Make Percival prioritize structures over T1 units
  units/XEL0305/XEL0305_unit.bp
Labels: area: balance

#5818 Reduce maximum attack radius of the Volcano
  units/UAB4201/UAB4201_unit.bp
Labels: feature: tactical missiles

#5816 Add decimal places for the BuildRate stat in the UI
  lua/ui/game/unitview.lua
Labels: area: ui

#5819 Revert "Experimental changes for the Fatboy"
  units/UEL0401/UEL0401_unit.bp
Labels: area: balance

#5821 Add power generator templates for Eye and Soothsayer
  lua/ui/game/hotkeys/context-based-templates-data.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToEye.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToSoothsayer.lua
  lua/ui/game/hotkeys/context-based-templates-data/CapOpticsWithPower.lua
  units/XAB3301/XAB3301_unit.bp
Labels: feature: context-based templates

#5820 Expand the assist-to functionality
  changelog/3779.md
  lua/SimCallbacks.lua
  lua/options/options.lua
  lua/sim/commands/shared.lua
  lua/ui/game/commandmode.lua
  lua/userInit.lua
Labels: area: ui, feature: assist-to side effects

#5826 Add decimal places for the DamageRadius stat in the UI
  loc/US/strings_db.lua
Labels: area: ui

#5831 Fix achievements JsonStats message
  lua/sim/Unit.lua
  lua/sim/score.lua
  lua/sim/units/AirUnit.lua
  lua/system/dkson.lua
Labels: feature: achievements

#5829 Fix an error when the Salem makes landfall
  units/URS0201/URS0201_unit.bp
Labels: area: graphics

#5823 Fix offsets in ground targeting related to Megalith
  lua/sim/Projectile.lua
  units/XRL0403/XRL0403_script.lua
  units/XRL0403/XRL0403_unit.bp
Labels: feature: tactical missiles, feature: collision shapes

#5830 Rework the FPS counter to be less obstructive and more modern
  lua/debug/uidebug.lua
  lua/shared/statistics.lua
Labels: area: ui

#5834 Fix some issues in naval weapons
  lua/system/blueprints-units.lua
  lua/ui/game/unitviewDetail.lua
  units/UAS0103/UAS0103_unit.bp
  units/UAS0201/UAS0201_unit.bp
  units/UAS0401/UAS0401_unit.bp
  units/UES0201/UES0201_unit.bp
  units/URS0201/URS0201_unit.bp
  units/XAS0204/XAS0204_unit.bp
  units/XAS0306/XAS0306_unit.bp
  units/XES0102/XES0102_unit.bp
  units/XES0307/XES0307_unit.bp
  units/XRL0305/XRL0305_unit.bp
  units/XRL0403/XRL0403_unit.bp
  units/XRS0204/XRS0204_unit.bp
  units/XRS0205/XRS0205_unit.bp
  units/XSB2205/XSB2205_unit.bp
  units/XSS0201/XSS0201_unit.bp
  units/XSS0203/XSS0203_unit.bp
  units/XSS0304/XSS0304_unit.bp
Labels: area: balance

#5841 Reduce the value of wrecks from units on the seabed
  lua/sim/Unit.lua
Labels: type: bug, area: sim

#5848 Remove friendly fire from Ravager
  units/XEB2306/XEB2306_unit.bp
Labels: area: balance

#5789 Re-implement the Billy
  effects/Entities/UEFNukeEffectController02/UEFNukeEffectController02_proj.bp
  effects/Entities/UEFNukeEffectController02/UEFNukeEffectController02_script.lua
  lua/terranprojectiles.lua
  projectiles/TIFMissileCruise01/TIFMissileCruise01_Script.lua
  projectiles/TIFMissileCruise03/TIFMissileCruise03_Script.lua
  projectiles/TIFMissileCruise04/TIFMissileCruise04_Script.lua
  projectiles/TIFMissileCruise05/TIFMissileCruise05_Script.lua
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua
  units/UEL0001/UEL0001_unit.bp
Labels: area: balance, feature: tactical missiles

#5851 Revert "UEF ACU: Revert the option to have the teleporter and nuke upgrades simultaneously"
  units/UEL0001/UEL0001_unit.bp
Labels: area: balance

#5853 Fix a bug when the Billy is redirected
  lua/sim/NukeDamage.lua
  lua/sim/Projectile.lua
  lua/sim/weapons/cybran/CDFMissileRedirectWeapon01.lua
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua
Labels: feature: tactical missiles

#5854 More Robust Auto OC toggle
  lua/sim/units/CommandUnit.lua
  lua/sim/weapons/OverchargeWeapon.lua
  lua/ui/game/orders.lua
Labels: type: bug, area: sim, area: ui

#5840 Improve the descriptions of various Cybran units
  loc/US/strings_db.lua
Labels: area: ui

#5855 Allow AI to have some definition of rating
  lua/system/repr.lua
  lua/ui/lobby/aitypes.lua
  lua/ui/lobby/data/playerdata.lua
  lua/ui/lobby/lobby.lua
Labels: area: ui, area: lobby, area: AI

#5857 Revert "Revert "UEF ACU: Revert the option to have the teleporter and nuke upgrades simultaneously""
  units/UEL0001/UEL0001_unit.bp
Labels: area: balance

#5666 Move classes of Cybran weapons to separate files
  lua/cybranweapons.lua
  lua/sim/weapons/cybran/CAAAutocannon.lua
  lua/sim/weapons/cybran/CAABurstCloudFlakArtilleryWeapon.lua
  lua/sim/weapons/cybran/CAAMissileNaniteWeapon.lua
  lua/sim/weapons/cybran/CAANanoDartWeapon.lua
  lua/sim/weapons/cybran/CAMEMPMissileWeapon.lua
  lua/sim/weapons/cybran/CAMZapperWeapon.lua
  lua/sim/weapons/cybran/CAMZapperWeapon02.lua
  lua/sim/weapons/cybran/CAMZapperWeapon03.lua
  lua/sim/weapons/cybran/CANNaniteTorpedoWeapon.lua
  lua/sim/weapons/cybran/CANTorpedoLauncherWeapon.lua
  lua/sim/weapons/cybran/CCannonMolecularWeapon.lua
  lua/sim/weapons/cybran/CDFBrackmanCrabHackPegLauncherWeapon.lua
  lua/sim/weapons/cybran/CDFEMP.lua
  lua/sim/weapons/cybran/CDFElectronBolterWeapon.lua
  lua/sim/weapons/cybran/CDFHeavyDisintegratorWeapon.lua
  lua/sim/weapons/cybran/CDFHeavyElectronBolterWeapon.lua
  lua/sim/weapons/cybran/CDFHeavyMicrowaveLaserGenerator.lua
  lua/sim/weapons/cybran/CDFHeavyMicrowaveLaserGeneratorCom.lua
  lua/sim/weapons/cybran/CDFHvyProtonCannonWeapon.lua
  lua/sim/weapons/cybran/CDFLaserDisintegratorWeapon01.lua
  lua/sim/weapons/cybran/CDFLaserDisintegratorWeapon02.lua
  lua/sim/weapons/cybran/CDFLaserHeavyWeapon.lua
  lua/sim/weapons/cybran/CDFLaserHeavyWeapon02.lua
  lua/sim/weapons/cybran/CDFLaserPulseLightWeapon.lua
  lua/sim/weapons/cybran/CDFMissileMesonWeapon.lua
  lua/sim/weapons/cybran/CDFOverchargeWeapon.lua
  lua/sim/weapons/cybran/CDFParticleCannonWeapon.lua
  lua/sim/weapons/cybran/CDFProtonCannonWeapon.lua
  lua/sim/weapons/cybran/CDFRocketIridiumWeapon.lua
  lua/sim/weapons/cybran/CDFRocketIridiumWeapon02.lua
  lua/sim/weapons/cybran/CEMPAutoCannon.lua
  lua/sim/weapons/cybran/CIFArtilleryWeapon.lua
  lua/sim/weapons/cybran/CIFBombNeutronWeapon.lua
  lua/sim/weapons/cybran/CIFGrenadeWeapon.lua
  lua/sim/weapons/cybran/CIFMissileCorsairWeapon.lua
  lua/sim/weapons/cybran/CIFMissileLoaTacticalWeapon.lua
  lua/sim/weapons/cybran/CIFMissileLoaWeapon.lua
  lua/sim/weapons/cybran/CIFMissileStrategicWeapon.lua
  lua/sim/weapons/cybran/CIFNaniteTorpedoWeapon.lua
  lua/sim/weapons/cybran/CIFSmartCharge.lua
  lua/sim/weapons/cybran/CKrilTorpedoLauncherWeapon.lua
  lua/sim/weapons/cybran/CMobileKamikazeBombWeapon.lua
Labels: area: code style

#5859 Format of Cybran weapon files
  lua/sim/weapons/cybran/CAAAutocannon.lua
  lua/sim/weapons/cybran/CAABurstCloudFlakArtilleryWeapon.lua
  lua/sim/weapons/cybran/CAAMissileNaniteWeapon.lua
  lua/sim/weapons/cybran/CAANanoDartWeapon.lua
  lua/sim/weapons/cybran/CAMEMPMissileWeapon.lua
  lua/sim/weapons/cybran/CAMZapperWeapon02.lua
  lua/sim/weapons/cybran/CAMZapperWeapon03.lua
  lua/sim/weapons/cybran/CANNaniteTorpedoWeapon.lua
  lua/sim/weapons/cybran/CANTorpedoLauncherWeapon.lua
  lua/sim/weapons/cybran/CCannonMolecularWeapon.lua
  lua/sim/weapons/cybran/CDFBrackmanCrabHackPegLauncherWeapon.lua
  lua/sim/weapons/cybran/CDFEMP.lua
  lua/sim/weapons/cybran/CDFHeavyDisintegratorWeapon.lua
  lua/sim/weapons/cybran/CDFHeavyElectronBolterWeapon.lua
  lua/sim/weapons/cybran/CDFHeavyMicrowaveLaserGenerator.lua
  lua/sim/weapons/cybran/CDFHeavyMicrowaveLaserGeneratorCom.lua
  lua/sim/weapons/cybran/CDFLaserDisintegratorWeapon01.lua
  lua/sim/weapons/cybran/CDFLaserDisintegratorWeapon02.lua
  lua/sim/weapons/cybran/CDFLaserHeavyWeapon.lua
  lua/sim/weapons/cybran/CDFLaserHeavyWeapon02.lua
  lua/sim/weapons/cybran/CDFLaserPulseLightWeapon.lua
  lua/sim/weapons/cybran/CDFMissileMesonWeapon.lua
  lua/sim/weapons/cybran/CDFOverchargeWeapon.lua
  lua/sim/weapons/cybran/CDFParticleCannonWeapon.lua
  lua/sim/weapons/cybran/CDFProtonCannonWeapon.lua
  lua/sim/weapons/cybran/CDFRocketIridiumWeapon.lua
  lua/sim/weapons/cybran/CDFRocketIridiumWeapon02.lua
  lua/sim/weapons/cybran/CEMPAutoCannon.lua
  lua/sim/weapons/cybran/CIFArtilleryWeapon.lua
  lua/sim/weapons/cybran/CIFBombNeutronWeapon.lua
  lua/sim/weapons/cybran/CIFGrenadeWeapon.lua
  lua/sim/weapons/cybran/CIFMissileCorsairWeapon.lua
  lua/sim/weapons/cybran/CIFMissileLoaTacticalWeapon.lua
  lua/sim/weapons/cybran/CIFMissileLoaWeapon.lua
  lua/sim/weapons/cybran/CIFMissileStrategicWeapon.lua
  lua/sim/weapons/cybran/CIFNaniteTorpedoWeapon.lua
  lua/sim/weapons/cybran/CIFSmartCharge.lua
  lua/sim/weapons/cybran/CKrilTorpedoLauncherWeapon.lua
  lua/sim/weapons/cybran/CMobileKamikazeBombWeapon.lua
Labels: area: code style

#5861 Improve performance of navigational functions
  lua/sim/NavUtils.lua
Labels: area: nav-mesh

#5863 Add an alternative, more detailed way to compute positions in radius
  lua/aibrains/platoons/platoon-adaptive-attack.lua
  lua/aibrains/platoons/platoon-adaptive-raid.lua
  lua/aibrains/platoons/platoon-simple-raid.lua
  lua/sim/NavDebug.lua
  lua/sim/NavDebug/GetPositionsInRadius.lua
  lua/sim/NavUtils.lua
Labels: area: AI, area: nav-mesh

#5862 Introduce additional lobby guards
  lua/ui/lobby/lobby.lua
Labels: area: lobby
