Repository FAForever/fa, pull requests merged in 2024-07, with the labels that each got.

#6313 Remove the code of conduct
  CODE_OF_CONDUCT.md
Labels: area: documentation

#6310 Enhance the periodic logging to help understand memory usage
  changelog/snippets/other.6310.md
  lua/simInit.lua
  lua/system/logger.lua
  lua/ui/game/gamemain.lua
  lua/userInit.lua
Labels: type: enhancement

#6316 Implement GetMousedOverWorldView
  changelog/snippets/other.6316.md
  lua/ui/game/worldview.lua
Labels: area: ui

#6322 Revert "add option to show user defined templates instead of default onland/onwater templates"
  changelog/snippets/features.5586.md
  lua/options/options.lua
  lua/ui/game/hotkeys/context-based-templates.lua
  lua/ui/help/tooltips.lua
Labels: type: bug

#6315 Document development and changelog management practices
  .github/CHANGELOG.md
  .github/DEPLOYMENT.md
  .github/DEVELOPMENT.md
  README-russian.md
  README.md
  annotation.md
  changelog.md
Labels: area: documentation

#6312 Fix radial dragger appearing when mouse isn't moved
  changelog/snippets/features.6095.md
  lua/ui/controls/draggers/radial.lua
Labels: area: ui, feature: area commands

#6317 Polish area attack dragger code and visuals
  changelog/snippets/features.6095.md
  lua/SimCallbacks.lua
  lua/shared/commands/area-attack-order.lua
  lua/sim/commands/area-attack-ground-order.lua
  lua/ui/controls/draggers/radial.lua
  lua/ui/game/hotkeys/area-attack-order.lua
Labels: area: ui, feature: area commands

#6297 Disable area reclaim command
  lua/SimCallbacks.lua
  lua/ui/game/commandmode.lua
Labels: feature: area commands

#6334 Correct the annotation for MaxHeightDiff
  engine/Core/Blueprints/WeaponBlueprint.lua
Labels: type: intellisense

#6332 Fix various small issues and update the processing of patch notes
  .vscode/settings.json
  docs/404.html
  docs/_config.yml
  docs/_include/head.html
  docs/_posts/2024-03-16-3801.md
  docs/_posts/2024-03-17-3802.md
  docs/_posts/2024-03-17-3803.md
  docs/_posts/2024-03-24-3804.md
  docs/_posts/2024-03-24-3805.md
  docs/_posts/2024-03-31-3806.md
  docs/_posts/2024-04-03-3807.md
  docs/_posts/2024-04-07-3808.md
  docs/_posts/2024-04-20-3809.md
  docs/_posts/2024-07-07-3810.md
  docs/assets/FAF-Logo.svg
  docs/assets/FAF_Logo.png
  docs/assets/favicon.ico
  docs/assets/postImage/3810.png
  docs/assets/uef-dance.gif
  docs/blender.md
  docs/changelog.md
  docs/changelogs/3810.md
  docs/changelogs/creating-changelog.md
  docs/deployment.md
  docs/development.md
  docs/development/chrashAnalysis.md
  docs/development/developmentEnviroment.md
  docs/documentation.md
  docs/favicon.ico
  docs/patches.md
Labels: area: documentation

#6326 Add page to setup development environment
  docs/assets/development/lua-debugger-01.png
  docs/development/batch-processing.md
  docs/development/engine-debugger.md
  docs/development/lua-debugger.md
  docs/development/setup.md
  docs/development/start-here.md
  init_local_development.lua
  setup/bin/dev_linux.sh
  setup/bin/dev_windows.bat
Labels: area: documentation

#6329 Better align the selection box and lifebar of two units with their mesh
  changelog/snippets/fix.6329.md
  units/DSLK004/DSLK004_unit.bp
  units/XSA0203/XSA0203_unit.bp
Labels: feature: collision shapes

#6302 [SACU Rework] : New Base Stats
  changelog/snippets/balance.6301.md
  units/UAL0301/UAL0301_unit.bp
  units/UEL0301/UEL0301_unit.bp
  units/URL0301/URL0301_unit.bp
  units/XSL0301/XSL0301_unit.bp
Labels: area: balance

#6339 Buff the shield and AA capabilities of the Fatboy
  changelog/snippets/balance.6339.md
  units/UEL0401/UEL0401_unit.bp
Labels: area: balance, DO NOT MERGE

#6335 Fix platoon bug introduced in 6083
  changelog/snippets/fix.6335.md
  lua/platoon.lua
Labels: type: bug, area: AI

#6309 Implement variable transport speeds
  changelog/snippets/features.6309.md
  loc/US/strings_db.lua
  lua/sim/units/AirTransportUnit.lua
  lua/system/blueprints-units.lua
  lua/ui/game/unitviewDetail.lua
  units/UAA0104/UAA0104_unit.bp
  units/UAA0107/UAA0107_unit.bp
  units/UEA0104/UEA0104_unit.bp
  units/UEA0107/UEA0107_unit.bp
  units/URA0104/URA0104_unit.bp
  units/URA0107/URA0107_unit.bp
  units/XEA0306/XEA0306_unit.bp
  units/XSA0104/XSA0104_unit.bp
  units/XSA0107/XSA0107_unit.bp
Labels: area: balance, DO NOT MERGE

#6321 Update Yolona's missile position after changing army
  changelog/snippets/fix.6321.md
  units/XSB2401/XSB2401_script.lua
Labels: area: graphics

#6342 Add guards to verify that the unit instance still exists
  changelog/snippets/fix.6342.md
  lua/aibrains/components/StorageManagerBrainComponent.lua
Labels: type: bug

#6303 [SACU Rework] : Quantum Gateways
  changelog/snippets/balance.6301.md
  lua/sim/AdjacencyBuffs.lua
  units/UAB0304/UAB0304_unit.bp
  units/UEB0304/UEB0304_unit.bp
  units/URB0304/URB0304_unit.bp
  units/XSB0304/XSB0304_unit.bp
Labels: area: balance

#6345 Fix a bug that could freeze up a weapon and even the simulation
  changelog/snippets/fix.6345.md
  lua/sim/weapons/DefaultProjectileWeapon.lua
  lua/sim/weapons/uef/TIFCarpetBombWeapon.lua
Labels: type: bug

#6344 1 bug hotbuild preview cycle skips selection
  lua/ui/game/commandmode.lua
Labels: type: bug

#6351 Adds a workflow to automagically verify the URLs in the documentation
  .github/workflows/docs-url-check.yaml
Labels: area: documentation

#6360 Fix various units being able to evade torpedoes due to their hitboxes being too shallow
  changelog/snippets/balance.6360.md
  units/UAB3102/UAB3102_unit.bp
  units/UAB3202/UAB3202_unit.bp
  units/UAB4201/UAB4201_unit.bp
  units/UAS0102/UAS0102_unit.bp
  units/UAS0305/UAS0305_unit.bp
  units/UEB3102/UEB3102_unit.bp
  units/UEB3202/UEB3202_unit.bp
  units/UEB4201/UEB4201_unit.bp
  units/UEL0105/UEL0105_unit.bp
  units/UEL0208/UEL0208_unit.bp
  units/UEL0309/UEL0309_unit.bp
  units/UES0305/UES0305_unit.bp
  units/URB3102/URB3102_unit.bp
  units/URB3202/URB3202_unit.bp
  units/URB4201/URB4201_unit.bp
  units/URL0105/URL0105_unit.bp
  units/URL0208/URL0208_unit.bp
  units/URL0309/URL0309_unit.bp
  units/URS0202/URS0202_unit.bp
  units/URS0305/URS0305_unit.bp
  units/XEL0209/XEL0209_unit.bp
  units/XES0102/XES0102_unit.bp
  units/XES0205/XES0205_unit.bp
  units/XSB2104/XSB2104_unit.bp
  units/XSB2304/XSB2304_unit.bp
  units/XSB3102/XSB3102_unit.bp
  units/XSB3202/XSB3202_unit.bp
  units/XSB4201/XSB4201_unit.bp
Labels: feature: collision shapes

#6363 Transfer all unbuilt units on death
  changelog/snippets/features.6363.md
  lua/SimUtils.lua
Labels: type: enhancement, area: balance, area: sim

#6366 Extend logging of various game objects
  .github/workflows/deploy-faf.yaml
  .github/workflows/deploy-fafbeta.yaml
  .github/workflows/deploy-fafdevelop.yaml
  docs/deployment.md
  init_fafbeta.lua
  init_fafdevelop.lua
  lua/shared/components/DebugComponent.lua
  lua/sim/Projectile.lua
  lua/sim/Unit.lua
  lua/sim/projectiles/components/DebugProjectileComponent.lua
  lua/sim/units/components/DebugUnitComponent.lua
  lua/sim/weapon.lua
  lua/sim/weapons/components/DebugWeaponComponent.lua
Labels: area: automated testing, area: documentation

#6364 Fix crash when enabling auto OC on non-sera SACU
  changelog/snippets/fix.6364.md
  lua/sim/units/CommandUnit.lua
Labels: type: bug, area: sim

#6355 Add information related to the Lua contexts of the game
  docs/development-start-here/lua-contexts.md
Labels: area: documentation

#6377 Introduce a debug configuration
  docs/README.md
  docs/_config_debug.yml
  docs/documentation.md
Labels: area: documentation

#6378 Apply the relative URL filter for relative URLs in the documentation
  docs/patches.md
Labels: area: documentation

#6379 Convert all images to relative URLs
  docs/404.html
  docs/_config.yml
  docs/assets/404.gif
  docs/assets/images/banner.png
  docs/assets/images/development/blender/step1.png
  docs/assets/images/development/blender/step2.png
  docs/assets/images/development/blender/step3.png
  docs/assets/images/development/blender/step4.png
  docs/assets/images/development/blender/step5.png
  docs/assets/images/development/lua/debugger-01.png
  docs/assets/images/development/lua/extension-01.png
  docs/assets/images/logo.png
  docs/assets/postImage/3810.png
  docs/blender.md
  docs/development-start-here/lua-debugger.md
  docs/development/developmentEnviroment.md
  docs/index.md
Labels: area: documentation

#6380 Improve documentation of workflows
  .github/workflows/docs-build.yml
  .github/workflows/docs-changelog.yaml
Labels: area: documentation
