Repository FAForever/fa, pull requests merged in 2024-09, with the labels that each got.

#6341 Various improvements to unitviewDetail.lua.
  changelog/snippets/features.6341.md
  loc/US/strings_db.lua
  lua/ui/game/unitviewDetail.lua
Labels: area: ui

#6432 Fix error when full share transfers units to a dead player
  changelog/snippets/fix.6432.md
  lua/aibrain.lua
Labels: type: bug, area: sim

#6447 Initialize utils before repr in RuleInit
  changelog/snippets/fix.6447.md
  lua/RuleInit.lua
  lua/globalInit.lua
Labels: type: bug

#6450 Improve beam blueprint annotations
  changelog/snippets/other.6450.md
  engine/Core/Blueprints/BeamBlueprint.lua
  engine/Core/Blueprints/EffectBlueprint.lua
Labels: type: intellisense, area: graphics

#6430 Fix an OnImpact error for CZAR depth charges
  changelog/snippets/fix.6430.md
  projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
Labels: type: bug, area: sim

#6431 Add water vision to CZAR depth charge on impact
  changelog/snippets/other.6431.md
  projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
Labels: type: nice-to-have

#6433 Add `OVERLAYINDIRECTFIRE` to Aeon destroyer so depth charge's range ring appears
  changelog/snippets/fix.6433.md
  units/UAS0201/UAS0201_unit.bp
Labels: type: bug, area: ui, area: unit-blueprint, area: unit categories

#6446 Fix the "assist to upgrade" and "assist to unpause" settings conflicting and not pausing upgraded units during lag
  changelog/snippets/fix.6446.md
  lua/ui/game/commandmode.lua
Labels: type: bug, area: ui

#6418 Add structure armor resistances to TMD armor
  changelog/snippets/fix.6418.md
  lua/armordefinition.lua
Labels: type: bug

#6419 Add nil check for GuardScanRadius in build range overlay
  changelog/snippets/fix.6419.md
  lua/system/blueprints-units.lua
Labels: type: bug, area: ui, area: unit-blueprint

#6416 Fix Salvation fire rate not being reduced when missing T1 pgens
  changelog/snippets/fix.6416.md
  lua/sim/AdjacencyBuffs.lua
Labels: type: bug

#6429 Fix GC claw aim being disrupted by walking
  changelog/snippets/fix.6429.md
  units/UAL0401/UAL0401_Script.lua
Labels: type: bug, area: sim, area: graphics

#6451 Annotate emitter blueprints
  changelog/snippets/other.6451.md
  engine/Core/Blueprints/EffectBlueprint.lua
  engine/Core/Blueprints/EmitterBlueprint.lua
Labels: type: intellisense, area: graphics

#6460 Add a workflow to automatically convert pull requests to draft
  .github/workflows/auto-draft-pr.yaml
Labels: area: tooling

#6453 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: area: documentation

#6436 Prevent the logging of an unecessary warning when certain units make landfall
  changelog/snippets/fix.6436.md
  lua/sim/Unit.lua
  units/URS0201/URS0201_unit.bp
Labels: type: bug, area: sim
