Repository FAForever/fa, pull requests merged in 2024-06, with the labels that each got.

#6003 Implement DirectionsFromWithThreatThreshold into AI transport logic
  changelog/snippets/ai.6003.md
  lua/AI/Transportutilities.lua
Labels: area: AI

#6229 Annotate `MATH_Lerp(s, sMin, sMax, a, b)`
  changelog/snippets/other.6229.md
  engine/Core.lua
Labels: type: intellisense

#6234 Fix reclaiming unbuilt units not giving back resources
  changelog/snippets/fix.6234.md
  lua/sim/Unit.lua
Labels: type: bug, area: sim

#6232 Enable the Czar's depth charges to function again
  changelog/snippets/fix.6232.md
  projectiles/AANDepthCharge01/AANDepthCharge01_script.lua
Labels: type: bug, area: balance

#6226 Improve the visual representation of the Exodus’ and Tempest’s depth charges
  changelog/snippets/other.6226.md
  projectiles/AANDepthCharge02/AANDepthCharge02_proj.bp
Labels: area: graphics

#6224 Fix the Cybran ACU's teleport weapon being displayed under 'Basics' in uvd
  changelog/snippets/fix.6224.md
  units/URL0001/URL0001_unit.bp
Labels: area: ui

#6222 Fix not being able to kick observers in team games
  changelog/snippets/fix.6222.md
  lua/ui/lobby/lobby.lua
Labels: type: bug, area: lobby

#6200 commandmode.lua callback refactor
  engine/User.lua
  lua/ui/game/commandmeshes.lua
  lua/ui/game/commandmode.lua
Labels: area: code style, area: ui

#6245 Improve details of warnings when map files are missing
  changelog/snippets/fix.6245.md
  lua/ui/dialogs/mapselect.lua
Labels: area: code style, area: lobby

#6251 Add missing localizations to faf init file mounting whitelist
  changelog/snippets/fix.6251.md
  init.lua
  init_faf.lua
  init_fafbeta.lua
  init_fafdevelop.lua
  init_shared.lua
Labels: type: bug

#6256 Fix Billy dealing wrong outer ring damage
  changelog/snippets/fix.6256.md
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_Script.lua
Labels: type: bug

#6110 Move vetDamage total inside instigator check
  changelog/snippets/fix.6110.md
  lua/defaultcomponents.lua
Labels: area: sim, area: ui, ui: unit-stats

#6252 Fix issues with fire rate test related to rounding tie-breaking towards evens
  changelog/snippets/balance.6252.md
  changelog/snippets/fix.6252.md
  tests/blueprint/unit.spec.lua
  units/UAA0310/UAA0310_unit.bp
  units/UEB2204/UEB2204_unit.bp
  units/UEL0202/UEL0202_unit.bp
  units/URS0202/URS0202_unit.bp
  units/XAA0305/XAA0305_unit.bp
  units/XRL0403/XRL0403_unit.bp
  units/XSA0203/XSA0203_unit.bp
Labels: type: bug, area: automated testing

#6228 Fix several flaks consistently missing their first shot at specific angles
  changelog/snippets/fix.6228.md
  lua/sim/weapons/aeon/AAATemporalFizzWeapon.lua
  lua/sim/weapons/seraphim/SAAOlarisCannonWeapon.lua
  units/UAA0310/UAA0310_unit.bp
  units/UAB2204/UAB2204_script.lua
  units/UAB2204/UAB2204_unit.bp
  units/UAL0205/UAL0205_script.lua
  units/UAL0205/UAL0205_unit.bp
  units/XSB2204/XSB2204_unit.bp
  units/XSL0205/XSL0205_unit.bp
Labels: area: unit-blueprint

#5249 Adjust engineer filter key
  changelog/snippets/features.5249.md
  lua/keymap/keydescriptions.lua
  lua/ui/game/hotkeys/filter-engineers.lua
Labels: status: need rework

#6265 Implement the blinking lights at a unit level
  lua/aibrains/components/AIBrainStorageComponent.lua
  lua/sim/units/EnergyStorageUnit.lua
  lua/sim/units/FactoryUnit.lua
  lua/sim/units/MassStorageUnit.lua
  lua/sim/units/RadarUnit.lua
  lua/sim/units/SonarUnit.lua
  lua/sim/units/StructureUnit.lua
  lua/sim/units/components/BlinkingLightsUnitComponent.lua
Labels: area: graphics

#6266 Fix the blinking lights of the storage structures
  units/UAB1105/UAB1105_unit.bp
  units/UAB1106/UAB1106_unit.bp
  units/UEB1105/UEB1105_LOD0.scm
  units/UEB1105/UEB1105_unit.bp
  units/UEB1106/UEB1106_LOD0.scm
  units/UEB1106/UEB1106_unit.bp
  units/URB1105/URB1105_LOD0.scm
  units/URB1105/URB1105_unit.bp
  units/URB1106/URB1106_LOD0.scm
  units/URB1106/URB1106_unit.bp
  units/XSB1105/XSB1105_unit.bp
  units/XSB1106/XSB1106_unit.bp
Labels: area: graphics

#6258 Make shields absorb full overcharge damage
  changelog/snippets/fix.6258.md
  lua/ShieldAbsorptionValues.lua
  lua/shield.lua
Labels: type: bug, area: sim

#6268 Improve performance and readability of the jammer manager brain component
  lua/aibrains/components/JammerManagerBrainComponent.lua
Labels: area: code style

#6267 Rework the brain components
  lua/aibrain.lua
  lua/aibrains/components/EnergyManagerBrainComponent.lua
  lua/aibrains/components/FactoryManagerBrainComponent.lua
  lua/aibrains/components/JammerManagerBrainComponent.lua
  lua/aibrains/components/StatManagerBrainComponent.lua
Labels: area: code style

#6227 Evaluate the hitboxes of several units
  changelog/snippets/fix.6227.md
  units/DALK003/DALK003_unit.bp
  units/DRL0204/DRL0204_unit.bp
  units/UAL0205/UAL0205_unit.bp
  units/UAL0307/UAL0307_unit.bp
  units/URL0104/URL0104_unit.bp
  units/URL0107/URL0107_unit.bp
  units/XSL0103/XSL0103_unit.bp
Labels: feature: collision shapes

#5656 Allow Hotbuild to redirect orders to exfac units like the buttons do
  lua/keymap/hotbuild.lua
  lua/system/utils.lua
Labels: feature: mobile factories, feature: hotkeys

#5658 Move classes of UEF projectiles to separate files
  lua/sim/projectiles/uef/TAAGinsuRapidPulseBeamProjectile.lua
  lua/sim/projectiles/uef/TAALightFragmentationProjectile.lua
  lua/sim/projectiles/uef/TAntiNukeInterceptorProjectile.lua
  lua/sim/projectiles/uef/TArtilleryAntiMatterProjectile.lua
  lua/sim/projectiles/uef/TArtilleryAntiMatterProjectile02.lua
  lua/sim/projectiles/uef/TArtilleryAntiMatterSmallProjectile.lua
  lua/sim/projectiles/uef/TArtilleryProjectile.lua
  lua/sim/projectiles/uef/TArtilleryProjectilePolytrail.lua
  lua/sim/projectiles/uef/TCannonSeaProjectile.lua
  lua/sim/projectiles/uef/TCannonTankProjectile.lua
  lua/sim/projectiles/uef/TDFBigLandGaussCannonProjectile.lua
  lua/sim/projectiles/uef/TDFBigShipGaussCannonProjectile.lua
  lua/sim/projectiles/uef/TDFGaussCannonProjectile.lua
  lua/sim/projectiles/uef/TDFGeneralGaussCannonProjectile.lua
  lua/sim/projectiles/uef/TDFMediumLandGaussCannonProjectile.lua
  lua/sim/projectiles/uef/TDFMediumShipGaussCannonProjectile.lua
  lua/sim/projectiles/uef/TDepthChargeProjectile.lua
  lua/sim/projectiles/uef/TFragmentationGrenadeProjectile.lua
  lua/sim/projectiles/uef/THeavyPlasmaCannonProjectile.lua
  lua/sim/projectiles/uef/TIFMissileNukeProjectile.lua
  lua/sim/projectiles/uef/TIFSmallYieldNuclearBombProjectile.lua
  lua/sim/projectiles/uef/TIFTacticalNukeProjectile.lua
  lua/sim/projectiles/uef/TLaserBotProjectile.lua
  lua/sim/projectiles/uef/TLaserProjectile.lua
  lua/sim/projectiles/uef/TMachineGunProjectile.lua
  lua/sim/projectiles/uef/TMissileAAProjectile.lua
  lua/sim/projectiles/uef/TMissileCruiseProjectile.lua
  lua/sim/projectiles/uef/TMissileCruiseProjectile02.lua
  lua/sim/projectiles/uef/TMissileProjectile.lua
  lua/terranprojectiles.lua
Labels: area: code style

#6243 Fix production queue tooltip in non-default layouts
  changelog/snippets/fix.6243.md
  lua/ui/game/layouts/unitview_left.lua
  lua/ui/game/layouts/unitview_mini.lua
  lua/ui/game/layouts/unitview_right.lua
  lua/ui/game/unitview.lua
Labels: type: bug, area: ui

#6273 Fix compatibility issues with Lua 5.4
  lua/system/blueprints-units.lua
Labels: area: code style

#4578 Add ability to invert panning direction with middle mouse button
  changelog/snippets/features.4578.md
  engine/User.lua
  lua/options/options.lua
Labels: area: ui

#6280 Increase mass fab throttle maximum energy storage to allow for full damage overcharge
  changelog/snippets/fix.6280.md
  lua/shared/FabricatorBehaviorParams.lua
Labels: area: sim

#6235 Rebalance the Tempest and the Atlantis
  changelog/snippets/balance.6235.md
  units/UAS0401/UAS0401_unit.bp
  units/UES0401/UES0401_unit.bp
Labels: area: balance, DO NOT MERGE

#6282 Display economy values as decimals in unit viewer
  changelog/snippets/features.6282.md
  engine/User/UserUnit.lua
  lua/ui/game/unitview.lua
Labels: area: ui

#6287 Fix intel state not being assigned
  lua/system/blueprints-units.lua
Labels: type: bug

#6288 Improve guards for `table.copy` to fix blueprint reloading crash
  lua/system/utils.lua
Labels: type: bug

#6285 Fix sub-optimal drag build of the air grid template
  changelog/snippets/fix.6285.md
  lua/ui/game/hotkeys/context-based-templates-data/AppendAirGrid.lua
Labels: type: bug, feature: context-based templates

#6277 Fix bombers not keeping track of attack ground tries
  changelog/snippets/fix.6277.md
  engine/Core/Blueprints/WeaponBlueprint.lua
  engine/Sim/UnitWeapon.lua
  lua/sim/weapons/DefaultProjectileWeapon.lua
Labels: type: bug, area: sim, feature: weapon firing cycle

#6286 AI - Fix incorrect unit set in T2LandAmphibious factory build template
  changelog/snippets/ai.6286.md
  lua/AI/PlatoonTemplates/LandPlatoonTemplates.lua
  lua/platoontemplates.lua
Labels: area: AI

#5810 Rotate every other texture layer
  changelog/snippets/graphics.5810.md
  effects/terrain.fx
Labels: area: graphics

#6293 Fix mod backwards compatibility in Aeon weapon files
  changelog/snippets/fix.6293.md
  lua/aeonweapons.lua
  lua/cybranweapons.lua
  lua/seraphimweapons.lua
  lua/terranweapons.lua
Labels: area: code style, type: regression

#5883 Re-implement Chrono Dampener to properly use firing cycle + VFX fixes
  changelog/snippets/balance.5883.md
  changelog/snippets/fix.5883.md
  changelog/snippets/other.5883.md
  effects/emitters/aeon_chrono_dampener_large_01_emit.bp
  effects/emitters/aeon_chrono_dampener_large_02_emit.bp
  effects/emitters/aeon_chrono_dampener_large_03_emit.bp
  effects/emitters/aeon_chrono_dampener_large_04_emit.bp
  loc/US/strings_db.lua
  lua/EffectTemplates.lua
  lua/sim/weapons/aeon/ADFChronoDampener.lua
  lua/ui/help/unitdescription.lua
  units/UAL0001/UAL0001_script.lua
  units/UAL0001/UAL0001_unit.bp
Labels: area: balance, area: sim, area: graphics, feature: weapon firing cycle, feature: target priorities

#6295 Use LOD instead of always emitting for Chrono visuals
  effects/emitters/aeon_chrono_dampener_large_02_emit.bp
  effects/emitters/aeon_chrono_dampener_large_04_emit.bp
Labels: type: bug, area: graphics

#6296 Don't block death nukes with mobile shields.
  changelog/snippets/balance.6060.md
  lua/ShieldAbsorptionValues.lua
  lua/shield.lua
  units/UAB4202/UAB4202_unit.bp
  units/UAB4301/UAB4301_unit.bp
  units/UEB4202/UEB4202_unit.bp
  units/UEB4301/UEB4301_unit.bp
  units/URB4202/URB4202_unit.bp
  units/URB4204/URB4204_unit.bp
  units/URB4205/URB4205_unit.bp
  units/URB4206/URB4206_unit.bp
  units/URB4207/URB4207_unit.bp
  units/XAC2101/XAC2101_unit.bp
  units/XSB4202/XSB4202_unit.bp
  units/XSB4301/XSB4301_unit.bp
Labels: area: balance

#6289 Revert FiringState OnLostTarget working through HaltFire
  changelog/snippets/fix.6289.md
  lua/sim/weapons/DefaultProjectileWeapon.lua
Labels: type: bug, area: sim, feature: weapon firing cycle

#5586 add option to show user defined templates instead of default onland/onwater templates
  changelog/snippets/features.5586.md
  lua/options/options.lua
  lua/ui/game/hotkeys/context-based-templates.lua
  lua/ui/help/tooltips.lua
Labels: feature: context-based templates

#6220 Move build range overlay creation to post-mod blueprint loading
  changelog/snippets/features.6220.md
  lua/system/Blueprints.lua
  lua/system/blueprints-units.lua
Labels: type: bug, area: ui, area: unit-blueprint

#6311 Move hidden crash damage out of Ahwassa and CZAR scripts
  changelog/snippets/fix.6311.md
  units/UAA0310/UAA0310_script.lua
  units/UAA0310/UAA0310_unit.bp
  units/XSA0402/XSA0402_script.lua
  units/XSA0402/XSA0402_unit.bp
Labels: area: balance, area: ui, area: unit-blueprint, ui: unit-stats

#5587 Fix error when deleting last template
  changelog/snippets/fix.5587.md
  lua/ui/game/construction.lua
Labels: type: bug, feature: context-based templates

#6160 Show player divisions in scoreboard
  changelog/snippets/features.6160.md
  lua/ui/game/score.lua
  lua/ui/lobby/autolobby.lua
Labels: area: ui, ui: scoreboard, type: testing needed
