Repository FAForever/fa, pull requests merged in 2024-05, with the labels that each got.

#6132 Clean up unused FiringRandomness stat from Ahwassa's bomb
  changelog/snippets/other.6132.md
  units/XSA0402/XSA0402_unit.bp
Labels: area: unit-blueprint

#6141 Increase the muzzle velocity of the Hoplite's rockets
  changelog/snippets/balance.6141.md
  units/DRL0204/DRL0204_unit.bp
Labels: area: balance, DO NOT MERGE

#6029 Show loyalist death weapon in UI
  changelog/snippets/other.6029.md
  units/URL0303/URL0303_Script.lua
  units/URL0303/URL0303_unit.bp
Labels: area: ui, ui: unit-stats

#6115 Fix UnitViewDetail beam damage calculation
  changelog/snippets/fix.6115.md
  lua/ui/game/unitviewDetail.lua
Labels: area: ui, ui: unit-stats

#6142 Fix Salvation being unable to fire to max range
  changelog/snippets/fix.6142.md
  units/XAB2307/XAB2307_unit.bp
Labels: type: bug, area: unit-blueprint

#6083 platoon.lua annotations and warning fixes [lua/platoon.lua]
  changelog/snippets/ai.6083.md
  lua/platoon.lua
Labels: type: intellisense

#6084 platoon.lua annotation and warning fixes [auxiliary files]
  engine/Core.lua
  engine/Sim/CAiBrain.lua
  engine/Sim/CPlatoon.lua
  engine/Sim/Unit.lua
  lua/AI/AIBehaviors.lua
  lua/AI/OpAI/BaseManager.lua
  lua/AI/aibuildstructures.lua
  lua/AI/sorianutilities.lua
  lua/aibrain.lua
  lua/aibrains/base-ai.lua
  lua/aibrains/campaign-ai.lua
  lua/shared/NavGenerator.lua
  lua/sim/Builder.lua
  lua/sim/Unit.lua
  lua/system/utils.lua
Labels: type: intellisense

#6085 platoon.lua annotation and warning fixes [lua/AI/aiutilities.lua]
  lua/AI/aiutilities.lua
Labels: type: intellisense

#6131 Balance idea: UEF ACU Bubble Shield 🛡️ #6130
  changelog/snippets/balance.6130.md
  units/UEL0001/UEL0001_unit.bp
Labels: area: balance, DO NOT MERGE

#6150 Nerf `Size20` (Salvation) `RateOfFire` adjacency
  changelog/snippets/balance.6150.md
  lua/sim/AdjacencyBuffs.lua
Labels: area: balance, DO NOT MERGE

#6140 Slightly buff the Vulthoo
  units/XSA0203/XSA0203_unit.bp
Labels: area: balance, DO NOT MERGE

#6156 Update `OnAdjacentTo` annotation comment
  changelog/snippets/other.6156.md
  lua/sim/units/StructureUnit.lua
Labels: area: code style

#6147 Improve comments in water2.fx
  changelog/snippets/other.6147.md
  effects/water2.fx
Labels: area: code style, area: graphics

#6144 Fix gunships trailing behind quick units and not being able to engage them
  changelog/snippets/balance.6034.md
  changelog/snippets/balance.6082.md
  changelog/snippets/balance.6130.md
  changelog/snippets/fix.6144.md
  units/UAA0203/UAA0203_unit.bp
  units/UEA0203/UEA0203_unit.bp
  units/UEA0305/UEA0305_unit.bp
  units/URA0203/URA0203_unit.bp
  units/URA0401/URA0401_unit.bp
  units/XAA0305/XAA0305_unit.bp
  units/XRA0105/XRA0105_unit.bp
  units/XRA0305/XRA0305_unit.bp
  units/XSA0203/XSA0203_unit.bp
Labels: area: sim

#6033 Fix defensive and arty structure orientations on build.
  changelog/snippets/features.6033.md
  changelog/snippets/fix.6033.md
  lua/defaultunits.lua
  lua/sim/units/StructureUnit.lua
Labels: area: sim

#5948 Create capture cost reticle
  changelog/snippets/features.5948.md
  lua/shared/captureCost.lua
  lua/shared/observable.lua
  lua/sim/Unit.lua
  lua/ui/controls/reticles/capture.lua
  lua/ui/controls/reticles/teleport.lua
  lua/ui/controls/worldview.lua
  lua/ui/game/gamemain.lua
Labels: area: ui

#6173 Use tooltip class for order buttons' tooltips instead of custom code
  changelog/snippets/other.6173.md
  lua/ui/game/orders.lua
Labels: area: ui

#6168 Allow various submarines without deck guns to surface again
  changelog/snippets/fix.6168.md
  units/UAS0203/UAS0203_unit.bp
  units/UAS0304/UAS0304_unit.bp
  units/UES0304/UES0304_unit.bp
  units/URS0304/URS0304_unit.bp
  units/XAS0204/XAS0204_unit.bp
  units/XRS0204/XRS0204_unit.bp
Labels: type: bug, area: sim

#6154 Update Ythotha tread mark textures.
  changelog/snippets/graphics.6154.md
  env/Common/splats/ythotha_tread_left_01.dds
  env/Common/splats/ythotha_tread_right_01.dds
  units/XSL0401/XSL0401_unit.bp
Labels: area: graphics

#6143 Pull threads out of functions
  engine/Core.lua
  lua/ScenarioFramework.lua
  lua/SimPing.lua
  lua/SimPingGroup.lua
  lua/aibrain.lua
  lua/defaultantiprojectile.lua
  lua/sim/MatchState.lua
  lua/sim/ScenarioUtilities.lua
  lua/sim/Unit.lua
  lua/sim/weapons/DefaultProjectileWeapon.lua
  lua/sim/weapons/OverchargeWeapon.lua
  lua/simInit.lua
  lua/ui/controls/worldview.lua
  lua/ui/dialogs/saveload.lua
  lua/ui/game/chat.lua
  lua/ui/game/construction.lua
  lua/ui/game/gamemain.lua
  lua/ui/game/multifunction.lua
  lua/ui/game/reclaim.lua
  lua/victory.lua
Labels: area: code style

#6174 Cherry-pick lobby annotations
  changelog/snippets/other.6174.md
  engine/User.lua
  engine/User/CDiscoveryService.lua
  engine/User/CLobby.lua
  lua/ui/lobby/lobbyComm.lua
Labels: area: code style, area: ui, area: lobby

#6163 Fix Miasma shield penetration
  lua/sim/projectiles/aeon/AMiasmaProjectile.lua
  projectiles/AIFMiasmaShell01/AIFMiasmaShell01_proj.bp
  projectiles/AIFMiasmaShell01/AIFMiasmaShell01_script.lua
Labels: area: balance

#6159 Fix pause_unit_all and unpause_unit_all Hotkey Behavior
  changelog/snippets/fix.6159.md
  lua/ui/game/construction.lua
Labels: area: ui, feature: hotkeys

#6178 Enable the Pulsar to be built using hotkeys
  changelog/snippets/other.6178.md
  lua/keymap/unitkeygroups.lua
  lua/ui/game/buildmodedata.lua
Labels: area: ui, feature: hotkeys

#6179 Ilshy Turn Rate Buff
  changelog/snippets/balance.6179.md
  units/XSL0202/XSL0202_unit.bp
Labels: area: balance

#6181 Annotate fields related to bombs
  changelog/snippets/other.6181.md
  engine/Core/Blueprints/ProjectileBlueprint.lua
  engine/Core/Blueprints/WeaponBlueprint.lua
  engine/Sim/Projectile.lua
  lua/sim/weapons/DefaultProjectileWeapon.lua
Labels: area: sim, type: intellisense

#6103 Othuum Responsiveness and Range Buff
  changelog/3810.md
  engine/Core/Blueprints/UnitBlueprint.lua
  units/XSL0303/XSL0303_unit.bp
Labels: area: balance, DO NOT MERGE

#6028 Fix wrong splash radius decal appearing for certain units
  changelog/snippets/fix.6028.md
  lua/ui/controls/worldview.lua
Labels: type: bug, area: ui

#6198 Fix small bugs in the wiki generation script
  .github/workflows/wiki-generate-blueprints.yaml
  .github/workflows/wiki-generate-icons.yaml
  changelog/snippets/other.6188.md
Labels: type: bug

#6195 Further improve the Chariot's hitbox
  changelog/snippets/fix.6195.md
  units/UAA0107/UAA0107_unit.bp
Labels: feature: collision shapes

#6194 Fix AI rating for sub-1.0 ratings
  lua/ui/lobby/lobby.lua
Labels: area: lobby, area: AI

#6175 Rework UnitsTooltip to use Layouter to fix its UI scaling
  changelog/snippets/fix.6175.md
  lua/ui/lobby/UnitsTooltip.lua
Labels: type: bug, area: ui, ui: unit-manager

#6201 Fix rounding in beam damage calculation
  changelog/snippets/fix.6115.md
  lua/ui/game/unitviewDetail.lua
  units/DSLK004/DSLK004_unit.bp
Labels: area: ui, ui: unit-stats

#6208 Fix sound regression
  lua/SimSyncUtils.lua
  lua/UserSync.lua
  lua/aibrain.lua
Labels: type: bug

#6209 Fix log spam from spawn dummies when reloading blueprints
  changelog/snippets/fix.6209.md
  lua/system/Blueprints.lua
Labels: area: automated testing

#6211 Buff/fix the Wailer's AA-missiles
  changelog/snippets/balance.6211.md
  units/XRA0305/XRA0305_unit.bp
Labels: type: bug, area: balance

#6213 Revert change in default teleport time
  changelog/snippets/fix.6213.md
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/shared/teleport.lua
Labels: area: balance, area: sim, type: regression, feature: teleportation

#6121 Fix UEF SACU fire rate upgrade using inaccurate fire rate value
  changelog/snippets/fix.6121.md
  loc/RU/strings_db.lua
  loc/US/strings_db.lua
  tests/blueprint/unit.spec.lua
  units/UEL0301/UEL0301_unit.bp
Labels: area: unit-blueprint

#6212 Command Queue Annotations
  engine/Sim/Unit.lua
  engine/User.lua
  lua/sim/Unit.lua
Labels: area: code style, type: intellisense

#6192 Fatboy unit detach bug + exFac footprint fix
  changelog/snippets/fix.6192.md
  units/UEL0401/UEL0401_script.lua
  units/ZXA0003/ZXA0003_unit.bp
Labels: type: bug, feature: mobile factories

#6048 AI - Increase distance limits for Naval Area marker generation
  changelog/snippets/ai.6048.md
  lua/sim/MarkerUtilities/NavalAreas.lua
Labels: area: AI

#6218 Annotate auto assist in `InitialAutoMode` and `SetAutoMode`
  changelog/snippets/other.6218.md
  engine/Core/Blueprints/UnitBlueprint.lua
  engine/Sim/Unit.lua
  engine/User.lua
  units/UAL0111/UAL0111_unit.bp
  units/UEA0001/UEA0001_unit.bp
  units/UEA0003/UEA0003_unit.bp
  units/UEL0111/UEL0111_unit.bp
  units/UES0202/UES0202_unit.bp
  units/URL0111/URL0111_unit.bp
  units/XEL0306/XEL0306_unit.bp
  units/XSL0111/XSL0111_unit.bp
Labels: area: code style

#6217 Clarify hotbuild keybind collision warning
  changelog/snippets/other.6217.md
  lua/keymap/keymapper.lua
Labels: area: ui

#6176 Assisting engineers track new construction orders
  changelog/snippets/features.6169.md
  lua/sim/Unit.lua
  lua/sim/commands/abort-navigation.lua
  lua/sim/units/uef/TConstructionPodUnit.lua
  lua/terranunits.lua
  units/UEA0001/UEA0001_script.lua
  units/UEA0003/UEA0003_script.lua
  units/UEL0001/UEL0001_script.lua
  units/UEL0301/UEL0301_script.lua
Labels: area: sim

#5759 Code Formatting Units V1
  changelog/snippets/fix.5759.md
  changelog/snippets/other.5759.md
  engine/Sim.lua
  engine/Sim/CRotateManipulator.lua
  lua/seraphimweapons.lua
  lua/sim/collisionBeams/LightningSmallCollisionBeam.lua
  lua/sim/collisionBeams/LightningSmallSurfaceCollisionBeam.lua
  lua/sim/weapons/seraphim/SAALightningWeapon.lua
  units/DAA0206/DAA0206_script.lua
  units/DAL0310/DAL0310_Script.lua
  units/DEA0202/DEA0202_Script.lua
  units/DELK002/DELK002_script.lua
  units/DRA0202/DRA0202_Script.lua
  units/DRLK001/DRLK001_Script.lua
  units/DSLK004/DSLK004_script.lua
  units/DSLK004/DSLK004_unit.bp
  units/UAA0104/UAA0104_script.lua
  units/UAA0203/UAA0203_script.lua
  units/UAA0304/UAA0304_Script.lua
  units/UAA0310/UAA0310_script.lua
  units/UAB0303/UAB0303_script.lua
  units/UAB0304/UAB0304_script.lua
  units/UAB1102/UAB1102_script.lua
  units/UAB1103/UAB1103_script.lua
  units/UAB1104/UAB1104_Script.lua
  units/UAB1106/UAB1106_script.lua
  units/UAB1201/UAB1201_script.lua
  units/UAB1301/UAB1301_script.lua
  units/UAB1302/UAB1302_script.lua
  units/UAB1303/UAB1303_script.lua
  units/UAB2109/UAB2109_script.lua
  units/UAB2204/UAB2204_script.lua
  units/UAB2205/UAB2205_script.lua
  units/UAB2305/UAB2305_script.lua
  units/UAB3101/UAB3101_script.lua
  units/UAB3104/UAB3104_script.lua
  units/UAB3201/UAB3201_script.lua
  units/UAB4201/UAB4201_script.lua
  units/UAB4202/UAB4202_script.lua
  units/XSL0402/XSL0402_script.lua
Labels: area: code style

#6216 Fix unit tooltip docking for non-startup layouts
  changelog/snippets/fix.6216.md
  lua/ui/game/unitview.lua
Labels: type: bug, area: ui

#5906 Allow Ctrl to bypass Alt to force attack move
  changelog/features.5906.md
  lua/ui/controls/worldview.lua
  lua/ui/help/tooltips.lua
Labels: area: ui

#6207 Fix free intel not being toggleable
  changelog/snippets/fix.6207.md
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/defaultcomponents.lua
  lua/sim/Unit.lua
  lua/sim/units/cybran/CCommandUnit.lua
  lua/system/blueprints-units.lua
  units/URL0301/URL0301_script.lua
Labels: type: bug, area: sim, area: unit-blueprint
