Repository FAForever/fa, pull requests merged in 2024-10, with the labels that each got.

#6471 Fix xsb5101 not orientating to the terrain as intended
  changelog/snippets/fix.6471.md
  units/XSB5101/XSB5101_unit.bp
Labels: type: bug, area: unit-blueprint

#6409 Update the deployment procedure
  .github/workflows/docs-url-check.yaml
  docs/deployment.md
Labels: area: documentation

#6469 Reduce the `TransportSpeedReduction` stat of the Fire Beetle
  changelog/snippets/balance.6469.md
  units/XRL0302/XRL0302_unit.bp
Labels: area: balance

#6463 Remove the hotkey to kill all your units
  changelog/snippets/other.6463.md
  lua/keymap/keyactions.lua
  lua/selfdestruct.lua
  lua/ui/game/confirmunitdestroy.lua
Labels: feature: hotkeys

#6444 Create workflow converting markdown-based changlog to lua-based changelog
  .github/workflows/docs-build.yml
  .github/workflows/docs-changelog.yaml
  .github/workflows/docs-convert-changelog.yaml
  .github/workflows/scripts/bash/changelog-combine.sh
  .github/workflows/scripts/bash/changelog-links.sh
  .github/workflows/scripts/bash/changelog-verify.sh
  .github/workflows/scripts/python/README.md
  .github/workflows/scripts/python/changelog_markdown2lua.py
  .github/workflows/scripts/python/requirements.txt
  .github/workflows/scripts/python/setup_python_env.sh
  .gitignore
  changelog/snippets/other.6237.md
  changelog/snippets/other.6238.md
  tests/run-syntax-test.sh
Labels: area: automated testing, area: changelog management, area: documentation

#6467 Fix a crash if a unit has an enhancements table but not an intel table
  changelog/snippets/fix.6467.md
  lua/system/blueprints-units.lua
Labels: type: bug

#6474 Implement command line launch of the auto lobby for LAN games
  changelog/snippets/other.6474.md
  engine/User.lua
  lua/system/utils.lua
  lua/ui/lobby/autolobby.lua
  lua/ui/uimain.lua
  scripts/LaunchFAInstances.ps1
Labels: type: enhancement, area: ui

#6424 UnitviewDetail.lua: Introduce total DPS calculations
  changelog/snippets/features.6424.md
  loc/US/strings_db.lua
  lua/ui/game/unitviewDetail.lua
  units/URL0101/URL0101_unit.bp
  units/XSL0303/XSL0303_unit.bp
Labels: area: ui

#6465 Improve the visual representation of multiple projectiles by increasing their `StrategicIconSize`
  changelog/snippets/features.6465.md
  projectiles/SDFSniperShot02/SDFSniperShot02_proj.bp
  projectiles/SDFTauCannon01/SDFTauCannon01_proj.bp
  projectiles/TDFIonizedPlasmaGatlingCannon01/TDFIonizedPlasmaGatlingCannon01_proj.bp
Labels: feature: strategic icons

#6428 Implement a Dual Yaw turret controller so that Loyalist can fully aim its secondary
  changelog/snippets/features.6428.md
  engine/Core/Blueprints/WeaponBlueprint.lua
  lua/sim/weapon.lua
  units/URL0303/URL0303_unit.bp
Labels: type: bug, type: enhancement, area: sim

#6438 Finalize "Update vector processing" (#5061)
  changelog/snippets/fix.6438.md
  changelog/snippets/other.6438.md
  engine/Core.lua
  engine/Sim.lua
  lua/benchmarking/benchmarks/VDist2.lua
  lua/benchmarking/benchmarks/VDist3.lua
  lua/benchmarking/controller.lua
  lua/defaultexplosions.lua
  lua/defaultunits.lua
  lua/shared/quaternions.lua
  lua/sim/Projectile.lua
  lua/sim/ScenarioUtilities.lua
  lua/sim/TerrainUtils.lua
  lua/sim/Unit.lua
  lua/sim/units/StructureUnit.lua
  lua/system/utils.lua
  lua/utilities.lua
  tests/utility/string.spec.lua
  units/UAL0401/UAL0401_Script.lua
  units/URL0402/URL0402_script.lua
  units/XRL0403/XRL0403_script.lua
Labels: area: code style

#6458 Annotate the damage data passed from weapons to projectiles
  changelog/snippets/sections/other.6458.md
  lua/sim/CollisionBeam.lua
  lua/sim/Projectile.lua
  lua/sim/weapon.lua
Labels: area: sim, type: intellisense

#6480 Fix movement effects warning spam due to contrails
  changelog/snippets/fix.6436.md
  lua/sim/Unit.lua
Labels: type: bug, area: sim

#6495 Refactor of `maputils.lua`
  changelog/snippets/other.6495.md
  engine/User.lua
  etc/faf/mapblacklist.lua
  lua/ui/dialogs/mapselect.lua
  lua/ui/maputil.lua
Labels: area: code style

#6494 Fix a crash when the `EnableDiskWatch` command line argument is enabled
  changelog/snippets/fix.6494.md
  lua/system/blueprints-units.lua
Labels: type: bug
