Repository FAForever/fa, pull requests merged in 2024-03, with the labels that each got.

#5929 Evaluate and rework the categories of UEF naval units
  engine/Core/Categories.lua
  units/UES0103/UES0103_unit.bp
  units/UES0201/UES0201_unit.bp
  units/UES0202/UES0202_unit.bp
  units/UES0203/UES0203_unit.bp
  units/UES0302/UES0302_unit.bp
  units/UES0305/UES0305_unit.bp
  units/XES0307/XES0307_unit.bp
Labels: feature: target priorities

#5934 T3 Cybran Strat bomber - ANTIAIRWEAK added
  units/URA0304/URA0304_unit.bp
Labels: feature: target priorities

#5935 T3 Cybran Gunship AA weak added
  units/XRA0305/XRA0305_unit.bp
Labels: feature: target priorities

#5928 Evaluate and rework the categories of UEF air units
  units/UEA0103/UEA0103_unit.bp
  units/UEA0104/UEA0104_unit.bp
  units/UEA0304/UEA0304_unit.bp
  units/UEA0305/UEA0305_unit.bp
Labels: feature: target priorities

#5930 Adds WEAKDIRECTFIRE/WEAKANTIAIR to Cybran T2 transport
  units/URA0104/URA0104_unit.bp
Labels: feature: target priorities

#5942 Update the use of `STRATEGIC` category
  lua/ui/lobby/UnitsAnalyzer.lua
  lua/ui/lobby/UnitsRestrictions.lua
  units/UAB2302/UAB2302_unit.bp
  units/UAB5202/UAB5202_unit.bp
  units/UEB2302/UEB2302_unit.bp
  units/UEB2401/UEB2401_unit.bp
  units/UEB5202/UEB5202_unit.bp
  units/URB2302/URB2302_unit.bp
  units/URB5202/URB5202_unit.bp
  units/URL0401/URL0401_unit.bp
  units/XAB1401/XAB1401_unit.bp
  units/XAB2307/XAB2307_unit.bp
  units/XEB2402/XEB2402_unit.bp
  units/XSB2302/XSB2302_unit.bp
  units/XSB5202/XSB5202_unit.bp
Labels: feature: target priorities

#5951 Filter all whitespace from UI weapon priority strings
  lua/WeaponPriorities.lua
Labels: feature: target priorities

#5958 Fix SACUs having less effective range due to low projectile lifetimes
  units/UAL0301/UAL0301_unit.bp
  units/UEL0301/UEL0301_unit.bp
  units/URL0301/URL0301_unit.bp
  units/XSL0301/XSL0301_unit.bp
Labels: type: bug, area: balance

#5960 Rework the representation of the high-value tactical missiles
  effects/emitters/cybran_missile_hit_02_emit.bp
  effects/emitters/cybran_missile_hit_03_emit.bp
  lua/EffectTemplates.lua
  lua/sim/projectiles/components/DebrisComponent.lua
  projectiles/AIFMissileTactical01/AIFMissileTactical01_Script.lua
  projectiles/AIFMissileTactical01/AIFMissileTactical01_proj.bp
  projectiles/CIFMissileTactical03/CIFMissileTactical03_Script.lua
  projectiles/CIFMissileTactical03/CIFMissileTactical03_proj.bp
  projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_Script.lua
  projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_proj.bp
  projectiles/TIFMissileCruise01/TIFMissileCruise01_Script.lua
  projectiles/TIFMissileCruise01/TIFMissileCruise01_proj.bp
  projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_proj.bp
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_proj.bp
  textures/ui/common/game/strategicicons/icon_tactical_missile.png
  textures/ui/common/game/strategicicons/icon_tactical_nuke_missile.png
Labels: feature: tactical missiles

#5961 Rework (sound) effects of valuable tactical missiles
  projectiles/AIFMissileSerpentine01/AIFMissileSerpentine01_script.lua
  projectiles/AIFMissileSerpentine02/AIFMissileSerpentine02_proj.bp
  projectiles/AIFMissileSerpentine02/AIFMissileSerpentine02_script.lua
  projectiles/AIFMissileSerpentine03/AIFMissileSerpentine03_Script.lua
  projectiles/AIFMissileTactical01/AIFMissileTactical01_proj.bp
  projectiles/AIFMissileTactical02/AIFMissileTactical02_Script.lua
  projectiles/AIFMissileTactical02/AIFMissileTactical02_proj.bp
  projectiles/CIFMissileTactical02/CIFMissileTactical02_Script.lua
  projectiles/CIFMissileTactical02/CIFMissileTactical02_proj.bp
  projectiles/CIFMissileTactical03/CIFMissileTactical03_Script.lua
  projectiles/CIFMissileTactical03/CIFMissileTactical03_proj.bp
  projectiles/SIFLaanseTacticalMissile04/SIFLaanseTacticalMissile04_proj.bp
  projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_proj.bp
  projectiles/SIFLaanseTacticalMissileCDR/SIFLaanseTacticalMissileCDR_script.lua
  projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_proj.bp
  projectiles/SIFLaanseTacticalMissileSCU/SIFLaanseTacticalMissileSCU_script.lua
  projectiles/TIFMissileCruise01/TIFMissileCruise01_Script.lua
  projectiles/TIFMissileCruise01/TIFMissileCruise01_proj.bp
  projectiles/TIFMissileCruise02/TIFMissileCruise02_proj.bp
  projectiles/TIFMissileCruise02/TIFMissileCruise02_script.lua
  projectiles/TIFMissileCruiseCDR/TIFMissileCruiseCDR_proj.bp
  projectiles/TIFMissileNukeCDR/TIFMissileNukeCDR_proj.bp
  textures/ui/common/game/strategicicons/icon_tactical_missile.dds
  textures/ui/common/game/strategicicons/icon_tactical_nuke_missile.dds
Labels: feature: tactical missiles

#5967 Evaluate and rework the categories of cybran naval units
  units/URS0302/URS0302_unit.bp
Labels: area: unit categories

#5845 Add tests for rate of fire
  .github/workflows/test.yaml
  tests/blueprint/unit.spec.lua
  tests/run-blueprint-tests.sh
  units/DRLK001/DRLK001_unit.bp
  units/UAA0310/UAA0310_unit.bp
  units/UAB2101/UAB2101_unit.bp
  units/UAB2104/UAB2104_unit.bp
  units/UAB2108/UAB2108_unit.bp
  units/UAS0102/UAS0102_unit.bp
  units/UEA0104/UEA0104_unit.bp
  units/UEA0203/UEA0203_unit.bp
  units/UEA0304/UEA0304_unit.bp
  units/UEA0305/UEA0305_unit.bp
  units/UEB2101/UEB2101_unit.bp
  units/UEB2104/UEB2104_unit.bp
  units/UEB2108/UEB2108_unit.bp
  units/UEB2204/UEB2204_unit.bp
  units/UEL0106/UEL0106_unit.bp
  units/UEL0202/UEL0202_unit.bp
  units/UEL0203/UEL0203_unit.bp
  units/UEL0303/UEL0303_unit.bp
  units/UEL0401/UEL0401_unit.bp
  units/URA0104/URA0104_unit.bp
  units/URA0304/URA0304_unit.bp
  units/URA0401/URA0401_unit.bp
  units/URB2101/URB2101_unit.bp
  units/URB2108/URB2108_unit.bp
  units/URB2301/URB2301_unit.bp
  units/URL0107/URL0107_unit.bp
  units/URL0202/URL0202_unit.bp
  units/URL0205/URL0205_unit.bp
  units/URL0402/URL0402_unit.bp
  units/URS0103/URS0103_unit.bp
  units/URS0201/URS0201_unit.bp
  units/URS0202/URS0202_unit.bp
  units/URS0302/URS0302_unit.bp
  units/XAA0305/XAA0305_unit.bp
  units/XAL0203/XAL0203_unit.bp
  units/XEA0306/XEA0306_unit.bp
  units/XRA0105/XRA0105_unit.bp
  units/XRA0305/XRA0305_unit.bp
  units/XRL0403/XRL0403_unit.bp
  units/XSA0104/XSA0104_unit.bp
  units/XSA0203/XSA0203_unit.bp
  units/XSB2101/XSB2101_unit.bp
  units/XSB2104/XSB2104_unit.bp
  units/XSB2108/XSB2108_unit.bp
  units/XSB2204/XSB2204_unit.bp
  units/XSL0101/XSL0101_unit.bp
  units/XSL0201/XSL0201_unit.bp
  units/XSL0202/XSL0202_unit.bp
  units/XSL0401/XSL0401_unit.bp
  units/XSL0402/XSL0402_unit.bp
  units/XSS0202/XSS0202_unit.bp
  units/XSS0203/XSS0203_unit.bp
Labels: area: automated testing

#5953 New mesh and normal texture for the valiant
  units/UES0201/UES0201_LOD0.scm
  units/UES0201/UES0201_normalsTS.dds
Labels: area: graphics

#5964 Evaluate and rework the categories of cybran naval units
  units/URS0103/URS0103_unit.bp
Labels: area: unit categories

#5963 Improve the handling of all movable Sonars
  units/UAS0305/UAS0305_unit.bp
  units/UES0305/UES0305_unit.bp
  units/URS0305/URS0305_unit.bp
  units/XSB3202/XSB3202_unit.bp
Labels: feature: pathfinding

#5959 Fix the Cybran T3 and the Seraphim T2 Sonars being able to evade beam weapons
  units/URS0305/URS0305_unit.bp
  units/XSB3202/XSB3202_unit.bp
Labels: feature: collision shapes

#5922 Fix Aeon and UEF T2 transport slot/clamp count for "load into transports" command
  loc/US/strings_db.lua
  units/UAA0104/UAA0104_unit.bp
  units/UEA0104/UEA0104_unit.bp
  units/XEA0306/XEA0306_unit.bp
Labels: area: unit-blueprint, feature: transports

#5885 Fix Aeon T1 and Seraphim T1/T2 transports blocking construction
  units/UAA0107/UAA0107_unit.bp
  units/XSA0104/XSA0104_unit.bp
  units/XSA0107/XSA0107_unit.bp
Labels: feature: transports

#5947 Make unbuilt structures and experimentals not spawn a wreck
  lua/sim/Unit.lua
Labels: area: balance

#5881 Improve the descriptions of various Seraphim units + update the Enhanced Sensor System upgrade
  loc/US/strings_db.lua
Labels: area: ui

#5978 Correctly make Ythotha turn towards its target
  engine/Core/Blueprints/WeaponBlueprint.lua
  units/XSL0401/XSL0401_unit.bp
Labels: area: balance

#5979 Improve Fatboy attack angle and give it a longer projectile lifetime
  units/UEL0401/UEL0401_unit.bp
Labels: area: balance

#5986 Fix experimental wrecks disappearing
  changelog/3802.md
  lua/sim/Unit.lua
Labels: type: bug

#4477 Print chat message when game is paused / unpaused
  lua/ui/game/clientutils.lua
  lua/ui/game/gamemain.lua
Labels: area: ui

#5993 Process moderator requests
  changelog/3802.md
  lua/SimCallbacks.lua
  lua/userInit.lua
Labels: area: ui

#5997 Remove full redundancy from reclaim commands
  changelog/3802.md
  lua/sim/commands/shared.lua
Labels: feature: distribute orders

#5998 Mongoose visual fix
  changelog/3802.md
  units/DEL0204/DEL0204_lod0.scm
  units/DEL0204/DEL0204_normalsTS.dds
  units/DEL0204/del0204_albedo.dds
  units/DEL0204/del0204_specteam.dds
Labels: area: graphics

#6004 add antinavy category to CZAR UAA0310
  units/UAA0310/UAA0310_unit.bp
Labels: area: unit categories

#6002 Simplify the setup for moderator events
  engine/User.lua
  lua/SimCallbacks.lua
  lua/SimPing.lua
  lua/SimSync.lua
  lua/UserSync.lua
  lua/keymap/misckeyactions.lua
  lua/userInit.lua
Labels: area: ui, area: tooling

#6008 Remove `ANTIMISSILE` category from Brick
  changelog/3804.md
  units/XRL0305/XRL0305_unit.bp
Labels: area: unit categories

#6005 Remove the 'BUILTBYEXPERIMENTALSUB' category from various units
  changelog/3804.md
  units/UAS0102/UAS0102_unit.bp
  units/UAS0103/UAS0103_unit.bp
  units/UAS0201/UAS0201_unit.bp
  units/UAS0202/UAS0202_unit.bp
  units/UAS0203/UAS0203_unit.bp
  units/XAS0204/XAS0204_unit.bp
  units/XES0102/XES0102_unit.bp
  units/XRS0205/XRS0205_unit.bp
  units/XSS0201/XSS0201_unit.bp
  units/XSS0202/XSS0202_unit.bp
  units/XSS0304/XSS0304_unit.bp
Labels: area: unit categories

#6012 CZAR categories - remove antinavy and add weakantinavy
  changelog/3804.md
  units/UAA0310/UAA0310_unit.bp
Labels: area: unit categories

#6015 Fix a bug and extend the context based templates feature
  changelog/3804.md
  lua/ui/game/hotkeys/context-based-templates.lua
  units/XEB0204/XEB0204_unit.bp
  units/XRB0204/XRB0204_unit.bp
  units/XRB0304/XRB0304_unit.bp
Labels: type: bug, feature: context-based templates

#6016 Rework/context based templates
  changelog/3804.md
  engine/User.lua
  lua/ui/game/hotkeys/context-based-templates-data.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendOpticsWithPower.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendPowerGeneratorsToSoothsayer.lua
  lua/ui/game/hotkeys/context-based-templates-data/T1Extractor.lua
  lua/ui/game/hotkeys/context-based-templates-data/T2ExtractorWithStorages.lua
  lua/ui/game/hotkeys/context-based-templates-data/T3Extractor.lua
  lua/ui/game/hotkeys/context-based-templates.lua
  lua/ui/templates_factory.lua
Labels: feature: context-based templates

#6013 Fix exploit with the `Copy/Distribute orders` feature
  changelog/3804.md
  engine/Core.lua
  engine/Sim.lua
  engine/Sim/ReconBlip.lua
  lua/sim/commands/distribute-queue.lua
  lua/sim/commands/shared.lua
Labels: type: bug, feature: distribute orders

#6010 Re-add hotkey label for attack move
  changelog/3804.md
  lua/keymap/hotkeylabels.lua
Labels: area: ui

#6009 Adjust 'BOMB' category usage and add torpedo/normal bomber selection hotkeys
  changelog/3804.md
  engine/Core/Categories.lua
  loc/US/strings_db.lua
  lua/keymap/keyactions.lua
  lua/keymap/keydescriptions.lua
  units/DAA0206/DAA0206_unit.bp
  units/URL0303/URL0303_unit.bp
Labels: feature: hotkeys, area: unit categories

#6006 Tweaks to the categories of various blueprints
  changelog/3804.md
  units/UAL0001/UAL0001_unit.bp
  units/UAL0301/UAL0301_unit.bp
  units/UEL0001/UEL0001_unit.bp
  units/UEL0301/UEL0301_unit.bp
  units/URL0001/URL0001_unit.bp
  units/URL0301/URL0301_unit.bp
  units/XAB1401/XAB1401_unit.bp
  units/XSL0001/XSL0001_unit.bp
  units/XSL0301/XSL0301_unit.bp
  units/XSS0303/XSS0303_unit.bp
Labels: area: unit categories

#6017 Add the `UpgradesFromBase` field to the tech 2 mass extractors
  changelog/3805.md
  engine/Core/Blueprints/UnitBlueprint.lua
  lua/ui/game/hotkeys/context-based-templates-data/AppendExtractorWithStorages.lua
  lua/ui/lobby/changelogData.lua
  lua/version.lua
  mod_info.lua
  units/UAB1202/UAB1202_unit.bp
  units/UEB1202/UEB1202_unit.bp
  units/URB1202/URB1202_unit.bp
  units/XSB1202/XSB1202_unit.bp
Labels: type: bug, area: sim, area: unit-blueprint

#6022 Fix Seraphim Air Factories being harder to place than other factories
  changelog/3806.md
  units/XSB0102/XSB0102_unit.bp
  units/XSB0202/XSB0202_unit.bp
  units/XSB0302/XSB0302_unit.bp
  units/ZSB9502/ZSB9502_unit.bp
  units/ZSB9602/ZSB9602_unit.bp
Labels: type: bug, area: sim

#6026 Fix lingering build queue icons
  changelog/3806.md
  lua/userInit.lua
Labels: type: bug, area: ui

#6021 Sync playable area in `UIScenarioInfo` table
  changelog/3806.md
  engine/Core/Blueprints/UnitBlueprint.lua
  engine/User.lua
  lua/ScenarioFramework.lua
  lua/UserSync.lua
  lua/simInit.lua
  lua/ui/controls/reticle.lua
  lua/ui/game/score.lua
  lua/ui/maputil.lua
Labels: type: bug, area: ui

#6027 Implementation for the 'Nyan cat' seasonal event
  effects/emitters/nyan_01.bp
  effects/emitters/nyan_02.bp
  effects/emitters/nyan_trail.bp
  projectiles/ADFOverCharge01/ADFOverCharge01_script.lua
  projectiles/CDFCannonMolecularOvercharge01/CDFCannonMolecularOvercharge01_script.lua
  projectiles/SDFChronatronCannon02/SDFChronatronCannon02_script.lua
  projectiles/TDFOverCharge01/TDFOverCharge01_script.lua
  textures/particles/NyanMini.dds
  textures/particles/NyanMiniFlipped.dds
  textures/particles/NyanRamp.dds
  textures/particles/NyanTrail.dds
Labels: area: graphics
