Repository FAForever/fa, pull requests merged in 2025-03, with the labels that each got.

#6608 Fix text overflow in fixed width tooltips when using UI scaling
  changelog/snippets/fix.6608.md
  lua/ui/game/tooltip.lua
Labels: type: bug, area: ui

#6646 Remove the chat sound when watching a replay
  changelog/snippets/fix.6646.md
  lua/ui/game/chat.lua
Labels: ui: chat window

#6698 Update hover cursor texture only when changed
  changelog/snippets/fix.6698.md
  lua/ui/controls/worldview.lua
Labels: area: ui

#6635 Enable counterintel by default for AI units
  changelog/snippets/ai.6635.md
  engine/Enums.lua
  engine/Sim/Entity.lua
  engine/Sim/Unit.lua
  lua/aibrains/campaign-ai.lua
  units/DRA0202/DRA0202_Script.lua
  units/UEA0304/UEA0304_Script.lua
  units/URA0303/URA0303_Script.lua
  units/URA0304/URA0304_Script.lua
  units/URA0401/URA0401_script.lua
  units/URL0101/URL0101_Script.lua
  units/XRA0305/XRA0305_script.lua
Labels: type: enhancement, area: AI

#6679 Resolve circular dependency of WorldView and CommandMode
  changelog/snippets/other.6679.md
  lua/ui/game/commandmode.lua
Labels: area: ui

#6684 Console improvements
  changelog/snippets/fix.6684.md
  lua/ui/dialogs/console.lua
Labels: area: ui

#6683 Yet another shader rework
  effects/terrain.fx
Labels: area: graphics

#6681 Don't initialize/alter objects during module loading in `Construction.lua`
  changelog/snippets/fix.6681.md
  lua/ui/game/construction.lua
  lua/ui/game/gamemain.lua
Labels: area: ui

#6701 Fix exploit that spawns partially built units out of external factories on transfer
  changelog/snippets/fix.6701.md
  lua/SimUtils.lua
Labels: type: bug, area: sim, feature: mobile factories

#6702 Fix unbuilt units staying around when issued with BuildMobile to external factories and cancelled
  changelog/snippets/fix.6702.md
  lua/defaultcomponents.lua
  units/UEL0401/UEL0401_script.lua
Labels: type: bug, area: sim, feature: mobile factories
