Repository FAForever/fa, pull requests merged in 2025-06, with the labels that each got.

#6835 Revert "Fix factories not immediately building queue after finished upgrades or cancelled land/navy units"
  changelog/snippets/fix.6835.md
  lua/sim/units/FactoryUnit.lua
Labels: type: bug

#6844 Fix error when eye of rhianne finishes building during e stall
  changelog/snippets/fix.6844.md
  units/XAB3301/XAB3301_script.lua
Labels: type: bug, area: sim

#6799 Annotate exit callbacks
  changelog/snippets/other.6799.md
  lua/system/performance.lua
  lua/ui/override/Exit.lua
Labels: type: intellisense

#6797 Move teleport reticle out of command mode data
  changelog/snippets/other.6797.md
  lua/ui/controls/worldview.lua
Labels: area: ui

#6837 Improve annotations related to Buffs
  changelog/snippets/other.6837.md
  lua/sim/AdjacencyBuffFunctions.lua
  lua/sim/Buff.lua
  lua/sim/Unit.lua
  lua/sim/units/StructureUnit.lua
  lua/system/BuffBlueprints.lua
Labels: area: code style, type: intellisense

#6832 Annotation fixes for the profiler
  changelog/snippets/other.6832.md
  engine/Library.lua
  engine/User/CMauiItemList.lua
  engine/User/CMauiText.lua
  lua/shared/DebugFunction.lua
  lua/sim/Profiler.lua
  lua/ui/controls/combo.lua
  lua/ui/game/Profiler.lua
  lua/ui/game/ProfilerElements.lua
  lua/ui/game/tooltip.lua
Labels: area: code style, type: intellisense

#6798 Annotate worldview control and ping data
  changelog/snippets/other.6798.md
  engine/User/CMauiEdit.lua
  engine/User/CUIWorldView.lua
  engine/User/CameraImpl.lua
  lua/SimPing.lua
  lua/SimSync.lua
  lua/ui/controls/worldview.lua
  lua/ui/game/ping.lua
Labels: type: intellisense

#6763 Add a game option for shadow LOD
  changelog/snippets/graphics.6763.md
  lua/options/options.lua
  lua/ui/game/gamemain.lua
  lua/ui/help/tooltips.lua
Labels: area: graphics

#6845 Fix various issues with announcements
  changelog/snippets/fix.6845.md
  lua/ui/game/announcement.lua
  lua/ui/game/announcement/AbstractAnnouncement.lua
Labels: area: ui

#6853 Reduce conditional table accesses of projectiles when colliding or losing targets
  changelog/snippets/performance.6853.md
  lua/sim/Projectile.lua
Labels: area: code style, area: sim

#6870 Reevaluate the `UniformScale` and related values of the Bulwark and the Mermaid
  changelog/snippets/balance.6870.md
  units/XES0205/XES0205_script.lua
  units/XES0205/XES0205_unit.bp
  units/XRS0205/XRS0205_unit.bp
Labels: area: balance, area: balance idea

#6851 Extend the rendering distance of all tree (groups)
  changelog/snippets/graphics.6851.md
  lua/sim/units/uef/TConstructionPodUnit.lua
  lua/system/blueprints-props.lua
Labels: area: graphics

#6705 Adjust Aeon range/speed gun upgrade costs
  changelog/snippets/balance.6705.md
  units/UAL0001/UAL0001_unit.bp
Labels: area: balance idea
