Repository FAForever/fa, pull requests merged in 2025-04, with the labels that each got.

#6686 Improve annotations
  engine/Sim/CAiBrain.lua
  engine/Sim/CAiPersonality.lua
  engine/Sim/CPlatoon.lua
  lua/AI/OpAI/BaseManager.lua
  lua/AI/OpAI/BaseManagerPlatoonThreads.lua
  lua/AI/OpAI/ReactiveAI.lua
  lua/AI/aiutilities.lua
  lua/ScenarioFramework.lua
  lua/ScenarioPlatoonAI.lua
  lua/SimObjectives.lua
  lua/aibrain.lua
  lua/aibrains/campaign-ai.lua
  lua/cinematics.lua
  lua/dataInit.lua
  lua/platoon.lua
  lua/scenariotriggers.lua
  lua/sim/ScenarioUtilities.lua
  lua/sim/Unit.lua
  lua/sim/units/CommandUnit.lua
  lua/sim/weapon.lua
Labels: area: AI, type: intellisense

#6664 Fix issues in create unit dialog
  changelog/snippets/fix.6664.md
  lua/ui/dialogs/createunit.lua
Labels: type: bug, area: ui, feature: mod compatibility

#6662 Refactor weapon turret setup validation
  changelog/snippets/other.6662.md
  lua/sim/Unit.lua
  lua/sim/weapon.lua
Labels: type: enhancement, area: sim

#6614 Fix error on death when ACU/SACU drone pods are built without ACU/SACU
  changelog/fix.6614.md
  lua/sim/units/uef/TConstructionPodUnit.lua
  lua/sim/units/uef/TPodTowerUnit.lua
  units/UEL0301/UEL0301_script.lua
  units/XEA3204/XEA3204_script.lua
Labels: type: bug, area: sim

#6660 Make mass fabs use overflowed energy
  changelog/snippets/fix.6660.md
  engine/Core.lua
  engine/Sim/CAiBrain.lua
  engine/User.lua
  lua/aibrains/components/EnergyManagerBrainComponent.lua
  lua/shared/FabricatorBehaviorParams.lua
Labels: type: bug, area: sim

#6669 Add several useful blueprint modding functions
  changelog/snippets/features.6669.md
  engine/Core/Blueprints/EntityBlueprint.lua
  engine/Core/Blueprints/UnitBlueprint.lua
  engine/Core/Blueprints/WeaponBlueprint.lua
  lua/MODS.LUA
  lua/system/Blueprints.lua
Labels: type: enhancement, feature: mod compatibility

#6714 Fix the hitbox of the Volcano
  changelog/snippets/fix.6714.md
  units/UAB4201/UAB4201_unit.bp
Labels: feature: collision shapes

#6676 Fix dual yaw controller affecting unit pitch
  changelog/snippets/fix.6676.md
  engine/Sim.lua
  engine/Sim/CAimManipulator.lua
  engine/Sim/UnitWeapon.lua
  lua/sim/weapon.lua
Labels: type: bug, area: sim

#6682 Improve intellisense plugin
  .vscode/fa-plugin.lua
  changelog/snippets/fix.6682.md
  changelog/snippets/other.6682.md
  lua/lazyvar.lua
Labels: type: intellisense

#6723 Fix Sera T1 transport attempting to load more T3 units than it has slots with "load into transports"
  changelog/snippets/fix.6723.md
  units/XSA0107/XSA0107_unit.bp
Labels: type: bug

#6680 Annotate SetWeaponPriorites callback and usage
  changelog/snippets/other.6680.md
  lua/SimSync.lua
  lua/UserSync.lua
  lua/WeaponPriorities.lua
  lua/keymap/misckeyactions.lua
Labels: type: intellisense

#6601 Include the projectile in the OnMissileIntercepted callback
  changelog/snippets/other.6601
  lua/sim/Projectile.lua
  lua/sim/Unit.lua
Labels: area: AI

#6731 Fix blueprint loading crash for `nil` death animation
  changelog/snippets/fix.6731.md
  lua/system/blueprints-units.lua
Labels: type: bug

#6735 AI - add filter for non engineering units in Engineer Manager callback
  changelog/snippets/fix.6735.md
  lua/sim/EngineerManager.lua
Labels: area: AI

#6743 Fix error when air staging gets killed when dead
  changelog/snippets/balance.6665.md
  lua/sim/units/AirStagingPlatformUnit.lua
Labels: type: bug, area: sim

#6692 Fix factories not immediately building queue after finished upgrades or cancelled land/navy units
  changelog/snippets/fix.6692.md
  lua/sim/units/FactoryUnit.lua
Labels: type: bug, area: sim, experimental! do not release

#6741 Refactor screen indicator
  changelog/snippets/other.6741.md
  lua/ui/controls/worldview.lua
  lua/ui/game/OffScreenIndicator.lua
  lua/ui/game/OffScreenMarkerIndicator.lua
  lua/ui/game/common/AnimatedGlow.lua
Labels: area: ui

#6739 Refactor custom world rendering of shapes
  changelog/snippets/other.6739.md
  engine/User.lua
  engine/User/CUIWorldView.lua
  lua/ui/controls/components/WorldViewShapeComponent.lua
  lua/ui/controls/draggers/radial.lua
  lua/ui/controls/draggers/rectangle.lua
  lua/ui/controls/worldview.lua
  lua/ui/game/shapes/CircleShape.lua
  lua/ui/game/shapes/LineShape.lua
  lua/ui/game/shapes/Shape.lua
  lua/ui/game/shapes/SquareShape.lua
Labels: area: code style, area: ui

#6742 Fix shield assist issuing orders to an empty table
  changelog/snippets/fix.6742.md
  lua/shield.lua
Labels: type: bug, area: sim

#6732 Add list of reviewers and snippet guidelines to PR template
  .github/pull_request_template.md
Labels: area: documentation

#6687 Move lobby presets into their own file
  changelog/snippets/fix.6687.md
  lua/ui/lobby/lobby.lua
  lua/ui/lobby/presets.lua
Labels: area: code style, area: ui, area: lobby

#6749 Fix various gunships and the Dragon Fly being unable to hit units that are directly beneath them
  changelog/snippets/balance.6749.md
  units/UAA0203/UAA0203_unit.bp
  units/UEA0203/UEA0203_unit.bp
  units/URA0104/URA0104_unit.bp
  units/URA0401/URA0401_unit.bp
  units/XAA0305/XAA0305_unit.bp
  units/XRA0105/XRA0105_unit.bp
Labels: type: bug, area: balance, area: unit-blueprint, area: balance idea

#6414 Increase the usefulness of the Cooper and compensate for previous changes to its hitbox
  changelog/snippets/balance.6414.md
  units/XES0102/XES0102_unit.bp
Labels: area: balance
